### ISSUE TITLE
Typeaheads internal "wrapper" css

### ISSUE THREAD

**Issue by robvon** [twitter/typeahead.js#1000]
I've had to patch to change 'display: inline-block' to 'display:block' for my page in the css.wrapper markup. The inline-block, behaves as it is supposed to, in taking a minimal width approach to the target input element. In applications where the existing markup through bootstrap and other css is to fill the width, applying the current wrapper breaks the layout - well shortens it anyway.

Perhaps this could be surfaced as an option like the hint ?

Regards

Rob

**Comment by jharding** [comment]
Yep this stuff got overhauled in v0.11 and I'll be documenting it in the coming days.
