### ISSUE TITLE
Cursor doesn't set focus (can't use native HTML links)

### ISSUE THREAD

**Issue by DanielHeath** [twitter/typeahead.js#1003]
I'm trying to enable (e.g.) right-click -> open in new tab.

To do this, I've changed my app from navigating in the select event to using an <a> on each search result.

This works nicely, except that using the arrow keys to select a search result & then pressing enter doesn't do anything.

In https://github.com/twitter/typeahead.js/blob/master/src/typeahead/dropdown.js#L102
we could set :focus on the element - this would mean that arrows+enter would work for <a> tags.

Are there any downsides to adding this? Design considerations I've missed?

**Comment by jharding** [comment]
Setting focus on the suggestion would cause focus to be lost from the text input which would cause a bunch of issues. Couldn't you just add another event handler that listens for enter key presses?

**Comment by DanielHeath** [comment]
I can add it application-side; shouldn't this be built-in?

**Comment by jharding** [comment]
Perhaps I don't quite understand what you're trying to do. What event are you listening on the suggestions for to navigate?
