### ISSUE TITLE
handling search items which have aliases

### ISSUE THREAD

**Issue by seme1** [twitter/typeahead.js#1009]
I am trying to implement something similar to the stackoverflow tag suggestion input field. In the database, I have two tables: one is for tags and another is for tagaliases. 

When a user types a term, the search engine should be smart enough to detect the aliases of the typed term, and display only the main tag corresponding to the typed term. What is the best way for implementing this with bloodhound ?

**Comment by jharding** [comment]
You'd want to write a custom tokenizer:

```js
function customTokenizer(obj) {
  return obj.tags.concat(Bloodhound.tokenizers.obj.whitespace('val'));
}
```
