### ISSUE TITLE
Recommended way to use multiple datasets sharing same remote source

### ISSUE THREAD

**Issue by dhruvg** [twitter/typeahead.js#1010]
I have a remote source which can output data like:

{
  "dataset 1": [{ "name" => "abc" }, {"name" => "xyz"}],
  "dataset 2": [{ "name" => "def" }, {"name" => "ghi"}]
}

The reason I want to do it this way is so I only make one network call.

What is the ideal way to specify typeahead options so that this response is treated like two separate datasets?

**Comment by django-emerge** [comment]
late to the party, but chiming in as i just encountered a similar situation...

i am not sure it is ideal, but an approach that worked for me was making one ajax call, capturing that data to a local variable, and then using an array of local datums for each bloodhound datasource.  here's a rough example (**code not tested**):
```javascript
var myData;

$.get('http://some.url/get_my_data', function(data){
  myData = data;  // capture the data from your remote call so you can use local data sources.

  // create your bloodhound data sources for each of your data sets using LOCAL sources
  var dataSource1 = new Bloodhound({
					datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
					queryTokenizer: Bloodhound.tokenizers.whitespace,
					local: myData.dataset1,  // set this to the first data set coming back from your remote source
					limit:3
				});
  var dataSource2 = new Bloodhound({
					datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
					queryTokenizer: Bloodhound.tokenizers.whitespace,
					local: myData.dataset2, // set this to the second data set coming back from your remote source
					limit:3
				});

  // declare typeahead as you normally would for multiple data sets
  $('#my-typeahead').typeahead({
					highlight: true,
				},
				{
					name: 'dataset-1',
					displayKey: 'value',
					source: dataSource1.ttAdapter()
				},
				{
					name: 'dataset-2',
					displayKey: 'value',
					source: dataSource2.ttAdapter()
				});
});
```

bear in mind, depending on how quickly the ajax request comes back, this approach may introduce some lag into the availability of the typeahead to the user.  you also lose the features available to remote bloodhound datasources.  but something like it worked for me.
