### ISSUE TITLE
Not much response here

### ISSUE THREAD

**Issue by getub** [twitter/typeahead.js#1018]
There hasn't been much activity here on commits & response to issues. There was a similar hiatus about a year ago (https://github.com/twitter/typeahead.js/issues/466). It's likely that @jharding has been busy with getting 0.11 out the door. Any official word?

**Comment by jharding** [comment]
Yeah, I've been busy and no one else maintains this project. Going to try and recruit some help this week.

**Comment by ionutzp** [comment]
@jharding found somebody interested in contributing yet?

**Comment by gaborbernat** [comment]
I offered my services like a month ago. Absolutely no response, although I tried via mail, twitter.

**Comment by getub** [comment]
@gaborbernat Also see #1320. Any interest in reviving this as a fork?

**Comment by gaborbernat** [comment]
could be part of it, not on my own :)

**Comment by Ghostavio** [comment]
@getub @gaborbernat let's wait maybe one more week, if there's no response I don't mind maintaining it as a fork with you and anyone else willing to help
