### ISSUE TITLE
focus of input lost when setting up typeahead

### ISSUE THREAD

**Issue by evirca** [twitter/typeahead.js#1020]
In a lazy loading scenario I am trying to bind typeahead to input only if the input is focused for the first time. After typeahead is applied the input loses focus so i have to click again in the input to start writing. Any idea why this is happening?

**Comment by mkleehammer** [comment]
I'm not sure why this was closed without comment...

I wouldn't use 'click' since that won't work when tabbing into the control.  Instead, use `setTimeout` to apply focus after the current microtask - different browsers handle focus differently:

```
function onFocus(e) {
  var ctrl = $(e.target);
  var tt = ctrl.data('tt-typeahead'); // from typeahead's src/typeahead/plugin.js
  if (!tt) {
    ctrl.typeahead( ... );
    // The TT control messes with DOM so we lose our focus.  Set it again ourselves.
    setTimeout(function() { ctrl.focus(); }, 0);
  }
}
```

**Comment by kratosvn** [comment]
i have samed problem and here is my code:
function suggestKeyword(id_input, data) {
    var states = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: data
    });
    **$('#' + id_input).typeahead({
        hint: true,
        highlight: true,
        minLength: 1
    },
    {
        name: 'states',
        source: states
    });
    $('#' + id_input).promise().done(function() {
        $('#' + id_input).focus();
    });**
}

**Comment by warrenspe** [comment]
Did a bit of investigation into this; appears as though focus is lost because the element is removed and re-added to the DOM within a tt wrapper.  A fix for this could be to check if the input has focus before removing it, and re-adding it afterwards if it did.
