### ISSUE TITLE
Add method for triggering suggestion update

### ISSUE THREAD

**Issue by crhallberg** [twitter/typeahead.js#1021]
I have a case where the user can pick what source their results come from in a dropdown. Adding a method that allows a programmer to trigger a refresh of the results would go far to increase the flexibility of this tool.

Or I'm just missing it.

**Comment by jharding** [comment]
If you wanted to refresh results, but keep the same query, you could do this:

```js
$('.typeahead').typeahead('val', '').typeahead('val', prevQuery);
```

It's a little hacky, but it should get the job done. Not sure if it's worth adding something along the lines of `jQuery#typeahead('refresh')`.

**Comment by crhallberg** [comment]
Thank you!
