### ISSUE TITLE
Bloodhound doesn't escape brackets from query.

### ISSUE THREAD

**Issue by bartroza** [twitter/typeahead.js#1026]
I'm using typeahead.bundle.js, and encountered issue when typed bracktes "[" or "(", then regex fails e.g. in first example on [examples](http://twitter.github.io/typeahead.js/examples/):

```Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class```

In my case I've similar errors on server side when querying mongodb by regex. I want to disable sending brackets in queryTokenizer() but it doesn't apply new string it is a bug?
```javascript
var bloo_tags = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace('text'),
  queryTokenizer: function(query) {
    query = query.replace(/([.?*+^$[\]\\(){}|-])/g, "");
    Bloodhound.tokenizers.whitespace(query);
  },
  remote: '/tags/%QUERY.json'
});
```

**Comment by jharding** [comment]
Looks like is a bug in the example code, not typeahead.js. The first example uses an ad-hoc source, not a bloodhound instance. If you play with the other examples, you'll notice this bug doesn't exist.
