### ISSUE TITLE
Placeholder text doesn't disappear on focus

### ISSUE THREAD

**Issue by altrugon** [twitter/typeahead.js#1027]
I have noticed that the placeholder text doesn't disappear when the input text box receives the focus but when the user start to type.

This kind of goes against the [HTML5 behaviour](http://www.w3.org/TR/html5/forms.html#the-placeholder-attribute) for this attribute.

> User agents should present this hint to the user, after having stripped line breaks from it, when the element's value is the empty string and the control is not focused (i.e., by displaying it inside a blank unfocused control).

Could this be resolved?

Thank you.

**Comment by jharding** [comment]
typeahead.js isn't doing anything special here.
