### ISSUE TITLE
Custom template without Handlebars

### ISSUE THREAD

**Issue by raxan** [twitter/typeahead.js#1031]
Hi

how to custom template without handlebars dep?

thanks

**Comment by mnquintana** [comment]
:+1:

**Comment by netwire88** [comment]
How do you access `data.year`? I have a similar code but the only variable I see is data.value. Do I need to modify `filter` in Bloodhound or something?

**Comment by brendanfalkowski** [comment]
I only tested using the example data, but this to see exactly what's in `data`:

```
suggestion: function (data) {
    console.log(data);
}
```

**Comment by netwire88** [comment]
It turns out typeahead doesn't like JSON names with an underscore. So `image_url` doesn't work but `imageurl` does. Very odd.

**Comment by nodiced922** [comment]
This was a great help @brendanfalkowski  Thanks for directly including the code !!

**Comment by razvanphp** [comment]
Just a note, with the new 0.11 version, this only works if you wrap everything in `div` instead of `p`. Any idea why and if this is intentional?

**Comment by ZaneCEO** [comment]
@razvanphp I foud this issue searching for confirmation to the same. The returned HTML gets converted to a DOM node, so any non-valid text screws it up.. dunno if its intentional, but smells buggy to me.

**Comment by hala3amme** [comment]
what if i have an array within the data ? how i can deal with it ?

<pre>
<code>
data = [
{
category: 'category 1',
docs:['doc1', 'doc2', 'doc3']
},
{
category: 'category 2',
docs:['doc4', 'doc5', 'doc6']
},
]
</code>
</pre>

**Comment by phlegx** [comment]
@PierBover thx :+1:  :smile:

**Comment by PierBover** [comment]
@hala3amme you should be able form a string from that array and simply return that.

**Comment by zenithtekla** [comment]
Workaround for footer. It took me hours to figure out. I could have fixed it if I were to see this post first:

``` javascript
$.ajax({
  dataType: "json",
  url: "../model/json_db/formats.php"})
  .done( function(data) {

    /*    $.each(data,function(i,v){
            console.log(v.format);
            $.each(v,function(i,va){
                console.log(va);
            })
        });
      $.map(data, function(obj) { 
        console.log(obj.format + "example" + obj.format_example);
      }); http://forum.jquery.com/topic/jquery-and-json-troubles */
      // constructs the suggestion engine
      var engine = new Bloodhound({
        datumTokenizer: function (datum) {
          return Bloodhound.tokenizers.whitespace(datum.value);
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        // `data` is an array of country names defined in "The Basics"
        local: $.map(data, function(obj) { 
            return { value : obj.format, eg: obj.format_example };
        }),
        limit: 10
      });

      // kicks off the loading/processing of `local` and `prefetch`
      engine.initialize();
     $('#scrollable-dropdown-menu .typeahead').typeahead(null, {
          name: 'data',
          displayKey: 'value',
          hint: true,
          highlight: true,
          minLength: 1,
          source: engine.ttAdapter(),
          templates: {
              empty: [
                '<div class="empty-message">',
                  'Result not found',
                '</div>'
              ].join('\n'),
              suggestion: Handlebars.compile("<div style='padding:6px'><b>{{value}}</b> - example : {{eg}} </div>"),
              // footer: "<b>Searched for "+ console.log($('input.typeahead.tt-input').val()+"</b>"
              footer: function (data) {
                // return Handlebars.compile("<b>Searched for {{data.query}} </b>")
                return '<div>Searched for <strong>' + data.query + '</strong></div>';
              }
          }
      });
```

**Comment by zenithtekla** [comment]
I could still use normal callback func to return suggestion but I decide to leave it there for now. Feel free to give your input.
