### ISSUE TITLE
Index not being bootstraped when using local data

### ISSUE THREAD

**Issue by martinffx** [twitter/typeahead.js#1033]
I've intialised bloodhound using the local data option, I get no errors but when I query bloodhound I don't get any results. 

After some digging I end up here: 

    var SearchIndex = function () {
        ...
        get: function get(query) {
                        var that = this, tokens, matches;
                        tokens = normalizeTokens(this.queryTokenizer(query));
                        _.each(tokens, function (token) {
                            var node, chars, ch, ids;
                            if (matches && matches.length === 0) {
                                return false;
                            }
                            node = that.trie;
                            chars = token.split("");
                            while (node && (ch = chars.shift())) {
                                node = node.children[ch];
                            }
                            if (node && chars.length === 0) {
                                ids = node.ids.slice(0);
                                matches = matches ? getIntersection(matches, ids) : ids;
                            } else {
                                matches = [];
                                return false;
                            }
                        });
                        return matches ? _.map(unique(matches), function (id) {
                            return that.datums[id];
                        }) : [];
                    },

more specifically `node = that.trie` which appears to not have been initialised properly. As far as I can tell `trie` is set in the `SearchIndex.bootstrap` function, which is only called by the `Bloodhound._loadPrefetch` function which is only called during initialisation  if the prefetch object has been set.

    _initialize: function initialize() {
        var that = this, local = this.local, deferred;
        deferred = this.prefetch ? this._loadPrefetch(this.prefetch) : $.Deferred().resolve();
        local && deferred.done(addLocalToIndex);
        this.transport = this.remote ? new Transport(this.remote) : null;
        return this.initPromise = deferred.promise();
        function addLocalToIndex() {
                that.add(_.isFunction(local) ? local() : local);
         }
    },

So `trie` is never set properly when using local data?

Am I doing something wrong when initialising with local data? Or is this a bug? How can I fix it?

**Comment by jharding** [comment]
Cannot reproduce in v0.11.
