### ISSUE TITLE
List of visible elements is not scrolled down following the cursor

### ISSUE THREAD

**Issue by nitoloz** [twitter/typeahead.js#1034]
Hi!
i have used typeahead in a projects as a beautiful and fast suggesting system, but have faced a problem:
My typeahead window has a limited size, but the list of suggested elements could be enormous, so it is impossible to see all the elements is a dropdown window.
When I scroll down using a mouse it works perfectly and selected element from a list is always visible, but when I press the down arrow it works not absolutely correctly. The current selected element in a list is highlighted and I can move up and down using arrows, but when I move too far down (out of the visible window) the highlighted element moves out of the "visible elements window" and it is impossible to see which element I am going to select now.
Is this feature present in current version of typeahead?
thank you

**Comment by jharding** [comment]
It's doubtful this is something typeahead.js would support out of the box. I think if you got clever with the [`typeahead:cursorchange` event](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events), you could solve this problem.
