### ISSUE TITLE
Easy Dataset Retrieveal

### ISSUE THREAD

**Issue by sparestub** [twitter/typeahead.js#1035]
Hi,

I've got a quick question. I thought I might be able to get a quick response here rather than delving into the internals of typeahead.

I'm currently using the prefetch option to get my typeahead dataset for a form's input box.  When the user selects one of typeahead's suggestions, we know that the choice was in the dataset. When the user ignores typeahead's suggestions and enters their own value, I need to do some input validation. I'm hoping to simply compare the inputted value against the dataset that was fetched by typeahead, but I'd prefer not to query the server again for the dataset.  

I have my Bloodhound object, but I have no idea where in there lies the dataset. Can anyone lend a quick helping hand?

Thank you

**Comment by jharding** [comment]
Depending on what exactly you're trying to do, one of the Bloodhound API methods (probably `#search`) is what you're looking for.
