### ISSUE TITLE
Using 'delete' key should remove the hint

### ISSUE THREAD

**Issue by pjfsilva** [twitter/typeahead.js#1042]
Currently, the keyboard support seems to be lacking one important thing that is a way to "not accept" the hint that is given and just use the text that was written.

For example:
1) Try the 1st example "The Basics": http://twitter.github.io/typeahead.js/examples/
2) Write "ala". 
3) Using TAB accepts the hint and a 2nd TAB passes to the next focusable element.

The only way to have the value "ala" on the input is to write it and then use the mouse outside the input field. I believe this is not a coherent pattern as we should also be able to write "ala" only using the keyboard.

I know that the design guidelines are the google.com search bar but google.com allows to search for "ala": you just write and press enter. The problem in typeahead is that ENTER doesn't do anything in this case. Also on google the DELETE key does the same thing as ENTER.

My proposal is to implement the delete key to "remove the hint", so for example:
1) Write "ala" -> hint Alabama is shown
2) Press DEL key -> hint is deleted
3) Press TAB -> navigate to next focusable element (and input stays with "ala")

Another example is this plugin: http://complete-ly.appspot.com/examples/booking.html

If you type something and hit DEL key the "hint" is removed and no autocomplete is done when you press TAB.

For me this is really a behavior that makes sense: the default behavior is that you use TAB and it autocompletes with the hint (because that's the usual case when using this component) but also allow the user to just type "ala" if he really wants to.

**Comment by jharding** [comment]
IMO this would be an unwelcomed behavior to the end-user. There'd be no visual cue telling the end-user this would happen. I'd prefer to leave this as is for now, but people are always welcomed to persuade me otherwise.
