### ISSUE TITLE
Get current dataset matches

### ISSUE THREAD

**Issue by apexskier** [twitter/typeahead.js#1045]
Feature request:

It would be useful to provide a method to get the set of current options based on the current input.

This would allow accepting matches without the user explicitly selecting an option from the dropdown.

My current workaround for this involves scanning the dropdown in the dom, but I only have the text of the option available. Each option in the dataset also has an id that's not available. I could use a template to insert a data-attribute, but this seems like more overhead than necessary.

Something like 

``` javascript
$('.typeahead').typeahead('matches');
```

would return a subset of the original dataset that's currently shown to the user, or currently matches the input.

Questions to answer about this:

- How many values should be returned? Just visible ones? All from remote?
- What happens when the user hasn't entered anything? Return nothing, return everything? (my preference would be nothing)

**Comment by jharding** [comment]
By listening for the [`typeahead:rendered` custom event](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-event), you should be able to track which suggestions are being shown.

**Comment by leizard** [comment]
hi @jharding, I use `typeahead:rendered` event and the suggestions argument always return 1 object not the array of suggestion. Is there anything I miss ?
