### ISSUE TITLE
nonsecure items warning on IE7

### ISSUE THREAD

**Issue by montabou** [twitter/typeahead.js#1046]
Using remote data with Bloodhound leads to a nonsecure warning on IE7:
"Security Information
This page contains both secure and nonsecure items.
Do you want to display the nonsecure items?"

It works well after choosing yes or no... Don't know why this warning occurs.
The remote url parameter is in https...

I've got the same warning on example page: https://twitter.github.io/typeahead.js/
even if it does not use remote but prefetch data

**Comment by jharding** [comment]
IE7 support was dropped in v0.11.
