### ISSUE TITLE
How can I make this bootstrap 3 compatible?

### ISSUE THREAD

**Issue by KrunchMuffin** [twitter/typeahead.js#1049]
It doesn't pass bootlint.

> bootlint:  E010  Input groups cannot contain multiple `.form-control`s

I start off with this

    <div class="input-group">
	    <input type="text" class="form-control" id="NameSearch" placeholder="Name Search">
	    <span class="input-group-btn">
	        <a href="javascript:;" class="btn submit"><i class="fa fa-search"></i></a>
	    </span>
    </div>

and end up with this

    <div class="input-group">
	<span class="twitter-typeahead" style="position: relative; display: inline-block; direction: ltr;">
		<input type="text" class="form-control tt-hint" readonly="" autocomplete="off" spellcheck="false" tabindex="-1" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(59, 105, 146);">
		<input type="text" class="form-control tt-input" id="NameSearch" placeholder="Name Search" autocomplete="off" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;">
		<pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: 'Open Sans', sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre>
		<span class="tt-dropdown-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none; right: auto;">
			<div class="tt-dataset-Name-Search"></div>
		</span>
	</span>
	<span class="input-group-btn">
		<a href="javascript:;" class="btn submit"><i class="fa fa-search"></i></a>
	</span>
    </div>

**Comment by gitsnail** [comment]
running into the same issue while migrating from bootstrap v2 to v3

**Comment by mrchief** [comment]
:+1
