### ISSUE TITLE
typeahead("open") doesn't work

### ISSUE THREAD

**Issue by thany** [twitter/typeahead.js#1053]
Consider this code:
```
$("input[type=search]")
  .typeahead(...)
  .on("click", function() {
    $(this).typeahead("open");
  });
```
As you can see, I want the dropdown to open when the visitor clicks on the input. Doesn't work. It doesn't matter if there's a value in the input or not (but for clarity: I want it to open regardless).

The problem appears to be the open function in typeahead.bundle.js#1383:
```
open: function open() {
  if (!this.isOpen) {
    this.isOpen = true;
    !this.isEmpty && this._show();
    this.trigger("opened");
  }
},
```
I've stepped through this, and the `isOpen` is property is `true`, even when the dropdown isn't visible. Also, `isEmpty` is `true`, even when I guarantee at least one item (i.e. from a static array).

The root of the problem *could* be that `isOpen` is set to `true` even when `isEmpty` might be `true`, causing the dropdown to remain hidden, while `isOpen` is left `true` without having opened the dropdown.

Anyway, when I tell typeahead to programmatically open the dropdown, I want it to open the dropdown. Period. Any kind of intelligence should be only applied to opening the dropdown as a result of input events.

**Comment by mnquintana** [comment]
I've encountered this issue too. It seems like a typeahead.js bug.

**Comment by solygen** [comment]
+1

**Comment by jarinudom** [comment]
+1

**Comment by tompiard** [comment]
+1

**Comment by jensniedling** [comment]
+1

**Comment by jlbooker** [comment]
+1

**Comment by jharding** [comment]
Yeah the open/close stuff in previous versions of typeahead.js was not great. I tried to simplify it in v0.11. I still need to document how things work now in v0.11, hopefully I can do that within the next few days.
