### ISSUE TITLE
After hitting escape, then enter (autoselect), typeahead:selected is fired, even if menu is closed

### ISSUE THREAD

**Issue by bradlis7** [twitter/typeahead.js#1057]
I'm using this to add tags (for a blog), and I've got the following code:

        $(document).ready(function() {
            $('#AddTag').typeahead({
                minLength: 0,
                highlight: true,
                autoselect: true,
            }, { /* Datasource */ });
            $('#AddTag').bind('typeahead:selected', OnAddTagFromTypeahead);
        });
        function OnAddTagFromTypeahead(evt, tag) {
            console.log(tag);
            // ...
        }

When I hit escape to close the dropdown, then hit enter, it is firing the `typeahead:selected` event, but I don't think it should be.

**Comment by jharding** [comment]
Should be fixed in v0.11.
