### ISSUE TITLE
Call typeahead:selected is not working

### ISSUE THREAD

**Issue by shadeoner** [twitter/typeahead.js#1060]
Hi,

I'm trying to make it works, but can't find solution.

I have complex getting data throught Ajax on typeahead:selected event

So, I want to use it when my page load with for example :

$('.typeahead').trigger('selected', {"id":idvalue, "value":value});

Is anything wrong with it ?

Thank you

**Comment by Parcye** [comment]
I am having exact the same problem. On the webshop www.todotipo.nl the typeahead:selected is not working. 

I have removed it for now and will have to look into it later; if I can't get it working I will try from scratch using jsFiddle or something like that.

**Comment by jharding** [comment]
The `selected` event is for listening for user selections, not for programmatically selecting a suggestion.
