### ISSUE TITLE
Suggestion : Add an options parameter to display full list on click

### ISSUE THREAD

**Issue by ibiza420** [twitter/typeahead.js#1061]
Hi,
I was met with this requirement to show the full list of suggestions on click.

I have found this answer (http://jsfiddle.net/5xxYq/) but it only works if the typeahead source is not from bloodhound engine.

Then I asked the question on StackOverflow and someone provided a fix in the bloodhound engine javascript file : http://stackoverflow.com/questions/27138123/show-full-list-of-suggestions-on-click-with-typeahead-and-bloodhound
And it's working well.

Since I do not like to change the original source code of a plug-in, I was wondering if it would be worthy to add an options parameter on initialization to activate this feature of being able to show the full list of suggestions with no token provided.

Thanks!

**Comment by jharding** [comment]
Doubt I'll add support to Bloodhound for this. You can easily achieve this functionality by simply wrapping the bloodhound instance before passing it to the jQuery plugin:

```js
var bloodhound = new Bloodhound({ /* ... */});

function wrapper(q, sync) {
  if (q === '') {
    sync(bloodhound.all());
  }

  else {
    bloodhound.search(q, sync);
  }
}
```
