### ISSUE TITLE
Keep current input text with autocomplete

### ISSUE THREAD

**Issue by Style87** [twitter/typeahead.js#1062]
I have a search input that goes with a table. I have columns like Name and Customer ID. My goal is to allow customers to search columns like '@Name Foo @Customer-ID 1234'. I've added the columns into the array for the typeahead however whenever a new autocomplete is made it replaces the previous text in its entirety. In the previous example I'd like to autocomplete @Customer-ID without removing @Name Foo. Is it possible? If it's not possible consider this a feature request.

Another prime example is google's search box. It will autocomplete words without modifying the rest of your query string.

**Comment by jharding** [comment]
This is not currently possible and there are other requests for it. If I stumble across the issues, I'll link them here.
