### ISSUE TITLE
Throw error when using Bloodhound without calling initialize()

### ISSUE THREAD

**Issue by jlbooker** [twitter/typeahead.js#1064]
When attempting to use a Bloodhound instance, if bloodhound.initialize() has not been called, then throw an exception and/or log a nice message to the console.

I was trying out Typeahead and Bloodhound for the first time today and missed the call to initialize() (somehow...). Ended up spending far longer than I should've tracking down my mistake. A quick "You need to call initialize() first" message on the console would've helped a lot. :+1:

**Comment by jharding** [comment]
This was actually improved in v0.11. Bloodhounds are now implicitly initialized.
