### ISSUE TITLE
Bug handling leading spaces in queries with hint enabled

### ISSUE THREAD

**Issue by superal1394** [twitter/typeahead.js#1065]
I've discovered a bug with the behavior of typeaheads hints. I can recreate it on the examples page.

Steps to reproduce:
1) Enter a term with a leading space (i.e. ' York')
2) Backspace until only the space remains, observe the erroneous suggested result
3) Backspace again, observe the hint remains with the placeholder text now superimposed on it.

Expected: The box should only show the placeholder text
Reality: Placeholder text and erroneous suggested result are displayed on top of eachother

Clicking out of the box clears the issue.

![image](https://cloud.githubusercontent.com/assets/8291067/5307494/925c711c-7bdb-11e4-9679-155fb86688ab.png)

**Comment by jharding** [comment]
Yikes, nice catch. Will get it fixed for v0.11.

**Comment by jharding** [comment]
Turns out this is just a bug in the example code. I'm not too concerned about fixing it as it's for demonstration purposes only. If you were using bloodhound, you wouldn't encounter this.

**Comment by superal1394** [comment]
Unfortunately I cannot provide screenshots, however I can assure you this does occur when using bloodhound. I will recreate on Monday using non NDA covered projects.
