### ISSUE TITLE
Timeline for version 0.11.0

### ISSUE THREAD

**Issue by addremove** [twitter/typeahead.js#1068]
Requesting the core group for a timeline / roadmap for future developments. I'm a bit anxious since a lot of the pending issues are relevant. I've been eagerly waiting for some of the proposed changes in 0.11.0. 
Appreciate your good work :+1:

**Comment by ansonhoyt** [comment]
+1

**Comment by addremove** [comment]
Anyone from @twitter ? Please let us all know who's managing typeahead.js. It's been 4+ months since any communication.

**Comment by brendanfalkowski** [comment]
FYI ➔ Got a project status response from @jharding on Twitter: https://twitter.com/falkowski/status/556138762494046208

TLDR: hopefully v0.11 in February.

**Comment by addremove** [comment]
:+1:  @brendanfalkowski  Thanks for the update.

**Comment by fabn** [comment]
:+1:

**Comment by frandbf** [comment]
+1

**Comment by rogersillito** [comment]
+1 for #166

**Comment by jharding** [comment]
Released. Sorry for the delay. Going to try to on-board some new maintainers since I don't have much time nowadays to dedicate to typeahead.js.
