### ISSUE TITLE
Running Sauce tests on pull requests

### ISSUE THREAD

**Issue by cvrebert** [twitter/typeahead.js#1069]
So, I notice that Typeahead.js uses Sauce Labs for real-browser JS testing.
I was wondering whether you'd be interested in enabling Sauce testing for pull requests too (while still keeping your Sauce credentials secure)? If so, you might consider using the tool we created to do this for [Bootstrap](https://github.com/twbs/bootstrap): Savage: https://github.com/twbs/savage

If there's interest, I would be more than happy to offer assistance in setting up a Savage instance for Typeahead.js.

**Comment by jharding** [comment]
Thanks for bringing this up (and sorry for the super delayed response), but this functionality is already achieved through travis-ci (unless I'm misunderstanding something).

**Comment by cvrebert** [comment]
@jharding I believe there's a misunderstanding. Your pull requests aren't running real-browser tests currently; e.g. https://travis-ci.org/twitter/typeahead.js/jobs/60392130 ran no tests. Savage would remedy this.
