### ISSUE TITLE
Tab key should work just as the right arrow key

### ISSUE THREAD

**Issue by oxygens** [twitter/typeahead.js#1071]
On wide keyboards, people (including myself) are used to selecting (choosing) the typeahead proposed keyword using the tab key as well as the right arrow key.

Currently, the tab keypress does nothing.

Google Chrome / Chromium uses the tab key as well, as the right arrow key to autocomplete from the typeahead, in the omnibar.

**Comment by jharding** [comment]
Tab key should work...

**Comment by JorgeGomesRaimundo** [comment]
Hi!

The tab key works fine here, but when I use the arrow keys to choose an option and then use the right arrow key to select the desired option, the plugin selects the first option an not the one I chose.

Is this the desired behaviour?

Thanks.
