### ISSUE TITLE
'com.dengyukeji' can't be searched by string 'dengyukeji'

### ISSUE THREAD

**Issue by richardguancn** [twitter/typeahead.js#1076]
Hi,
I want to search 'com.dengyukeji';
when I input 'dengyu', The result dosn't include 'com.dengyukeji'...
If I have a string is 'com dengyukeji',
input 'dengyu', the result will show 'com dengyukeji'.
Can anyone know how to fix it?

Thanks.
Richard.

**Comment by jharding** [comment]
You'd want to use a tokenizer that breaks on the `.` character.
