### ISSUE TITLE
Clean field programmatically

### ISSUE THREAD

**Issue by rafaelroque** [twitter/typeahead.js#1083]
Hi all,

how could I clear a typeahead field in an focousout event?

The following jquery code doesn´t work in a typeahead field:

$( "#field" ).focusout(function() {
	$(this).val("");
	});

**Comment by marcusasplund** [comment]
Use the typeahead API instead of jQuery to manipulate the value;
this should work.
$( "#field" ).focusout(function() {
    $(this).typeahead("val", "");
  });

See:
https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#user-content-jquerytypeaheadval-val

**Comment by rafaelroque** [comment]
I had solved exactly this way,but thanks anyway!

**Comment by ionas** [comment]
This helped me a lot. Strange enough the inputs value attribute was not getting set even when I tried to query it via a live collection (getElementByClassname()[0].value). Where do I find the documentation on $(this).typeahead("val", "");?
