### ISSUE TITLE
Delay option to facilitate inspecting dropdown markup

### ISSUE THREAD

**Issue by moniuch** [twitter/typeahead.js#1086]
Could we have a param (in milliseconds) to delay the moment of hiding the dropdown? This would facilitate styling esp when custom templates are being tested.
Currently the dropdown closes immediately a click occurs outside, including those within inspector.

**Comment by jhuesos** [comment]
What we do is to use this simple trick:

```
$('input.tt-input').val('query').trigger('input')
```
Being: input.tt-input the input field with typeahead and query the value you want to search by.

Doing it from the console, you can now easily inspect the DOM and play with the styles. Typeahead dropdown wont close even if you click anywhere in the app.

One gotcha: in order for this trick to work, you must run that statement with a different value every time. If the input contains: 'value' and you set val('value'), running that will show nothing. 

You can give it a try here:

http://run.plnkr.co/1K5YGm2CpjmaB8s9/

Open console and run that command. This is good enough for us and we dont really need anything else.

**Comment by moniuch** [comment]
Hi Jaime,

Thanks for a great tip! It deserves to be included on the web page.

Artur

**Comment by jhuesos** [comment]
Thanks. BTW I just noticed that the link to the plunkr was broken. I just fixed it
