### ISSUE TITLE
Options for stopPropogation in _onEnterKeyed?

### ISSUE THREAD

**Issue by chezbo425** [twitter/typeahead.js#1095]
Seems a lot of people are having trouble getting their form to submit on pressing enter. I'm actually having the opposite issue. When suggestions are being offered I need enter to autocomplete/select an item, but NOT submit the form. When selection completes, the next enter press should propogate and submit the form.

In our case we have a form with several elements with typeahead so submitting the form is not desirable  in most cases because there are still other things to fill out. I tried using onKeyDown and tracking the open/close state of typeahead, but typeahead is always closed before my onKeyDown event handler fires. As such I can't tell when an Enter press event resulted in typeahead selection that should NOT submit the form or if it was a general enter event that should submit the form.

My best idea so far is to set a flag in typeahead:selected and queue the clearing of that flag w/ set timeout. That'll cause the flag to be set for the remainder of the current event processing, but be cleared as soon as that completes.

Open to ideas!

**Comment by jharding** [comment]
The only time typeahead.js intercepts an enter key press is when suggestions are being shown and the end-user has keyed down to one of them. In this scenario when the user hits enter, it selects the suggestion and stops propagation of the event.

**Comment by Intrepidd** [comment]
Are you sure you're stopping propagation ?

Here's the related code : 

``` javascript
_onEnterKeyed: function onEnterKeyed(type, $e) {
    var $selectable;
    if ($selectable = this.menu.getActiveSelectable()) {
        this.select($selectable) && $e.preventDefault();
    }
},
```

Shouldn't it be something like : 

``` javascript
_onEnterKeyed: function onEnterKeyed(type, $e) {
    var $selectable;
    if ($selectable = this.menu.getActiveSelectable()) {
        if (this.select($selectable)) {
          $e.preventDefault();
          $e.stopPropagation();
        }
    }
},
```

I tried applying this patch and it solved the problem.

Do you want a pull request ?

**Comment by jlbooker** [comment]
@Intrepidd Your PR is now merged over at corejavascript/typeahead.js#13 :+1:
