### ISSUE TITLE
Manually append / prepend a  result to list

### ISSUE THREAD

**Issue by canfiax** [twitter/typeahead.js#1097]
I look for some way, I can programmatically append a result to the list. How can I do this?

I do some regex on the input query (when it has changed), and then wish to append a result, if it matches a set of regexes..

Thanks in advance

**Comment by jhuesos** [comment]
You can do that quite easily. The beauty about typeahead and the thing I really like is that it is very simple and extremely flexible and powerful. In this plunkr, from the ones in the demo page, I have created an example of what you need: modifying the results on demand. Also I show how to add custom data sets where you can add anything you want:

http://run.plnkr.co/1K5YGm2CpjmaB8s9/

**Comment by canfiax** [comment]
Thanks for reply! However, your attached fiddle 404s. I'd like to see how you achieved it.

**Comment by jhuesos** [comment]
Ups sorry for that :) I just updated my previous comment with the right link
