### ISSUE TITLE
Add "refresh/update" method (i.e. after Bloodhound.add(datum))

### ISSUE THREAD

**Issue by canfiax** [twitter/typeahead.js#1099]
I have created a small piece of code that scans the input against a regex, and then adds a result to the suggestions.

Like so:

     Typeahead.engine.add(result);

However, the result does not show up, before i press the "backspace" button, or do something else to trigger an "update":

I could be cool if the `.add();` method would manually trigger an update, so the result would show up instantly.

**Comment by jharding** [comment]
You could achieve this by doing something like `$('.typeahead').typeahead('val', '').typeahead('val', oldVal)`. Obviously not ideal, but maybe passable. I'm considering adding something like `$('typeahead').typeahead('refresh')`, but it's not a high priority.
