### ISSUE TITLE
Group by categories

### ISSUE THREAD

**Issue by keithslater** [twitter/typeahead.js#11]
Anyway to group results by categories? It would be nice to show the category name and list the items below it.

**Comment by Vidhya-Dilip** [comment]
In which file should this code be applied? 
<div class="tt-dropdown-menu">
  {{#dataset}}
    <div class="tt-dataset-{{name}}">
      
      <div class="tt-suggestions">
        {{#suggestions}}
          <div class="tt-suggestion">{{{html}}}<div>
        {{/suggestions}}
      </div>
      
  {{/dataset}}
</div>

**Comment by Vidhya-Dilip** [comment]
In which file should this code be added? 
`<div class="tt-dropdown-menu">
  {{#dataset}}
    <div class="tt-dataset-{{name}}">
      
      <div class="tt-suggestions">
        {{#suggestions}}
          <div class="tt-suggestion">{{{html}}}<div>
        {{/suggestions}}
      </div>
      
  {{/dataset}}
</div>`

**Comment by Vidhya-Dilip** [comment]
In which file should this be added?
```
<div class="tt-dropdown-menu">
  {{#dataset}}
    <div class="tt-dataset-{{name}}">
      <!-- HEADER GOES HERE -->
      <div class="tt-suggestions">
        {{#suggestions}}
          <div class="tt-suggestion">{{{html}}}<div>
        {{/suggestions}}
      </div>
      <!-- FOOTER GOES HERE -->
  {{/dataset}}
</div>
```
