### ISSUE TITLE
Typeahead.js regex match / include {query} in search sentence?

### ISSUE THREAD

**Issue by canfiax** [twitter/typeahead.js#1100]
I have so far implemented this feature in typehead.js (very buggy and hacky): https://www.youtube.com/watch?v=EKJ8Lc1c0WM.

But I wondered, would there be a way to include the query string as a dynamic parameter in the datasets?

Using my above video as example, the `queryToken` could contain regex like so: `/plugins (.+)/g` which means it would show if the query would return true on the regex parameter.

**Comment by canfiax** [comment]
Actually asked before: https://github.com/twitter/typeahead.js/issues/210 

Maybe integrate some streamlined process of this? It seems like a common treat.

**Comment by jharding** [comment]
At this point I don't think this will happen. It'd be an involved change and I think the work outweighs the value added.
