### ISSUE TITLE
typeahead:responseSent and typeahead:responseReceived events?

### ISSUE THREAD

**Issue by glodov** [twitter/typeahead.js#1103]
Is this possible to add such events in typeahead plugin?
The simple reason is showing loading icon when responseSent and hide when responseReceived.
And more complicated to work with data received by typeahead request when received.

**Comment by solygen** [comment]
+1

**Comment by ralf57** [comment]
+1

**Comment by glodov** [comment]
Hello, guys!

I figured out this. It works with bloodhound. There are ajax events beforeSend() and complete().

            var engine = new Bloodhound({
                limit: 50,
                datumTokenizer: function (d) {
                    return Bloodhound.tokenizers.whitespace(d.name);
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url : "/search?q=%QUERY",
                    filter: function(parsedResponse){
                        return parsedResponse;
                    },
                    ajax: {
                        beforeSend: function(){
                            // event before send, so show loading icon here
                        },
                        complete: function(){
                            // event on complete request, so remove loading icon here
                        }
                    }
                }
            });

**Comment by jharding** [comment]
Check out the [`async*` events added in v0.11](https://github.com/twitter/typeahead.js/blob/integration-0.11.0/doc/jquery_typeahead.md#custom-events).
