### ISSUE TITLE
Disabling input update when scrolling through suggestions

### ISSUE THREAD

**Issue by yosefw** [twitter/typeahead.js#1105]
I'm using typeahead.js as more of a quick navigation tool rather than a search engine (think spotlight on Mac OS X). Therefore, I don't want the input to update when the user scrolls through suggestions. I want the user's original query to stay there and not change (only clear when appropriate).

Is there a way to do that?

**Comment by jhuesos** [comment]
Duplicated:

https://github.com/twitter/typeahead.js/issues/884#issuecomment-52456111

**Comment by jhuesos** [comment]
Can you close this one and continue in the other one. Thanks
