### ISSUE TITLE
Handle "maximum size reached" error

### ISSUE THREAD

**Issue by Koc** [twitter/typeahead.js#1110]
We are using typeahead with prefetch. And got uncatched exception

```
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached

return ls.setItem(this._prefix(key), encode(val));
```

Typeahead should handle this kind of exceptions

**Comment by Rukkuror** [comment]
Hi,
I am using typeahead prefetch like below.

prefetch:
      ttl: 250000
      url: '/employees.json'
      filter: (employees) ->
        $.map employees, (employee) ->
          { name: employee }
    limit: 25

Here employees.json is huge in size. I am getting the storage error

NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached

Someone please help ASAP to resolve this.

Thanks in advance.
