### ISSUE TITLE
Bloodhound - Exclusion of Selected Results

### ISSUE THREAD

**Issue by Timethor** [twitter/typeahead.js#1111]
We use Typeahead/Bloodhound with React at my job for getting database results and selecting them in an intuitive fashion. I recently ran into an undesired use case where once you have selected a result, it still pops up in the results. I found a way to get it working using a mix of the remote filter and a fancy dupDetector but I ended up having to disable prefetch because results from prefetch appear to be added to the list of results AFTER the filter and dupDetector pieces have run -- which makes sense.

Looks like this when prefetch is on:
![screen shot 2015-01-29 at 11 56 19 am](https://cloud.githubusercontent.com/assets/1635159/5963984/e7b94c7c-a7ad-11e4-9d41-8283338f7399.png)

So really I'm requesting one of the following features or something similar:
- An additional function on options similar to dupDetector that when it returns true a result is excluded from the final list of results to show the user (Local, Remote, and Prefetch results)
- An exposed method on the engine to clear only certain datums from prefetch -- not as desirable

I hope that some addition/change is in the scope of the project as I would prefer not to have to keep prefetch disabled or hack something in -- our queries are fast but having to disable cache in order to truly exclude results seems silly to me. Maybe I'm missing something?

I'm more than happy to do the work and create a PR. I just wanted check here first before I started anything.

Cheers!

**Comment by leesalminen** [comment]
I'm using Typeahead.js in a similar fashion and would love this feature!

**Comment by jharding** [comment]
If I understand the situation correctly, you could achieve this by wrapping a bloodhound instance:

```js
function theWrapper(q, sync) {
  var results = bloodhound.search(q, function(results) {
    // remove selected results
    sync(resultsWithExclusions);
  });
}
```

**Comment by DEKHTIARJonathan** [comment]
@jharding hello mate, I'm struggling with the same problem, do you have a working jsfiddle or something ... I can't manage to make it work.

Thanks a lot mate !

**Comment by Timethor** [comment]
I suppose I should've posted my solution here. Might not be the most elegant but it works. Hope this helps anyone trying to solve the same problem :)

``` js
/**
 * Initialize the bloodhound object for use with typeahead
 *
 * @param {object} props - an object containing the keys `bloodhound` and `typeahead`, each one's value is an object
 * representation of the configs per the documentation located at https://github.com/twitter/typeahead.js/tree/master/doc
 * plus some extras...
 * @return {object} The initialized bloodhound object
 */
initBloodhound(props) {
    this.bloodhound_options = _.cloneDeep(props.bloodhound);

    // initializes Bloodhound, the suggestion engine for typeahead.js
    var items = new Bloodhound(this.bloodhound_options);

    // Save bloodhound's current search function
    items.__search = items.search;
    // Override bloodhound search function with something that supports filtering selected items
    items.search = function (query, sync, async) {
        var filter = props.bloodhound.filter || _.identity;
        var search_local = function () {
            // Pass filtered results to sync & async
            items.__search(
                    query,
                    function (results) {
                        sync && sync(filter(results));
                    },
                    function (results) {
                        async && async(filter(results));
                    }
            );
        }.bind(this);
        // ...
        search_local();
    }.bind(this);

    return items;
}
```

and here is an example of one of our bloodhound.filter functions:

``` js
props.bloodhound.filter = function(list) {
    // We are removing all things from `list` that are NOT yet selected and returning them
    return _.remove(list, function (list_item) {
        // this.__serializeValue() returns an array of selected values
        return !_.findKey(this.__serializeValue(), function(existing) {
            // our item objects in this case look like {'value': ..., 'label': ...}
            return _.get(list_item, 'value') === existing.value;
        });
    }.bind(this));
}.bind(this);
```

All functions that look like `_.something` here are Lodash functions.
