### ISSUE TITLE
Can't style the dropdown

### ISSUE THREAD

**Issue by Jakobud** [twitter/typeahead.js#1112]
Why did you add so many inline css values to the `tt-dropdown-menu` element? I can't adjust the width and stuff of the dropdown without using `!important` (which is never a good idea to use).

Can you not adjust CSS via options?

Speaking of which, where is the documentation for the options? I don't even know what "hint" does.

**Comment by Jakobud** [comment]
Okay so after some further work with the script, you CAN do some styling, but you still have to use `!important` for a lot of your rules because of all the inline CSS.

I would highly suggest simply moving all CSS to an external stylesheet instead of doing everything inline. Taking a quick glance at the source, I don't see any styles being calculated dynamically, so I'm not sure why you would need to put them inline anyways. The two main advantages of using external CSS for this is 1. It's easier for users to customize the styles. 2. It keeps users from having to resort to using `!important`.

**Comment by sospedra** [comment]
+1 neither I understand why so many inlines, also they're totally unnecessary and could perfectly be on the .css files
