### ISSUE TITLE
Prevent closing autocomplete dropdown on input blur

### ISSUE THREAD

**Issue by chrisbjr** [twitter/typeahead.js#1113]
Hi was wondering if I could get some help with a feature request.

We want to keep the autocomplete dropdown open even when the input loses focus. It should only close when an item is selected.

I found an event in [input.js](https://github.com/twitter/typeahead.js/blob/master/src/typeahead/input.js) `blur.tt` which you can extend but I'm not sure how to prevent the dropdown from closing inside this event.

Any help would surely be appreciated.

Thanks

Chris

**Comment by chrisbjr** [comment]
Modified the onBlur method in typeahead.js and implemented my own close event. Fixed it.

**Comment by zedtux** [comment]
@chrisbjr do you have a repository with your code?

**Comment by chrisbjr** [comment]
Hi @zedtux sorry, I can't remember which project I was working on with this one.

**Comment by samuelcolvin** [comment]
Had the same problem and the (very easy) solution doesn't seem to be documented anywhere

```javascript
$(document).on('typeahead:beforeclose', function(event, data) {
  event.preventDefault()
})
```
