### ISSUE TITLE
Efficient AutoSuggest with throttling with remote data

### ISSUE THREAD

**Issue by X17** [twitter/typeahead.js#1114]
Typeahead hits the server every time you type a key and does not wait for you to essentially finish typing. What's the best way to solve this? Kill previous AJAX request? Adding some type of delay to check if the person has stopped typing say within range say 400ms.

Some kind of throttling which can handle the requests and abort the previous request when pressed key within throttle range.

Throttle.delay = 400 // delay in miliseconds

While working with remote data, it pings the server on back press.

**Comment by addremove** [comment]
Does this help ?

https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote

`rateLimitBy – The method used to rate-limit network requests. Can be either debounce or throttle. Defaults to debounce`

**Comment by X17** [comment]
@addremove 

Thanks a lot. I went through the document it helped.

Is there any way to prevent network calls when user press back press to remove the typed character ?

**Comment by addremove** [comment]
[Difference between Debounce and Throttle](http://drupalmotion.com/article/debounce-and-throttle-visual-explanation)

> Is there any way to prevent network calls when user press back ...

Haven't tried, but in the [`replace`](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote) function you could override what the user types by detecting <kbd>backspace</kbd>. However keep in mind that if the user types `Amazo` quickly and then erases `o`, he could either mean `Amazon` or `Amazing`. If you don't send the typeahead request, you won't see the latter suggestion.

**Comment by X17** [comment]
@addremove this one is little irrelevant, but been playing with typeahead. Does bloodhound takes white spaces into account while working with tokens. 

Like "token": ['typeahead.js', 'typeahead', 'auto complete', 'java script'];

while searching for keywords

> "java" it gives the result token[3] but when i include whitespace "java script" it looses meaning.

is there any workaround to include whitespaces with tokens.

**Comment by worthy7** [comment]
Going back to the original question... I still think that previous requests should be cancel-able, since the data they retrieve won't be used at all anyway.... is it not possible to do some kind of .abort?

**Comment by simplenotezy** [comment]
@worthy7 did you ever find a solution? 😊

**Comment by worthy7** [comment]
@simplenotezy nope
