### ISSUE TITLE
Bloodhound binding (this) cause error when used with module bundler like webpack

### ISSUE THREAD

**Issue by singggum3b** [twitter/typeahead.js#1120]
https://github.com/twitter/typeahead.js/blob/5f198b87d1af845da502ea9df93a5e84801ce742/dist/bloodhound.js#L582-726

the (this = root = window) scope wont be consistent when using with a module loader like webpack

Why passing root = this instead of root = window ?

**Comment by jharding** [comment]
I believe this should now be fixed, let me know if it isn't and I'll get right on it.

**Comment by Zagitta** [comment]
It's not fixed in 0.11.1, in case anyone else runs into this issue.

**Comment by freddyrangel** [comment]
I believe this is still an issue

**Comment by write2art** [comment]
Still not fixed.

**Comment by diegocouto** [comment]
I'm also having problems with it. Maybe this issue should be kept open 'til it gets really fixed.

**Comment by Growiel** [comment]
Confirming that it's indeed NOT fixed.
