### ISSUE TITLE
Ajax loading - UI indicator

### ISSUE THREAD

**Issue by shanplourde** [twitter/typeahead.js#1121]
Hello, the current typeahead.js doesn't seem to support a loading indicator, such as a spinning loading icon in the search box, etc. I have seen a few requests floating around related to this, but thinking about it more, I'm thinking that maybe it would be nice to create a new template called "loading" instead. Similar to the "suggestion, "header", "footer", and "empty" templating support. 

I'm not sure which of the two would result in a more usable approach in general, and wanted to get the community's thoughts before I implement either or in my current project. I like the idea of using the suggestions area for state related feedback, rather than the user's input area. What do you think? 

Thanks
Shan

**Comment by danimoe** [comment]
That would be great.

**Comment by perajovic** [comment]
+1

**Comment by JasperTey** [comment]
This was addressed in #166; hopefully we see it released soon.

**Comment by jharding** [comment]
This is now possible. Check out the [landing page](http://twitter.github.io/typeahead.js/) for an example. The js for that example is available [here](https://github.com/twitter/typeahead.js/blob/gh-pages/js/main.js).
