### ISSUE TITLE
Get the value regardless is or not in autocomplete list

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [twitter/typeahead.js#1126]
I've been checking the documentation and tells nothing about get the value. The only solution brings values only if they are in the autocomplete list.

http://stackoverflow.com/a/23001605

I've tried this https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#jquerytypeaheadval
but none of them brings me the value.

**Comment by jharding** [comment]
You just want the value that was typed into the input element? `$('.selectorGoesHere').val()` should do the trick. If I'm misunderstanding something, let me know and I can reopen the issue.
