### ISSUE TITLE
Bloodhound Typeahead only returning first 5 records from DB

### ISSUE THREAD

**Issue by mtanczos** [twitter/typeahead.js#1130]
I finally got this semi working, the only issue it only returns the 1st 5 records from my db.
Here is my javascript:
<script type="text/javascript">
                            var typeHeadEngine = new Bloodhound({
                                limit: 10,
                                remote: {
                                    url: 'Services/WebServiceAjax.asmx/GetProjID',
                                    ajax: {
                                        type: "POST",
                                        data: '{}',
                                        cache: false,
                                        contentType: "application/json; charset=utf-8",
                                        dataType: "text"
                                    },
                                    filter: function (data) {
                                        var obj = JSON.parse(data);
                                        console.log(obj.d);
                                        return obj.d;
                                    }
                                },
                                limit:25,
                                datumTokenizer: function (d) {
                                    return Bloodhound.tokenizers.whitespace(value);
                                },
                                queryTokenizer: Bloodhound.tokenizers.whitespace
                            });
                            // kicks off the loading/processing of `local` and `prefetch`
                            typeHeadEngine.initialize();
                            // passing in `null` for the `options` arguments will result in the default
                            // options being used
                            $('#scrollable-dropdown-menu .typeahead').typeahead(null, {
                                name: 'Name',
                                displayKey: 'Value',
                                //highlight: true,
                                //hint: true,
                                // `ttAdapter` wraps the suggestion engine in an adapter that
                                // is compatible with the typeahead jQuery plugin
                                source: typeHeadEngine.ttAdapter()
                            });

Here is the ASP.NET CODE
   <WebMethod()> _
    Public Function GetProjID() As List(Of ListItem)

        Dim query As String = "SELECT DISTINCT PROJ_DESCR FROM INL_Reporting.labor.Projects WHERE INT_LAB_RATE_TYPE <> 'NONE' AND ACTIVE = 1 ORDER BY PROJ_DESCR"
        Dim constr As String = ConfigurationManager.ConnectionStrings("Connection_String").ConnectionString
        Dim fruits As New List(Of ListItem)()
        Using con As New SqlConnection(constr)
            Using cmd As New SqlCommand(query)
                Using sda As New SqlDataAdapter()
                    cmd.Connection = con
                    sda.SelectCommand = cmd
                    Using dt As New DataTable()
                        con.Open()
                        Using sdr As SqlDataReader = cmd.ExecuteReader()
                            While sdr.Read()
                                fruits.Add(New ListItem() With { _
                             .Text = sdr("PROJ_DESCR").ToString(), _
                             .Value = sdr("PROJ_DESCR").ToString() _
                                })
                            End While
                        End Using
                    End Using
                End Using
            End Using
        End Using
        Return fruits
    End Function

Any ideas to what I am doing wrong?

Thanks

**Comment by hello-code** [comment]
The 5 is default value:
```javascript
 this.limit = o.limit || 5;

```
Maybe this:
```javascript
// remote
    var employees = new Bloodhound({
        datumTokenizer: function (d) { return Bloodhound.tokenizers.whitespace(d.name); },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        limit:Number.MAX_VALUE, // I do not know how to get total number ...
        remote: {
            url: '/Autocomplete/GetEmployeeName?name=%QUERY',
            filter: function (response) {
                return $.map(response.results,function (employee) {
                      return { name: employee.name }
                });
            }
        }
    });

```

**Comment by mtanczos** [comment]
Morning Thank you for reply, unfortunately the solution you provided didn't
on-account of I have no clue what I am doing...lol

I am using asp.net vb WebMethod to pull live data from db below is my code:

Public Function GetProjID() As List(Of ListItem)

Dim query As String = "SELECT DISTINCT PROJ_DESCR, PROJ_ID FROM
INL_Reporting.labor.Projects WHERE INT_LAB_RATE_TYPE <> 'NONE' AND ACTIVE =
1 ORDER BY PROJ_DESCR"
        Dim constr As String =
ConfigurationManager.ConnectionStrings("Connection_String").ConnectionString
        Dim fruits As New List(Of ListItem)()
        Using con As New SqlConnection(constr)
            Using cmd As New SqlCommand(query)
                Using sda As New SqlDataAdapter()
                    cmd.Connection = con
                    sda.SelectCommand = cmd
                    Using dt As New DataTable()
                        con.Open()
                        Using sdr As SqlDataReader = cmd.ExecuteReader()
                            While sdr.Read()
                                fruits.Add(New ListItem() With { _
                             .Text = sdr("PROJ_DESCR").ToString(), _
                             .Value = sdr("PROJ_ID").ToString() _
                                })
                            End While
                        End Using
                    End Using
                End Using
            End Using
        End Using
        Return fruits
    End Function

this is my text box:

                        <div class="label-and-input-container">
                            <asp:Label ID="lbl_search_proj_typeahead"
runat="server" Text="Project Name:"></asp:Label>
                            <div  id="JsonTypeaHead" style="width: 180px;
display: inline-block;">
                                 <asp:TextBox id="mytextbox" runat="server"
placeholder="Search Proj Desc" CssClass="form-control typeahead"
                              AutoComplete="off" data-provide="typeahead" />
                            </div>
                        </div>

Then this is my ajax, bloodhound code:
 <script type="text/javascript">
                            var typeHeadEngine = new Bloodhound({
                                datumTokenizer: function (d) { return
Bloodhound.tokenizers.whitespace(d.name); },
                                queryTokenizer:
Bloodhound.tokenizers.whitespace,
                                remote: {
                                    url:
'Services/WebServiceAjax.asmx/GetProjID',
                                    ajax: {
                                        type: "POST",
                                        data: "{}",
                                        cache: false,
                                        contentType: "application/json;
charset=utf-8",
                                        dataType: "text",
                                    },
                                    filter: function (data) {
                                        var obj = JSON.parse(data);
                                       //alert(JSON.stringify(obj.d));
                                        console.log(obj.d);
                                        return obj.d;
                                    }
                                },
                                limit: 160,
                            });
                            // kicks off the loading/processing of `local`
and `prefetch`
                            typeHeadEngine.initialize();
                            // passing in `null` for the `options`
arguments will result in the default
                            // options being used
                            $('#JsonTypeaHead .typeahead').typeahead(null, {
                                name: 'Text',
                                displayKey: 'Text',
                                highlight: true,
                                hint: true,
                                // `ttAdapter` wraps the suggestion engine
in an adapter that
                                // is compatible with the typeahead jQuery
plugin
                                source: typeHeadEngine.ttAdapter()
                            });


I am referencing both Typeahead and Bloodhound js with the latest version
from github.
So my drop down is working however the typeahead suggestion doesn't seem to
be working when I type it only recolonize the first record in the drop down
and not the rest. Any help would be greatly appreciated.

Thanks



Mate' Tanczos
Jn 14:6

**Comment by hello-code** [comment]
Sorry for late.I'm using ASP.NET MVC C#.
Maybe this:
```VB
  url:'Services/WebServiceAjax.asmx/GetProjID',
```
My url is:  
```C#
url: '/Autocomplete/GetEmployeeName?name=%QUERY',
```
```C#
Public ActionResult GetEmployeeName ( string name )
{
  ...
  return Json(...)
}

**Comment by mtanczos** [comment]
No worries at all thank for replying back to me, not many people would take
the time to do that.
I still can't get it tot work, is there anyway you could send me your
codes, html, JavaScript, and behind code. You can take out all sensitive
connections to dbs I just need to see how yours is put together .

Thank you again for all your help...



Mate' Tanczos
Jn 14:6

**Comment by hello-code** [comment]
You are welcome,my pleasure.
Html:
```html
 <div class="form-group">
    <label>Employee Name</label>
    <input type="text" id="employeeName" class="form-control" />
 </div>
```
Javascript:
```javascritp
$(document).ready(function () {
    // remote
    var employees = new Bloodhound({
        datumTokenizer: function (d) { return Bloodhound.tokenizers.whitespace(d.name); },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        //limit: 5,
        limit: Number.MAX_VALUE,// Set the limit as high as possible.
        remote: {
            url: '/Autocomplete/GetEmployeeName?name=%QUERY',
            filter: function (response) {
                return $.map(response.results, function (employee) {
                    return {
                        name: employee.name
                    }
                });
            }
        }
    });

    employees.initialize();

    $('#employeeName').typeahead(
    {
        hint: false,
        highlight: true,
        minLength: 1
    }
    ,
    {
        name: 'employees',// Bloodhound instance
        displayKey: 'name',
        source: employees.ttAdapter(),
        templates: {
            empty: [
                '<div class="empty-message">',
                'Sorry no data !',
                '</div>'
                ].join('\n')
        }
    })
    .css('vertical-align', 'middle');// label position
});
```
behind code:
```C#
public JsonResult GetEmployeeName(string name)
{
    using (var db=new EntityContext())
    {
        var n=db.Employee
            .Where(w => w.EmployeeName.Contains(name))
            .ToList()
            .Select(w => new { name = w.EmployeeName })
            .Distinct();
        return Json(new { success = true, results = n },JsonRequestBehavior.AllowGet);
    }
}
```
Hope help you.

**Comment by mtanczos** [comment]
Wow this is great!, hope I can make this work in VB now...
Thank you so much!!!



Mate' Tanczos
Jn 14:6

**Comment by hello-code** [comment]
Your are welcome.
BTW: I'm using select2 now.

**Comment by mtanczos** [comment]
Hi Again,

I am still stuck. I am able the pass parameters to the my webmethod and the
query works and when I put a break point at Return ProjectDescr its working
fine. But nothing is passed back to bloodhound. Can you please help me with
this.
Here are my codes:

*WebMethod:*

   <WebMethod()> _
    Public Function GetProjID(name As String) As List(Of ListItem)
        ' Public Function GetProjID() As List(Of ListItem)

        Dim myquery As String = "SELECT DISTINCT PROJ_DESCR FROM Projects
WHERE PROJ_DESCR like  '" + name + "%'  AND INT_LAB_RATE_TYPE <> 'NONE' AND
ACTIVE = 1 ORDER BY PROJ_DESCR"
        'Dim myquery As String = "SELECT DISTINCT PROJ_DESCR FROM
INL_Reporting.labor.Projects WHERE  INT_LAB_RATE_TYPE <> 'NONE' AND ACTIVE
= 1 ORDER BY PROJ_DESCR"
        Dim constr As String =
ConfigurationManager.ConnectionStrings("INL_Connection_String").ConnectionString
        Dim ProjectDescr As New List(Of ListItem)()
        Using con As New SqlConnection(constr)
            Using cmd As New SqlCommand(myquery)
                Using sda As New SqlDataAdapter()
                    cmd.Connection = con
                    sda.SelectCommand = cmd
                    Using dt As New DataTable()
                        con.Open()
                        Using sdr As SqlDataReader = cmd.ExecuteReader()
                            While sdr.Read()
                                ProjectDescr.Add(New ListItem() With { _
                             .Text = sdr("PROJ_DESCR").ToString()
                                })
                            End While
                        End Using
                    End Using
                End Using
            End Using
        End Using
        Return ProjectDescr

Bloodhound:
                        <script type="text/javascript">

                            var NewProjects = new Bloodhound({
                                datumTokenizer:
Bloodhound.tokenizers.obj.whitespace('Text'),
                                queryTokenizer:
Bloodhound.tokenizers.whitespace,
                                limit: 10,
                                remote: {
                                    url:
'Services/WebServiceAjax.asmx/GetProjID?name=%QUERY',
                                    filter: function (NewProjects) {
                                        var obj = JSON.parse(NewProjects);
                                        console.log(obj.d);
                                       return obj.d;
                                    }
                                },
                            });
                            NewProjects.initialize();
                            $('#users .typeahead').typeahead({
                                hint: true,
                                highlight: true,
                                minLength: 1
                            }, {
                                name: 'PROJ_DESCR',
                                displayKey: 'Text',
                                templates: {
                                    empty: '<div class="empty-message">No
matches.</div>'
                                },
                                source: NewProjects.ttAdapter()
                            });
                        </script>




I have no clue why nothing comes back.

Thanks



Mate' Tanczos
Jn 14:6

**Comment by hello-code** [comment]
Maybe your js will...:
```javascript
$(document).ready(function () {
    // remote
    var employees = new Bloodhound({
        datumTokenizer: function (d) { return Bloodhound.tokenizers.whitespace(d.name); },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        //limit: 5,
        limit: Number.MAX_VALUE,// Set the limit as high as possible.
        remote: {
            url: '/Autocomplete/GetEmployeeName?name=%QUERY',
            filter: function (response) {
                return $.map(response.results, function (employee) {
                    return {
                        name: employee.name
                    }
                });
            }
        }
    });

    employees.initialize();

    $('#employeeName').typeahead(
    {
        hint: false,
        highlight: true,
        minLength: 1
    }
    ,
    {
        name: 'employees',// Bloodhound instance
        displayKey: 'name',
        source: employees.ttAdapter(),
        templates: {
            empty: [
                '<div class="empty-message">',
                'Sorry no data !',
                '</div>'
                ].join('\n')
        }
    })
    .css('vertical-align', 'middle');// label position
});

```
Your js:
```javascript
 var NewProjects = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Text'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    limit: 10,
    remote: {
        url: 'Services/WebServiceAjax.asmx/GetProjID?name=%QUERY',
        filter: function (NewProjects) {
            var obj = JSON.parse(NewProjects);
            console.log(obj.d);
            return obj.d;
        }
    },
});
NewProjects.initialize();
$('#users .typeahead').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
},
 { name: 'PROJ_DESCR',
    displayKey: 'Text',
    templates: { empty: '<div class="empty-message">No matches.</div>' },
    source: NewProjects.ttAdapter()
   }
);

```

**Comment by haile819** [comment]
@hello-code reading through this thread from 2 years ago..I notice that you are very patient and helpful.

**Comment by hello-code** [comment]
@haile819  Thanks! To help others is the source of happiness.

**Comment by CharlesKitonga** [comment]
Hello, i followed your explanation and its really great, though am having trouble with my autocomplete, when i type in it gives me the er:sorry no data, though its fetching from the database. Please help,
Here is my code:
`<link href="<?php echo base_url() ?>assets/css/bootstrap-timepicker.min.css" rel="stylesheet">
<link href="<?php echo base_url() ?>assets/css/datepicker3.css" rel="stylesheet">
<link href="<?php echo base_url() ?>assets/tagsinput/bootstrap-tagsinput.css" rel="stylesheet">
<link href="<?php echo base_url() ?>assets\css\jquery.auto-complete.css" rel="stylesheet">

<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/bootstrap-timepicker.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/bootstrap-datepicker.js"></script>

<script type="text/javascript" src="<?php echo base_url() ?>assets/js/typeahead.js/bloodhound.min.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/typeahead.js/typeahead.bundle.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/typeahead.js/typeahead.jquery.min.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/jquery.auto-complete.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/js/jquery.auto-complete.min.js"></script>


<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
<script type="text/javascript" src="<?php echo base_url() ?>assets/tagsinput/bootstrap-tagsinput.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-maxlength/1.7.0/bootstrap-maxlength.min.js"></script>


<button class="btn btn-primary btn-xs pull-right" data-toggle="modal" data-target="#myModal">
    Send Message
</button>
<style type="text/css">
    .modal-backdrop{z-index: 1200;}
    .modal{z-index: 1201;}
    .tt-dropdown-menu{z-index: 1203; border: solid 1px #CCC; margin-right: 0; margin-left: 0; background-color: #fff; border-color: #ddd; border-width: 1px; border-radius: 4px 4px 0 0; border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; -webkit-box-shadow: none; box-shadow: none;}
    .tt-suggestions{}
</style>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index: 9999;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Send Message</h4>
            </div>
            <div class="modal-body">
                <form name="SendSMSForm" id="SendSMSForm" action="<?php echo site_url();?>/sms/sms_form"  class="form-horizontal" role="form" method="post">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Sender</label>
                        <div class="col-sm-10">
                            <p class="form-control-static"><label class="label label-primary">Inclusion</label></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="receiver" class="col-sm-2 control-label">To</label>
                        <div class="col-sm-10">
                            <input class="form-control" id="receiver" type="text" placeholder="" name="receiver" >
                            <p class="help-block">
                                <small>
                                    Enter name of person/group in address-book E.g John, Family, Workmates
                                </small>
                            </p>
                        </div>
                        <label for="message" class="col-sm-2 control-label">Message</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="body" rows="3"  id="body"></textarea>
                            <p>
                                <span id="remaining">160 characters remaining</span>
                                <span id="messages" name="">1 page(s)</span>
                            </p>
                        </div>
                    </div>

                    <a data-toggle="collapse" data-parent="#accordion" href="#SendSMSOptions">
                        <span class="glyphicon glyphicon-plus"></span> Options
                    </a>
                    <div id="SendSMSOptions" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="Schedule" class="col-sm-2 control-label">Schedule Send</label>
                                <div class="col-sm-10">
                                    <br />
                                    <div class="input-group date">
                                        <input data-provide="datepicker" name="datepicker" type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                    </div>
                                    <div class="input-group bootstrap-timepicker">
                                        <input id="timepicker" data-template="modal"  name="timepicker" type="text" class="form-control">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="SendSMS">Send Now</button>
            </div>
        </div>
    </div>
</div>

<script>
    //we are one
    $(document).ready(function() {
        $('.collapse').collapse();
        $('#timepicker').timepicker({showMeridian: false, minuteStep: 15, defaultTime: 'current'});

        $('.input-group.date').datepicker({
            format: 'mm/dd/yyyy',
            startDate: '-3d',
            autoclose: true,
            todayHighlight: true
        });
        $(document).ready(function(){
            var $remaining = $('#remaining'),
                $messages = $remaining.next();

            $('#body').keyup(function(){
                var chars = this.value.length,
                    messages = Math.ceil(chars / 160),
                    remaining = messages * 160 - (chars % (messages * 160) || messages * 160);
 
                $remaining.text(remaining + ' characters remaining');
                $messages.text(messages + ' page(s)');

            });
        }); 
        $(document).ready(function () {
            // remote
            var contacts = new Bloodhound({
                datumTokenizer: function (d) { return Bloodhound.tokenizers.whitespace(d.name); },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                //limit: 5,
                limit: Number.MAX_VALUE,// Set the limit as high as possible.
                remote: {
                    url:"<?php echo base_url('tags/get_tags')?>",
                    filter: function (response) {
                        return $.map(response.results, function (contacts) {
                            return {
                                name: contacts.name
                            }
                        });                    }
                }
            });

            contacts.initialize();

            $('#receiver').typeahead(
            {
                hint: false,
                highlight: true,
                minLength: 2
            }
            ,
            {
                name: 'contacts',// Bloodhound instance
                displayKey: 'name',
                source: contacts.ttAdapter(),
                templates: {
                    empty: [
                        '<div class="empty-message">',
                        'Sorry no data !',
                        '</div>'
                        ].join('\n')
                }
            })
            .css('vertical-align', 'middle');// label position
        });
        $(document).ready(function() {
           $("#SendSMS").click(function(event) {
                 event.preventDefault();
                    console.log($('#SendSMSForm').serializeArray())
                        jQuery.ajax({
                                type: "POST",
                                url: "<?php echo base_url('sms/sms_form') ?>",
                                dataType: 'html',
                                data:  $('#SendSMSForm').serializeArray(),
                                success: function(data){
                                       alert(data);
                                      }
                          });
                            return false;
                    });
        });
           
          
});
</script>

`
