### ISSUE TITLE
Error when typing a parenthesis "(" or ")" - 

### ISSUE THREAD

**Issue by Hakadel** [twitter/typeahead.js#1132]
Hello,

When I type "(" or ")" on the input, I have a JS error : 

    Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group

All characters are good, except parenthesis.

I have use the "The Basics" example, here : https://gist.githubusercontent.com/jharding/9458744/raw/the-basics.js

Thanks

**Comment by jharding** [comment]
Dumb bug, I'll get it fixed for v0.11.1. Thanks for the report!

**Comment by jharding** [comment]
Similar to #1026, I'm going to use that issue to track this bug.
