### ISSUE TITLE
return undefined value in auto suggest

### ISSUE THREAD

**Issue by doitajin** [twitter/typeahead.js#1134]
var trainno = 123;

var trainnos = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: 'ajaxcall.php?train_auto=TrainNo&trainno=' + trainno
});
 
trainnos.initialize();
 
$('.typeahead').typeahead(null, {
  name: 'trainnumber',
  displayKey: 'value',
  source: trainnos.ttAdapter()
});

this code return undefined in auto suggest

Return from php

["12303","12304","12307","12308","12311","12312","12315","12316","12317","12318","12319","12320","12321","12322","12323","12324","12325","12326","12327","12328","12329","12330","12331","12332","12333","12334","12335","12336","12337","12338","12339","12340","12341","12342","12343","12344","12345","12346","12347","12348","12349","12350","12351","12352","12353","12354","12355","12356","12357","12358","12361","12362","12363","12364","12367","12368","12369","12370","12371","12372","12373","12374","12375","12376","12377","12378","12379","12380","12381","12382","12383","12384","12385","12386","12389","12390","12391","12392","12393","12394","12395","12396","12397","12398","12301","12302","12305","12306","12309","12310","12313","12314","12365","12366","12359","12360"]

**Comment by jharding** [comment]
In v0.11, this would fix your problem:

```js
var trainno = 123;

var trainnos = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: 'ajaxcall.php?train_auto=TrainNo&trainno=' + trainno
});

$('.typeahead').typeahead(null, {
  name: 'trainnumber',
  source: trainnos
});
```
