### ISSUE TITLE
typeahead:opened not fired correctly

### ISSUE THREAD

**Issue by MorisatoK** [twitter/typeahead.js#1141]
Contrary to what is documented the `typeahead:opened` event is not fired when the dropdown is actually opened. Instead it fires on focus of the input. At this time the containers for the dropdown aren't event filled yet.

JSFiddle with snippets copied together from the examples page [here](http://jsfiddle.net/5xagb7b0/).

**Comment by CC1337** [comment]
+1, really annoying together with #1102

**Comment by matoni555** [comment]
+1

**Comment by bb** [comment]
+1 from me as well

**Comment by onetwopunch** [comment]
+1

**Comment by izkrivera** [comment]
+1

**Comment by CaptainPsycho** [comment]
+1

**Comment by powange** [comment]
+1

**Comment by JohnnyKB** [comment]
+1 :disappointed:

**Comment by jharding** [comment]
[Custom events were revamped in v0.11](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events) so now open and close mean what they sound like they mean.
