### ISSUE TITLE
Typeahead clearing if hint is empty

### ISSUE THREAD

**Issue by mikeblum** [twitter/typeahead.js#1142]
See the screenshot below:

![selection_007](https://cloud.githubusercontent.com/assets/3905463/6690305/df06e5da-cc8d-11e4-95f1-ff2b2871bf76.png)

the troublesome code is here at line 1095:
```javascript
valIsPrefixOfHint = val !== hint && hint.indexOf(val) === 0;
isValid = val !== "" && valIsPrefixOfHint && !this.hasOverflow();
!isValid && this.clearHint();
```
It seems odd that we call clearHint() on what is already an empty string...

Ultimately the input is cleared. This only happens once and if i wait long enough for the network call to resolve this isn't an issue.

I'm loading in a list of options into Bloodhound and then triggering the appropriate re-init and re-renders but it appears typeahead.js is clearing the input when options haven't loaded yet. What is the prescribed solution when loading in what is essentially local/static data (as far as typeahead.js is concerned) and keeping any user input before the local data arrives? I don't see this situation when I have a remote url.

Thanks!

**Comment by jharding** [comment]
This logic should be much improved in v0.11. I'd suggest giving that version a whirl and seeing if it solves your problem (it's not backwards compatible though so you may need to massage some code into place).
