### ISSUE TITLE
Prevent closing of drop down upon selection or blur

### ISSUE THREAD

**Issue by kneeki** [twitter/typeahead.js#1146]
Hi everyone,

Is it possible to disable the auto-closing feature of the suggestion drop down menu upon selection (click or keyed) or blur (loss of focus to the text box)?

**Comment by jharding** [comment]
It is, but there's not an easy boolean option that controls it. In v0.11, you can pass in the DOM element where results should be rendered, so you have full control over when it is visible and when it is hidden. This is currently undocumented FWIW. Until it's documented, you can poke around the [source code](https://github.com/twitter/typeahead.js/blob/master/src/typeahead/plugin.js#L45) to see how it works and I will try to answer any questions you have.

**Comment by DaveTacker** [comment]
Oh, great! Thanks for your hard work on the project!
