### ISSUE TITLE
Save datasets to DOM

### ISSUE THREAD

**Issue by migig** [twitter/typeahead.js#1150]
For large datasets, the `prefetch` option quickly pollutes the `localStorage`. We need to be able to specify *where to cache the data*, e.g. `none` / `localStorage` / `dom`.

For `dom`, it would save to the typeahead's element (typically an `input`) using:

    $("#theTypeaheadInput").data("theDataSource")

Until/if that option is available, I'm doing this:

- I get the data myself using

    ```javascript
    $.ajax(
      // fetch json data
    )
    .done(function (data, textStatus, jqXHR) {
      // assign to DOM node, e.g. $("#myTypeaheadInput").data("myDatasourceName", data)
    });
    ```

- assign the datasource to Bloodhound as a `local` source
- I attach multiple datasources to that DOM node, and swop between them easily by doing this:

    ```javascript
    engine.clear();
    var datums = getJsonDataFromDomOrWherever();
    engine.add(datums);
    ```

I'm already doing this and it works very well.

(I guess the second part to this issue, is that we need a way to refresh the data in the Bloodhound engine. The way I've shown above works for me.)

**Comment by jharding** [comment]
How does storing it on a DOM element cache it? Isn't it equivalent to storing it in memory i.e. the data will be lost on a page refresh?

**Comment by migig** [comment]
Yes, I meant "save" or "store", not "cache".

**Comment by jharding** [comment]
In that case, what you'd want to do is set the `cache` prefetch option to `false`. This will prevent data from being stored in localStorage. Shouldn't have to involve the DOM.
