### ISSUE TITLE
Bloodhound Remote with location.host

### ISSUE THREAD

**Issue by mwsasser** [twitter/typeahead.js#1152]
While this works fine:

` remote:  '/includes/bloodhound_postal_lookup.php?query=%QUERY'`

I'm unable to use something like this:

`remote: location.host + '/includes/bloodhound_postal_lookup.php?query=%QUERY'`

Am I doing something wrong or are `location.host` or `location.hostname` not supported?

**Comment by mwsasser** [comment]
So is this a bug or a gross misunderstanding on my part?

**Comment by jharding** [comment]
Not sure why that wouldn't work. Are you getting a 404 from your backend or is a request not even being sent?

**Comment by mwsasser** [comment]
I don't think it's being sent.  I'm not getting a 404.

**Comment by jharding** [comment]
Huh, weird. BTW, pretty sure you want to do this instead:

```js
var url = location.protocol + '//' + location.host + '/includes/bloodhound_postal_lookup.php?query=%QUERY';
```

Without the protocol, the URL will be treated as a relative URL, not an absolute URL (which I don't think you want). Maybe that'll solve your problem.

**Comment by jharding** [comment]
Going to close as I'm not sure how much help I can provide. Feel free to ask more questions though if you need help.
