### ISSUE TITLE
Autocomplete Options not working

### ISSUE THREAD

**Issue by bhawi** [twitter/typeahead.js#1156]
Hi @jharding  ,
I am new to typeahead.js and I am trying to create my first demo based on the examples you have given but not getting the auto complete options.
what is the error I am unable to figure out.

![git](https://cloud.githubusercontent.com/assets/11805689/6996736/93b0167c-dbb7-11e4-97f3-aaa0cdf5ba54.PNG)

**Comment by jharding** [comment]
There's not enough info here for me to help debug. If you post more information (maybe a jsfiddle?), I can help.
