### ISSUE TITLE
How to get hint value?

### ISSUE THREAD

**Issue by PierBover** [twitter/typeahead.js#1159]
When a user starts typing and a hint gets updated, how can I get the value of the hint?

I want this in case the user does not select anything from the dropdown list and presses `enter`.

**Comment by nickpearson** [comment]
I had the same need and accomplished this by added the following two functions to the `methods` object, defined in [`plugin.js`](https://github.com/twitter/typeahead.js/blob/0fd2467baa3e0593b91794b485be0bd725b7d2cb/src/typeahead/plugin.js#L16) before the `destroy` function:

```javascript
hint: function hint() {
    return getHint(this.first());

    function getHint($input) {
        var typeahead, hint;

        if (typeahead = $input.data(typeaheadKey)) {
            hint = typeahead.input.getHint();
        }

        return hint;
    }
},

autocomplete: function autocomplete() {
    return doAutocomplete(this.first());

    function doAutocomplete($input) {
        var typeahead, query;

        if (typeahead = $input.data(typeaheadKey)) {
            typeahead._autocomplete();
            query = typeahead.getVal();
        }

        return query;
    }
},
```

If you're editing the compiled distribution, `methods` is defined on [line 244 of `typeahead.bundle.js`](https://github.com/twitter/typeahead.js/blob/0fd2467baa3e0593b91794b485be0bd725b7d2cb/dist/typeahead.bundle.js#L244).

This can be tested by running the following in a JavaScript console:

```javascript
// show the top suggestion every two seconds
setInterval(function(){ console.log($('.typeahead').typeahead('hint')) }, 2000);

// autocomplete the field based on the top hint after five seconds
setTimeout(function(){ $('.typeahead').typeahead('autocomplete') }, 5000);
```

I'm not familiar enough with the codebase to say whether this is the "right" approach, but it works for my use case.

**Comment by PierBover** [comment]
Thanks @nickpearson  I will try that!

**Comment by jharding** [comment]
FYI there's not currently a typeahead.js API for retrieving the hint value. Would be easy to add if there was enough demand. Also would be an easy task for someone who wanted to contribute.

**Comment by jharding** [comment]
Closing for now as I don't believe exposing an API for getting the hint is that compelling. Feel free to try and change my mind :smile:

**Comment by beaugogh** [comment]
getting the hints would be useful when other parts of the page need to be updated based on these hints while the user is typing

**Comment by phaddius** [comment]
Here's my argument in favor of getting the hint comes from a usability standpoint if your form only contains the one text input that is doing the typeahead.

If you are showing the hint, and the current hint is what the user wants to select, its not clear to the user that they need to hit Tab to finish the autocomplete, or to hit the down arrow and then Enter to select the first entry.  In the user's mind, the correct value is already in the input field, and all they need to do is press Enter to submit the form.  In that case, nothing happens.  I would like to detect the Enter and then get the hint value.  OR, there's no need to expose the hint value if you accept both Tab and Enter to perform the typeahead:autocomplete event.

**Comment by atlantageek** [comment]
I agree with phaddius. When there is a recommendation there needs to be a way to press enter and accept the hint.

**Comment by gstreetmedia** [comment]
Could this be as easy as adding a hint event to the conditional inside _updateHint?

```
_updateHint: function updateHint() {
      var $selectable, data, val, query, escapedQuery, frontMatchRegEx, match;

      $selectable = this.menu.getTopSelectable();
      data = this.menu.getSelectableData($selectable);
      val = this.input.getInputValue();

      if (data && !_.isBlankString(val) && !this.input.hasOverflow()) {
        query = Input.normalizeQuery(val);
        escapedQuery = _.escapeRegExChars(query);

        // match input value, then capture trailing text
        frontMatchRegEx = new RegExp('^(?:' + escapedQuery + ')(.+$)', 'i');
        match = frontMatchRegEx.exec(data.val);

        // clear hint if there's no trailing text
        match && this.input.setHint(val + match[1]);

        this.eventBus.trigger('hint', data.obj, data.dataset);
      }

      else {
        this.input.clearHint();
      }
    }
```
