### ISSUE TITLE
Numerical Ordering

### ISSUE THREAD

**Issue by xitude** [twitter/typeahead.js#1160]
When I have multiple returns with the same name minus the last digit e.g. Property 1
It orders it's it with a random digit at the end, making no sense to anyone.

![image](https://cloud.githubusercontent.com/assets/3580195/7044493/d7e1323c-ddeb-11e4-8f7e-ef671dc7f8cb.png)

As you can see in the screenshot.
Adding support for ordering via Alphabetical or Numerical would be benefiting.

**Comment by jharding** [comment]
You can use the [`sorter`](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#options) option.
