### ISSUE TITLE
Suggestion: Toggle open

### ISSUE THREAD

**Issue by voidstate** [twitter/typeahead.js#1161]
In the absence of any way of detecting if the dropdwon is open or not through the API, can I suggest that in addition to:

    myTypeahead.typeahead('open');
    myTypeahead.typeahead('close'); 

you add a toggle function to the API:

    myTypeahead.typeahead('toggle');

**Comment by jharding** [comment]
The open and close APIs have been greatly improved in recently released v0.11. I haven't gotten a chance to document them yet (the release has been so delayed, I just wanted to get it out the door), but I will eventually. For now, you can take a look at the [source code](https://github.com/twitter/typeahead.js/blob/master/src/typeahead/plugin.js#L20) to browse the new API.
