### ISSUE TITLE
Results not showing on "refocus"

### ISSUE THREAD

**Issue by GreatPotato** [twitter/typeahead.js#1164]
See this video: http://pgrm.co/0z090i0M2W2c (around the 12-13 second mark).

When refocusing on a field, results do not show unless the down arrow is clicked - this is somewhat confusing.

Is there a way to reshow results when refocusing on a field?

**Comment by jlbooker** [comment]
@GreatPotato This could be fixed with a quick event handler:
```
$('#myTypeahead').on( 'focus', function() {
		$('#myTypeahead').typeahead('open');
});
```

Unfortunately, the 'open' call seems to be broken right now. See: #1053,

**Comment by jharding** [comment]
This behavior has changed in v0.11. Refocusing on the typeahead will show the existing results.
