### ISSUE TITLE
Completion not being styled

### ISSUE THREAD

**Issue by vigna** [twitter/typeahead.js#1165]
We created a basic example (you can see it at  http://vigna.di.unimi.it/test.html )  . We are very confused, as after scanning for hours the documentation it appears that CSS are inlined and typeahead should work out of the box. However, we see a very ugly result:

![screen shot 2015-04-17 at 12 20 39](https://cloud.githubusercontent.com/assets/1464942/7200340/4dc8509a-e4fc-11e4-8d2d-8d02a11cd92b.png)

Typeahead also perturbed significantly the CSS property of the FuelUX repeater search box, that we had to fix manually.

Is there any basic CSS file we should use? If so, please discuss it in the documentation.

Note that the example does not show that, for instance, the completion list is transparent. Here's a picture from the complete page using FuelUX:

![screen shot 2015-04-17 at 12 26 40](https://cloud.githubusercontent.com/assets/1464942/7200433/1b483a58-e4fd-11e4-922d-bafbdec20034.png)

**Comment by vigna** [comment]
The situation is actually worse—attaching typeahead to the Search box of a FuelUX repeater makes the repeater ignore the Search box at all. We wonder if you have any suggestion on how to proceed.

**Comment by Eschon** [comment]
As far as I know typeahead only inlines the basic css to make it work.
I used the styles from this stackoverflow question and they work well:
http://stackoverflow.com/questions/20198247/twitters-typeahead-js-suggestions-are-not-styled-have-no-border-transparent-b
