### ISSUE TITLE
when use up/down key in dropmenu,how to set selected item as input value

### ISSUE THREAD

**Issue by glone008** [twitter/typeahead.js#1170]
question is below

**Comment by glone008** [comment]
![3](https://cloud.githubusercontent.com/assets/3043196/7250090/da7bd590-e851-11e4-8668-ccf9f9a01c70.png)
![2](https://cloud.githubusercontent.com/assets/3043196/7250089/da79d89e-e851-11e4-8158-55d48161a719.png)
![1](https://cloud.githubusercontent.com/assets/3043196/7250088/da79dcae-e851-11e4-9403-ec4d9a0de1fe.png)

**Comment by jharding** [comment]
How are you selecting the item? By clicking? By hitting the enter key when the cursor is over the item?
