### ISSUE TITLE
Feature request: Bootstrap 3 support

### ISSUE THREAD

**Issue by AnderUstarroz** [twitter/typeahead.js#1171]
Hi, 
This is a very cool library, just wondering if you are planning to add support to Bootstrap 3  at some stage. Coming from twitter it feels like a "must have" feature.

**Comment by jlbooker** [comment]
@AnderUstarroz - This was an issue I ran into as well. As this project was once part of Bootstrap's JS components, I expected it'd come with some default styles that matched Bootstrap... but it doesn't. Not only that, it doesn't come with any default styles at all.

I found a workaround in [this StackOverflow question](http://stackoverflow.com/questions/20198247/twitters-typeahead-js-suggestions-are-not-styled-have-no-border-transparent-b). Note that some of the answers have outdated CSS class names, so be sure to read all the notes on each answer.

**Comment by jharding** [comment]
No plans to support bootstrap out of the box.

**Comment by jlbooker** [comment]
Could we include a default style sheet perhaps? Judging by the StackOverflow questions, I'm not the only one who fired up the examples and was disappointed when I needed to supply all my own css just to get them looking presentable.

**Comment by jharding** [comment]
If someone wants to create a default stylesheet, I'd gladly link to it from the docs.

**Comment by hackel** [comment]
It's insane that Twitter is producing two complimentary products that don't integrate with each other.  I guess it's not really surprising from a company stuck 10 years in the past...

**Comment by cvrebert** [comment]
@hackel Bootstrap isn't affiliated with Twitter anymore; see https://github.com/twbs/bootstrap/issues/9899

**Comment by hackel** [comment]
@cvrebert Ah, I had no idea, thanks for that.

Since my initial comment, I've learned how easy it is to fix this problem with CSS.  I'm currently using and recommend this excellent stylesheet to anyone else who comes across this issue:
https://github.com/hyspace/typeahead.js-bootstrap3.less
Just drop it in and you're good to go!  It would be a great idea to link to this (and/or a competitor, https://github.com/bassjobsen/typeahead.js-bootstrap-css) from the docs.

**Comment by stickbyatlas** [comment]
Found this thread super useful. Thanks for linking to the drop-in stylesheet. A humble suggestion to include links to some of these repos from the documentation page, at least. I was in the same boat, and my instinct was to look at docs, then go to issues and search for 'css'. I'm sure I'm not the only one.
