### ISSUE TITLE
Typeahead does not keep the dropdown open like Twitter.com Search when Dev tools open

### ISSUE THREAD

**Issue by sahanDissanayake** [twitter/typeahead.js#1172]
Hi,

At the moment I need the typeahead to work just exactly like the Twitter.com search, where the dropdown stays open until I click somewhere on the body

All I need to do is to use the dev tools to style the dropdown, but the dropdown closes
http://stackoverflow.com/questions/29789767/keep-twitter-typeahead-suggestion-dropdown-open

Any help please

**Comment by jlbooker** [comment]
If you're using Google Chrome, try setting a DOM breakpoint on the typeahead element. This will pause the Javascript and allow you to inspect the element's markup and styles. See: https://developer.chrome.com/devtools/docs/javascript-debugging#breakpoints-mutation-events

**Comment by sahanDissanayake** [comment]
alright, so you cannot program typeahead to to act this way right ?

Not a prob. Thanks :+1:
