### ISSUE TITLE
Need hover-effect and pointer-change on suggestions for better usability

### ISSUE THREAD

**Issue by nileshtrivedi** [twitter/typeahead.js#1194]
None of the examples have proper mouse pointer-change and hover effects as the demo present on the homepage: http://twitter.github.io/typeahead.js/

These things are basic requirements for a user-friendly experience, in my opinion.

**Comment by adrianocola** [comment]
I'm having the same issue after migrating from 0.10.5 to 0.11.1

In 0.10.5 a mouse hover added the class .tt-cursor to a suggestion, now it doesn't

Added with CSS the desired effect:

``` css
.tt-suggestion:hover {
  background-color: #f0446a;
}
```

**Comment by jharding** [comment]
Not something that belongs in typeahead.js core. I want to limit the amount of styles applied out of the box. If you want to achieve this, then @adrianocola's solution is the way to go.

Anyways, I updated the examples page accordingly. Thanks for the report.
