### ISSUE TITLE
0.11.* - No longer uses tt-cursor on mouseover?

### ISSUE THREAD

**Issue by rally25rs** [twitter/typeahead.js#1195]
Not really an "issue" but a question.
I noticed that with 0.11.0, Typeahead no longer toggles the `tt-cursor` class on mouseover of an item in the dropdown, `tt-cursor` is only used on arrow key press.

This seems like an odd change because now you would almost always have to style your items with:

```
.tt-suggestion.tt-cursor,
.tt-suggestion:hover {
    // styling of highlighted item
}
```

to make the styling correct (consistent) for both mouse and keyboard interaction.

Was this an intentional/desired change? Was just curious what the design decision was behind this.
Thanks!

**Comment by jharding** [comment]
Yep this was intentional. It was done to make it clear that hovering over a suggestion and keying down to it are different. For example the latter will change the display value in the input whereas the former will not.

Going to close the issue, but if you have more questions, feel free to ask away.

**Comment by rally25rs** [comment]
Thanks for the info and the quick replies. I really appreciate it.

This behavior change can cause a bit of an oddity; you can arrow-down to an item, which sets `tt-cursor` on it, then use the mouse to mouse-over a different item, triggering its `:hover` styling. This makes it visually look like 2 items are selected. So its a little weird, but also depends on how styling is set up.

You can reproduce it on the main Typeahead page: https://twitter.github.io/typeahead.js/
Just click in the box, arrow down once or twice, then switch to the mouse and hover over a different item.

Bit of an edge case I suppose, but thought I would point it out.

**Comment by bartkl** [comment]
I too noticed the oddity @rally25rs mentions and think it's quite an ugly issue. There are ways around it using mouseenter/mouseleave event handlers that add/remove the tt-cursor class based on mouseover events, but it feels like it should be possible more easily in a native fashion.

**Comment by krsyoung** [comment]
Also running into this now.  User's can get themselves confused in two ways:  
1. Select a value first with the cursor then a second with the hover
2. Select a value first with the hover then a second with the cursor

![typeahead-multiselect](https://cloud.githubusercontent.com/assets/5449541/9779687/7a2eab30-574c-11e5-93ea-e16ff61b5a68.png)

Both result in the appearance of two items being selected in the list (although it is clear that only one is actually entered into the input box).   Also a little odd in that moving the cursor always updates the input value whereas moving the hover doesn't update the value until clicked.  

Per @rally25rs, all scenarios can be seen at https://twitter.github.io/typeahead.js/.  @bartkl, any chance you had luck with the mouseenter/mouseleave that you felt was somewhat pretty / would be willing to share here?

**Comment by clodal** [comment]
@jharding Why not support this usability issue natively?

**Comment by csimpi** [comment]
```
$('body').on("mouseover", ".tt-suggestion", function () {
    $('.tt-suggestion').removeClass('tt-cursor');
    $(this).addClass('tt-cursor');
});
```

**Comment by fx86** [comment]
(This being one the first search result and all) 
The following CSS highlights the suggestion on mouse-over: 

```
.tt-suggestion:hover { /* UPDATE: newer versions use .tt-suggestion.tt-cursor */
    color: #fff;
    background-color: #0097cf;
    cursor: pointer;
}
```
