### ISSUE TITLE
Unable to display more than 5 results with Bloodhound (0.11.1)

### ISSUE THREAD

**Issue by ByScripts** [twitter/typeahead.js#1201]
Hi there,

I'm using the version 0.11.1 of Typeahead.js with Bloodhound

I'm unable to display more than 5 results.

Here is my settings:

``` js
    var cityEngine = new Bloodhound({
            prefetch: './prefetch-cities.json',
            remote: {
                url: './search-cities.json?query=%QUERY',
                wildcard: '%QUERY'
            },
            sufficient: 20,
            identify: function(datum) {
                return datum.id;
            },
            datumTokenizer: function (datum) {
                return Bloodhound.tokenizers.whitespace(datum.name);
            },
            queryTokenizer: Bloodhound.tokenizers.whitespace
        });
```

I tried "limit" instead of "sufficient" (like in older versions) but it doesn't work.

Prefetch is working fine. When I type in the input, for example I get instantly 2 results... then a remote request is done to get more results. I tried this request directly, and it returns 25+ results... but typeahead displays only 5.

Thank you.

**Comment by stefanoTron** [comment]
did you try setting 'limit' in your dataset configuration? (which defaults to 5)
see https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#datasets

since 0.11 'limit' is not a Bloodhound option anymore.

**Comment by ByScripts** [comment]
My bad. Didn't see that, thank you.

**Comment by eamocanu** [comment]
Do you have an example showing how to set limit in configuration as opposed to bloodhound settings? 
I don't understand your documentation.
Thanks

**Comment by Pipozor** [comment]
Same problem here.

**Comment by cigano** [comment]
I think `sufficient` is the option again ( https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#options) but not to display items.

For me what worked is to set the `limit` property in the Data Source:

```
        var example_ds = {
            name: 'example',
            displayKey: 'Description',
            source: my_bloodhound_object,
            limit: 20
        };
```

**Comment by dougludlow** [comment]
FWIW, I had to make sure that the `limit` was one less than the number of results being returned from my remote bloodhound object or nothing would show.

**Comment by nynka** [comment]
Same thing here @dougludlow, very strange behaviour. Setting the limit to 9 when receiving 10 hits works.

**Comment by AudriusKo** [comment]
+1. I've encountered same problem.

**Comment by u01jmg3** [comment]
Is there a more robust solution to this problem (other than ensuring the `limit` is one less than the number of results being returned)? It isn't always possible to know the number of results being returned.

Is there a PR to address this issue?

**Comment by fajaryanw** [comment]
+1. I've encountered same problem.

**Comment by ghost** [comment]
$('#search-input').typeahead({
                                    hint: true,
                                    highlight: true,
                                }, {
                                    name: 'best-pictures',
                                    display: 'table_name',
                                    source: bestPictures,
                                    limit: 20
                                });
it works for me for v0.11.1

**Comment by eugensunic** [comment]
This works for me

```
  $('#some_name').typeahead({
            hint: true,
            highlight: true,
            minLength: 1,
            
        },
        {
            name: 'some_name',
            source: substringMatcher(your_array),
            limit:10
        });
```

**Comment by thiago1belino** [comment]
I've encountered same problem.
**limit: 10**, work's only local, not work for **remote** calls.

I found the possible solution in [https://github.com/twitter/typeahead.js/pull/1675/files](url)

**Comment by ThierryBrun** [comment]
using the v0.11.1. Has there been any resolution to this?  if remote dataset returns 20, and limit is set to 20, nothing shows. if limit set to 19, then 19 show.  If dataset returns 11, limit set to 20, then 9 show. If dataset returns 12, limit set to 20, then 8 show.   What has been the workaround, since no patch is available?    

[update]  looks like the infinity limit works with the throttle at the end point if that is available.  otherwise, seems like you're screwed.

**Comment by dragonheaven** [comment]
I faced same issue.
limit:10 does not work for remote.
but when I set limit:20, it does work.
It is so strange typeahead parameter now.

**Comment by gsteve3** [comment]
> FWIW, I had to make sure that the `limit` was one less than the number of results being returned from my remote bloodhound object or nothing would show.

Same here - even in January 2019. Almost bailed on typeahead because of it.
Thank you so much @fajaryanw !

**Comment by hirutv** [comment]
same here

**Comment by KishanE5** [comment]
> I think `sufficient` is the option again ( https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#options) but not to display items.
> 
> For me what worked is to set the `limit` property in the Data Source:
> 
> ```
>         var example_ds = {
>             name: 'example',
>             displayKey: 'Description',
>             source: my_bloodhound_object,
>             limit: 20
>         };
> ```

Thanks For This Solution. I was able to overcome that issue in very hard time. **Kudos**!🙌🙌

**Comment by cobycloud** [comment]
Setting typeahead limit to 10 with remote data source did not change limit from default of 5. setting limit to 20 did however. Tks dragonheaven.

Re: sufficient, I wasn't successful with sufficient.
