### ISSUE TITLE
Suiggestion menu borders not visible

### ISSUE THREAD

**Issue by ghost** [twitter/typeahead.js#1205]
Hi,

I'm using  typeahead.bundle.min.js 0.11.1 + jQuery v2.1.3
The suggestions are visible but not the box around

With  Bootstrap v3.3.4
![capture](https://cloud.githubusercontent.com/assets/12160504/7381338/b519bf68-ee02-11e4-9677-a1365b108cf5.PNG)
Without Bootstrap:
![capture2](https://cloud.githubusercontent.com/assets/12160504/7381461/caa18da6-ee03-11e4-8936-9ac64fe41d7e.PNG)

-- Jimmy

**Comment by jharding** [comment]
There's no border added by default. Only the bare minimum css is applied out of the box. If you want to add a border, something like the following will do the trick:

``` css
.tt-menu {
  border: 1px solid black;
}
```
