### ISSUE TITLE
Add a Clear Method

### ISSUE THREAD

**Issue by jimmynotjim** [twitter/typeahead.js#126]
Any chance we could get a clear method to clear the input and typeahead's results? Using jQuery's .val(''); on the input element clears it, but when you focus typeahead adds the last entered text back in. Having a clear method would be useful to create a clear button (similar to the iOS standard search fields) for small screen touch devices where selecting and clearing inputs is a bit more tedious.

**Comment by ernstralek** [comment]
This could help, I resolved this simulating the click on cancel button

`$('.typeahead__cancel-button').trigger('mousedown');`
