### ISSUE TITLE
Doesn't work with Bootstrap modal

### ISSUE THREAD

**Issue by LazyBui** [twitter/typeahead.js#1283]
Yes, I know about #147. No, it's not a solution. #378 did help style the menu but did nothing about the behavior.
#147 doesn't work meaningfully unless you have a small dialog and can spare the real estate. It's not a real solution that works regardless of the context.

I spent about 30 minutes attempting to isolate the problem in a fiddle, but ultimately I found that it wouldn't work well because it requires a remote that doesn't exist anywhere. I tried playing around with other fiddles and found that all of them were too old to still work. Add 8 fields or 10 fields or however many it takes to exceed your dialog's size and you'll see how it only works in the simplest of cases.

EDIT: Removing complaints that were definitely my fault.

**Comment by LazyBui** [comment]
I see that these two things are mutually incompatible. Can't have some elements overflow visible and some elements overflow scroll since it's based on the parent container. The way that the browser does this with real dropdowns is separate from the DOM flow.

Sorry for the trouble.

**Comment by nickmerwin** [comment]
@LazyBui did you ever find a solution or workaround?

**Comment by LazyBui** [comment]
Not that I'm aware of. I think even if you mess with the z-index, it doesn't matter because of the overflow policy. Changing the overflow policy is the only thing you can do, but that ruins the dialog. You might be able to use some JS to account for scrolling with some absurd positional hacks, but that seems suspect to me.

I don't recall specifically what I did instead back then. It might've been something like reordering the fields so that there was enough room for the dropdown or telling the business side that there's just a problem that can't really be solved as long as there's a dialog. We also may have dropped the dialog for that particular editing.
