### ISSUE TITLE
Custom event suggestions

### ISSUE THREAD

**Issue by jharding** [twitter/typeahead.js#130]
I was pretty conservative with what custom events I added in v0.9.0, now it's time to get a little crazier. Below is a combination of events I think would be nice to have and some events I've seen people asking for:
- **autocompleted** – when the user `tabs` to select the suggestion the hint is showing.
- **rendered** – suggestions for a given query were retrieved and rendered.
- **prefetch failed** – requesting or processing the prefetched data fails for whatever reason.
- **nothing left** – no suggestions were found for a given query.
- **suggestion highlighted** – the user mouses or keys over a suggestion in the dropdown menu.
- **changed** – emulate the native change event of an input element.

I'm not sure implementing all of these is plausible, but I at least wanted to document them so a discussion could be had.

Any other custom events you'd like to see implemented?

**Comment by beefchimi** [comment]
+1 for this request!

**Comment by Jerskouille** [comment]
+1

**Comment by rg-anjul** [comment]
+1
