### ISSUE TITLE
Cannot install typeahead.js using bower on Windows 10

### ISSUE THREAD

**Issue by heathyates** [twitter/typeahead.js#1303]
I have this issue [here on stackoverflow](http://stackoverflow.com/questions/31091762/how-to-get-bower-to-install-typeahead-js-for-asp-net-5-application).  

Steps to reproduce: 
1. Go to root folder of ASP.NET 5 application (assuming you have git/bower dependencies in path) 
2. Type `bower install typeahead.js`
3. The error received is `bower typeahead#~0.11.1        ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/twitter/typeahead.git", exit code of #-532462766`

The current workaround is to install the zip and move to `.bower_components` in application root. You can then use grunt or gulp to bring it in to your solution. However, I would deeply appreciate it if you could point out if you could figure out what this issue might be and what a potential fix might be. 

I'm not sure if this is typeahead.js or not, but I figure there are enough folks using .NET and doing front end development that this issue is relevant for this repo. Thanks for your patience and consideration.

**Comment by rogeruiz** [comment]
I'm currently seeing the same issue but on Mac OS X and Ubuntu.

```
~/Developer/0p9/proj/code/proj-www dev/roger/sprint12*
      ❯ bower install                                                
bower not-cached    git://github.com/twitter/typeahead.git#~0.11.1
bower resolve       git://github.com/twitter/typeahead.git#~0.11.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/twitter/typeahead.git", exit code of #128 fatal: remote error:    Repository not found.

Additional error details:
fatal: remote error:
  Repository not found.
```

I can't even do a `bower info typeahead`

```
~ rogeruiz@machete  
❯❯❯❯❯ bower info typeahead
bower not-cached    git://github.com/twitter/typeahead.git#*        
bower resolve       git://github.com/twitter/typeahead.git#*        
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/twitter/typeahead", exit code of #128              

Additional error details:                                           
fatal: remote error:                                                
  Repository not found.               
```

I ended up solving it by updating my `bower.json` and `gulpfile.js` accordingly:

```
---
 bower.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/bower.json
+++ b/bower.json
@@ -21,6 +21,6 @@
-    "typeahead": "~0.11.1"
+    "typeahead": "https://github.com/twitter/typeahead.js.git"
   }
 }

 gulpfile.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/gulpfile.js
+++ b/gulpfile.js
@@ -18,7 +18,7 @@ var paths = {
-    'typeahead'  : './vendor/bower_components/typeahead.js/',
+    'typeahead'  : './vendor/bower_components/typeahead/',
 };

--
libgit2 0.22.2

```

Hope that helps you, @heathyates!

**Comment by heathyates** [comment]
@rogeruiz This helped. Thanks a lot.
