### ISSUE TITLE
Typeahead "limit" if equal to results returned, shows "no-data".

### ISSUE THREAD

**Issue by rash805115** [twitter/typeahead.js#1312]
Bloodhound returns correct number of results. But if the number of results is same as the `limit` option in the `datasets`, then this results in showing "no-results" instead of showing all of them.

I have created this JSFIDDLE that demonstrates this issue.
http://jsfiddle.net/rash805115/kosocz84/
Note: Searching for `1947` returns exactly 5 rows.

**_When `limit` is set to 4:**_
Searching for 1947 returns 4 results.

**_When `limit` is set to 5:**_
Searching for 1947 returns nothing.

**_When `limit` is set to 6:**_
Searching for 1947 returns one 1 result - the first result.

PS: My first time reporting a bug, so maybe I am not clear enough. Please teach me if I am wrong or something is missing.

**Comment by philippeboyd** [comment]
I had the same bug today, here's what I found, hope it helps (it did for me)
http://stackoverflow.com/questions/31007825/bootstrap-typeahead-not-showing-hints-as-expected

**Comment by rash805115** [comment]
Awesome. I will also update the issue I opened and mark it as duplicate of
yours. Can you tell me the issue number that you opened.

Regards.

On Tue, Jul 7, 2015 at 6:05 PM, Philippe Boyd notifications@github.com
wrote:

> I had the same bug today, here's what I found, hope it helps (it did for
> me)
> 
> http://stackoverflow.com/questions/31007825/bootstrap-typeahead-not-showing-hints-as-expected
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twitter/typeahead.js/issues/1312#issuecomment-119357711
> .

## 

Regards,
Rahul Chaudhary
Ph - 703-568-4718

**Comment by philippeboyd** [comment]
I'm not the one who asked the question on stackoverflow sorry...
but from the looks of it, i think it's this one : #1299

**Comment by rsutphin** [comment]
This appears to be the issue fixed by #1212.

**Comment by rash805115** [comment]
@rsutphin thanks for the update...any ideas when the new build will be released. Closing this issue.

**Comment by nancy-grow** [comment]
you can set limit Infinity,
