### ISSUE TITLE
"that.limit and rendered is equal" issue

### ISSUE THREAD

**Issue by mirzaher** [twitter/typeahead.js#1330]
function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        rendered += suggestions.length;
                        that._append(query, suggestions.slice(0, **that.limit - rendered**)); // limit = 5 and rendered = 5 make issue
                        that.async && that.trigger("asyncReceived", query);
                    }
                }
My suggestion is:
function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        rendered += suggestions.length;
                        that._append(query, suggestions.slice(0, **(that.limit - rendered)==0 ? that.limit:that.limit - rendered**));
                        that.async && that.trigger("asyncReceived", query);
                    }
                }

**Comment by dvanderfaeillie** [comment]
+1

**Comment by emmarq** [comment]
I struggled with this anoying thing for 3 hours and came precisely for that. is on line 1724 in the dev unminified version. Is that a new issue? I've been using typeahead for a while and never happened before.

**Comment by ghost** [comment]
if rendered < that.limit why slice the suggestions? Shouldn't the entirety of suggestions be shown at this point?

**Comment by jlbooker** [comment]
Looks like a duplicate of #1212, has been fixed over at corejavascript/typeahead.js#8
