### ISSUE TITLE
custom DOM placement for suggestions dropdown ?

### ISSUE THREAD

**Issue by baraamashaal** [twitter/typeahead.js#1369]
i have a nav with custom `height` and it's `overflow is hidden` (note:for some animation reasons) and inside this `nav` there is a search box
so 
when i starting typing in the search box everything worked perfectly but the suggestions menu 
doesn't appear cuz of the `hidden overflow` of the parent `nav` 

```
nav{
    height:56px
    overflow:hidden
}
```

is there is any way to append the drobdown to the body !!

**Comment by mrehayden1** [comment]
Some way of specifying where the suggestions element should be inserted/appended would be great.
@baraamashaal Maybe this issue could be renamed to encompass a more generic solution?

**Comment by baraamashaal** [comment]
maybe this help #875 
i don't see any documentation  for this option but it should work !!
