### ISSUE TITLE
Bloodhound#get(ids) not working

### ISSUE THREAD

**Issue by doutatsu** [twitter/typeahead.js#1377]
I am trying to use this function, but I get an error:

``` javascript
Uncaught TypeError: a.split is not a function(…)
```

when I am trying to do say 

``` javascript
var engine = new Bloodhound({
    local: [{ id: 1, name: 'dog' }, { id: 2, name: 'pig' }],
    identify: function(obj) { return obj.id; },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    datumTokenizer: Bloodhound.tokenizers.whitespace
  });

engine.get([1, 3]);
```

**Comment by garncarz** [comment]
How did you solve this? I've got similar problem, that `engine.get([...])` returns an empty array (when used in some `.on('change', function() { ... })`, although suggestions work otherwise.

**Comment by garncarz** [comment]
Solution described at bassjobsen/Bootstrap-3-Typeahead#163.
