### ISSUE TITLE
Typeahead not shown for some results

### ISSUE THREAD

**Issue by lucas03** [twitter/typeahead.js#1381]
Hi,
I am having trouble with typeahead. It works for some queries and does not for others. Here is my <a href="http://stackoverflow.com/questions/32443644/remote-autocomplete-by-typeahead-works-only-on-unique-queries">stackoverflow question</a>. Is it inappropriate use of typeahead.js code or a bug?

**Comment by justinstern** [comment]
0.11.1 release is broken, patch can be found in #1232 #1299 #1185

probably duplicate/related issues: #1368 #1333 #1314 #1294 #1244 #1238 #1226 #1220 #1218 #1204 #1198

**Comment by lucas03** [comment]
ok, thanks. Sorry for duplicate issue.

**Comment by justinstern** [comment]
no worries, I just spent a couple hours fighting with this before I realized it had already been identified and fixed so I wanted to save as many others from dealing with it as possible and help tie all the related issues together. This is an awesome library, hopefully it continues to be maintained
