### ISSUE TITLE
Remote loading does not show all results

### ISSUE THREAD

**Issue by jesperronn** [twitter/typeahead.js#1405]
For the remote example https://twitter.github.io/typeahead.js/examples/#remote (oscar winners):

Given I enter "`wi`" in the field, the remote result returns the [following 3 items](https://twitter.github.io/typeahead.js/data/films/queries/wi.json):

```
[
  {
    "year": "1927/1928",
    "value": "Wings",
    "tokens": [ "Wings" ]
  },
  {
    "year": "1938",
    "value": "You Can't Take It with You",
    "tokens": [ "You", "Can't", "Take", "It", "with", "You" ]
  },
  {
    "year": "1939",
    "value": "Gone with the Wind",
    "tokens": [ "Gone", "with", "the", "Wind" ]
  }
]
```

The suggestions only show 2 results. **Where is "Gone with the Wind"??**

I am seeing the same kind of error in my own application. Can you point me in which direction to find the error??

Screenshot displaying only 2 of the 3 results:
<img width="953" alt="typeahead_js_ _examples" src="https://cloud.githubusercontent.com/assets/6267/10514417/ddfe9b30-734d-11e5-9fe1-886572dd5de1.png">

**Comment by jesperronn** [comment]
Note this is apparently fixed by https://github.com/corejavascript/typeahead.js/pull/8 and #1212 

But since this repos is being abandoned, I refer to the fixes and use the version from the new repository.

**Comment by carlosagsmendes** [comment]
@jesperronn could you please clarify which repo is being abandoned? Thanks in advance

**Comment by jesperronn** [comment]
Abandoned: This repo https://github.com/twitter/typeahead.js
Continued: https://github.com/corejavascript/typeahead.js

**Comment by carlosagsmendes** [comment]
Thanks for the heads-up

**Comment by chialunwu** [comment]
@jesperronn  You save my life, thanks...
