### ISSUE TITLE
Prevent close on suggestion selected

### ISSUE THREAD

**Issue by gremo** [twitter/typeahead.js#1408]
Is there a way to prevent close the dropdown (.tt-menu) when a suggestion is clicked? I've searched a lot and none of these "hacks" works with current version:
- https://github.com/twitter/typeahead.js/issues/731
- https://github.com/twitter/typeahead.js/issues/1113
- http://stackoverflow.com/questions/20182058/prevent-typeahead-js-dropdown-from-closing-on-select

**Comment by laCour** [comment]
`select` is [called](https://github.com/twitter/typeahead.js/blob/588440f66559714280628a4f9799f0c4eb880a4a/src/typeahead/typeahead.js#L347) when an item is selected (requires >=0.11). You can prevent the default behavior of this method by listening to the `typeahead:beforeselect` event and cancelling it with `event.preventDefault()`, like so:

``` javascript
$(document).on("typeahead:beforeselect", function(event, data) {
  event.preventDefault();
});
```

**Comment by zedtux** [comment]
@laCour your tip is not more working, do you know another way to do it now?

**Comment by laCour** [comment]
@zedtux It still works for me. If you're not using jQuery my example wont work and would require changes. What version of typeahead are you using?

**Comment by zedtux** [comment]
I double checked and while I was thinking using the version 0.11, I just discovered that I'm using the version 0.10.5.

This should explain why it is not working.

I'm upgrading to 0.11.1 and I'll check again.

**Comment by zedtux** [comment]
Hell yeah, it's working now, thank you :)
