### ISSUE TITLE
Add event for "suggestionsRendered"

### ISSUE THREAD

**Issue by ustun** [twitter/typeahead.js#141]
Ideally, there should be separate events for each dataset, and also another after all datasets have been rendered.

I currently workaround this with the following:

``` javascript

    $('#foo').data('ttView').dropdownView.on('suggestionsRendered', function () {
        this.$menu.find('.tt-dataset-query').remove();
        var searchTerm = $('#foo').val();
        var $newTermSuggestion = $("<div class='tt-suggestion'><p>" + searchTerm + "</p></div>");
        // Todo: searchterm should be url encoded
        $newTermSuggestion.data('suggestion', {value: searchTerm,
                                               datum: {url: '/search/?q=' + searchTerm,
                                                       value: "this is the value"}});
        var $newTerm = $("<div class='tt-dataset-query' style='display:block'><span class='tt-suggestions' style='display:block'></span></div>");
        $newTerm.find('.tt-suggestions').append($newTermSuggestion);
        this.$menu.append($newTerm);
        console.log("suggestions rendered");
    });
```

Note that this is non-ideal for two reasons: 1- it delves into the internals too much. 2-it is trigger once for each data set (hence the `remove` call).

The use case for this is the following:

In addition to the autocompleted values, I want to allow the user to use the raw input query as the last choice. The reason I can't use the value that is already in the input field is that I prefer to immediately select the first choice upon rendering (for which I will file another bug.)

**Comment by kirbo** [comment]
Any estimates when this `typeahead:render` event will be implemented into `master`?

**Comment by lhwparis** [comment]
i need this event too!

**Comment by kirbo** [comment]
*Ping*

**Comment by rg-anjul** [comment]
we would appreciate having this too!

**Comment by kirbo** [comment]
Any estimate on implementing this?
