### ISSUE TITLE
Disable html escaping

### ISSUE THREAD

**Issue by bart** [twitter/typeahead.js#1456]
The typeahead plugin is awesome, but when fetching remote data which is already rendered HTML it gets escaped by typeahead, so in my suggests I get something like this:

```
Jupiter is the <strong>best</strong> planet
Nickelback is the <strong>best</strong> band
Github is the <strong>best</strong> repo source
```

I want to get it "as it is". Do you guys have any idea for this?
Thanks a lot!

**Comment by bart** [comment]
Solved by using custom template functionality

**Comment by willthemoor** [comment]
In case someone else comes across this, it required a tiny change to the handlebars templates. From:

`{{token}}`
to
`{{{token}}}`

**Comment by martinschilliger** [comment]
And for an Example of how to use custom templates: (copied from #1031, http://pastebin.com/qwYafvZU)

```
templates: {
  suggestion: function(data){
    return '<p><strong>' + data.value + '</strong> - ' + data.year + '</p>';
  }
}
```

Use this format for json: https://twitter.github.io/typeahead.js/data/films/post_1960.json
