### ISSUE TITLE
source.asyncResults not working as expected

### ISSUE THREAD

**Issue by pubkey** [twitter/typeahead.js#1470]
I wanted to show async results, but it doesnt work as described in the docs.
Here is my code:

``` js
        $('input').first().typeahead({
            minLength: 1
        }, {
            async: true,
            source: function (query, syncResults, asyncResults) {
                console.log('source() called');
                asyncResults([
                    'asdf',
                    'asdfasdf',
                    'sadfgsdfg',
                    '324f43'
                ]);
            }
        });
```

When I switch asyncResults to syncResult, it works as exected.

**Comment by pubkey** [comment]
example here: [jsfiddle](https://jsfiddle.net/pkfn3t4k/)

**Comment by alberto-bottarini** [comment]
Take a look here: https://github.com/twitter/typeahead.js/issues/1435

**Comment by pubkey** [comment]
Thank you @alberto-bottarini for your answer.
The code you referenced to, might help, but since this project is abandoned, I switched to an alternative.
