### ISSUE TITLE
bower install fails on ubuntu and mac

### ISSUE THREAD

**Issue by mani-mishra** [twitter/typeahead.js#1472]
bower install typeahead
bower typeahead#\*           not-cached git://github.com/twitter/typeahead.git#*
bower typeahead#\*              resolve git://github.com/twitter/typeahead.git#*
bower typeahead#\*              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/twitter/typeahead.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by mariofink** [comment]
I think you are trying to install the wrong repository.
Try this insead:
`bower install typeahead.js`
