### ISSUE TITLE
Any support?

### ISSUE THREAD

**Issue by adamasantares** [twitter/typeahead.js#1562]
There are so many issues and no fixes. Please, let us know if this plugin hasn't support anymore...

**Comment by MrHubble** [comment]
Apparently this project is no longer maintained as discussed here: https://github.com/twitter/typeahead.js/issues/1424

It was recommended to use https://github.com/corejavascript/typeahead.js but that hasn't been updated for 8 months so I'm not sure if that's the best solution either.

https://github.com/algolia/autocomplete.js was also recommended and it has recent activity.

**Comment by bitcity** [comment]
Feature-wise, there are a few better options
- https://github.com/selectize/selectize.js
- https://github.com/select2/select2

Both are a bit heavier than typeahead.js but have a lot more features like multiple select, pagination, infinite scroll, mobile support etc. 
Select2 is slightly bigger than selectize.js and extending it is complicated in the current version (4.x). Hence I've found selectize.js to be a good replacement for my projects.

**Comment by adamasantares** [comment]
@bitcity thank you for links, but my problem is that the client's project uses this plugin and I can't change it to other plugin for now :(

**Comment by josephearl** [comment]
As someone who uses the library in a few projects I would highly welcome a canonical fork (ideally with a notice in this repo) in the hands of someone who has the time and energy to maintain this.

I'd also note to Twitter devs that it is much better for reputation and brand to pro-actively identify unmaintained projects and mark these as such clearly at the top of the README so the community knows it is OK to create a new canonical fork (and offering to include a link to that fork from your repo).

**Comment by adamasantares** [comment]
My choise is https://github.com/pawelczak/EasyAutocomplete
