### ISSUE TITLE
Typeahead integration with Selenium for testing. Filling event is not recognised  

### ISSUE THREAD

**Issue by rikirenz** [twitter/typeahead.js#1573]
I am testing a web form with typeahead, selenium and py.test. 
Selenium version: 2.53.1
Typeahead version: 0.11.1
Browser type & version: selenium/standalone-firefox:2.53.1
Environment: Ubuntu 14.04 on docker

I am trying to trigger the event of click on a suggestion element. Anyway typeahead seems to capture the click but is not filling the input_text_element with the value that I have chosen.

Do you have an idea how to test typeahead with selenium+Firefox  in order to trigger the filling event?

this is my testcase:

``` python
import [...]

#my test
def test_advisors_typehead(selenium, login):
    """"Test the suggestions in the advisors field"""
    selenium.get(os.environ['SERVER_NAME'] + '/submit/author/create')
    advisor_field = selenium.find_element_by_id("advisors-0-name")
    force_autocomplete_event(advisor_field, "alexe", selenium)
    assert 'Vorobyev, Alexey' in advisor_field.get_attribute("value")

#auxiliar func
def force_autocomplete_event(field, chunk_text, selenium):
    """Performs selection in a html text field"""
    field.send_keys(chunk_text)
    WebDriverWait(selenium, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "div.tt-suggestion"))).click()

```

I have also debugged the code and the click event works. It means that selenium is able to find the element in the DOM and click it. Anyway the assertion is still failing.

**Comment by hjwp** [comment]
I can't even get selenium to trigger the autocompletion menu.  `send_keys` just puts text into the input box, but no suggestions appear...

**Comment by hjwp** [comment]
Progress!  I found that if I `send_keys` the characters one by one, instead of in a single call, it does trigger the suggestion menu.  Hope others find it useful!

**Comment by seashaw** [comment]
@hjwp I'm experiencing a similar issue with selenium driving firefox in a windows environment. Were you able to use selenium to 'click' on a typeahead suggestion to get it to fill the input?

**Comment by rikirenz** [comment]
the solution for this issue was pretty easy ( @hjwp @seashaw  ). Here the code:

``` python
field.send_keys(field_value)
WebDriverWait(self._instance, 10).until(
	EC.presence_of_element_located(
		(By.CLASS_NAME, "tt-suggestions")
	)
)
#here the solution
field.send_keys(Keys.DOWN)
field.send_keys(Keys.ENTER)
```

Anyway this is selecting only the first element in the suggestion list
