### ISSUE TITLE
new feature: different spellings/misspellings of countries

### ISSUE THREAD

**Issue by sulthan-ahmed** [twitter/typeahead.js#1577]
Their is a business case to have different spellings and misspellings of countries.  This is a requirement for registered traveller.  I'm happy to work on this but I thought I should raise it.  A good example of what RT want is here

http://baymard.com/labs/country-selector

**Comment by wordpressmz** [comment]
Hi Ahmed,

Sorry to ask such a stupid question. Actually I am trying to use the typeahead for some time. But I am new to coding and javascript so can't figure out which files to use.

Can yu guide?

**Comment by sulthan-ahmed** [comment]
sorry wrong area, @wordpressmz please private message me and I can help you but this is probably not the right area for discussion of how to use this
