### ISSUE TITLE
Problems with remote dataset

### ISSUE THREAD

**Issue by jcacha** [twitter/typeahead.js#1583]
Hello,
I've got problems when I use the remote dataset because I've got this error in my log.

`2016-11-02 14:44:56 [::1][-][-][error][yii\web\HttpException:404] exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request: control/empresas?q=%QUERY' in C:\wamp\www\Mahou\controlWeb\vendor\yiisoft\yii2\base\Controller.php:125
Stack trace:`

This is my Typehead widget:
`<?php 	    	
	    		echo '<label class="control-label">Empresa</label>';
				echo Typeahead::widget([
					'model' => $model,
					'attribute' => 'empresa',				    
					'scrollable' => true,
				    'pluginOptions' => ['highlight'=>true,
				    					'minLength' => 3,
				    					],
				    'dataset' => [
				        [
				            'remote' => Url::to(['control/empresas']) . '?q=%QUERY',
				        	'limit' => 10,
				        ]
				    ],
				]);
			?>`

And this is my action in the controller
```
use yii\db\Query;
use yii\helpers\Json;

public function actionEmpresas($q=null){
	    //Realizamos la busqueda de las empresas	    
	    $query = new Query();
	    
	    $query->select('Nombre')
	    ->from('empresa')
	    ->where('Nombre LIKE "%' . $q .'%"')
	    ->orderBy('Nombre');
	    $command = $query->createCommand();
	    $data = $command->queryAll();
	    Yii::warning($data);
	    $out = [];
	    foreach ($data as $d) {
	    	$out[] = ['value' => $d['Nombre']];	    	
	    }
	    Yii::warning($out);
	    echo Json::encode($out);
    }
```

Any suggestions?? I need help
Thanks!!!

**Comment by jlbooker** [comment]
@jcacha From the error message, it looks like the typeahead widget isn't replacing the `%QUERY` placeholder with the search terms that the user typed in. This probably has to do with the way your PHP code is outputting the Javascript. Instead of the PHP code, you'll need to look at what that's actually outputting for the Browser. The javascript it's generating is probably incorrect. Check the output of `echo Typeahead::widget(...)`.

**Comment by jcacha** [comment]
Thanks @jlbooker!!! Finally I found the problem. If you put '?q=%QUERY' the browser interprets it as a part of the route, but now q=%QUERY is a parameter. So if you change it and put and '&' instead of '?' everything is all right!!!
Greetings! Thx for your attention!!
