### ISSUE TITLE
typeahead suggestions show only search string

### ISSUE THREAD

**Issue by kaiaeberli** [twitter/typeahead.js#1598]
When writing a search string, the dropdown opens but only shows the search string repeated as many times as there are results.

It seems _getSuggestionsFragment in Dataset is causing the problem. Inside the _.each loop, the element $el is assigned data (which it doesnt receive, as .data doesnt seem to work in jquery, from documentation seems one needs to use $.data(obj, key, val)). The final element $el ends up with the search string as its textContent, innerHtml etc.

This occurred for me after upgrading from version 0.10.4.

**Comment by kaiaeberli** [comment]
solved it: my displayKey function in the typeahead setup was return a json object, not a string.

**Comment by mgonzaleza** [comment]
@kaiaeberli This issue should probably be deleted :)
