### ISSUE TITLE
Add `.typeahead('update')` method to reload a dataset

### ISSUE THREAD

**Issue by 907th** [twitter/typeahead.js#1644]
Add `.typeahead('update')` method to reload a dataset.

Typeahead calls `Dataset.update` only when new entered text is different from the text already put into input, but sometimes datasource depends on dynamic attributes which can change even if input text is not changed.

To avoid this limitation I had to use a hack:
```
  var resetAccountAutocompletion = function() {
    var oldVal = $accountNumber.val();
    $accountNumber.typeahead("val", "SomERandDomStrInG61792374876");
    $accountNumber.typeahead("val", oldVal);
  };
```

**Comment by 907th** [comment]
I can create a PR after a review of this issue.

**Comment by rajkotgire** [comment]
hi, i have similar situation where i need to update dataset on some event. Can you please let me know sample code that you implemented  and from where to call the update method.
thanks, your help is appreciated.

**Comment by TarasKovalyk** [comment]
I have faced with similar issue, could you provide some sample of the code? Thanks in advance.

**Comment by 907th** [comment]
@TarasKovalyk I simply call `resetAccountAutocompletion()` (from the first post) when I need to force autocomplete suggestions reloading.

**Comment by aelfannir** [comment]
I had the same problem and finally fixed by disabling remote's cache;
By default the remote cache is `true`, simply set it to `false`,
`remote : { cache : false ...}`

**Comment by 907th** [comment]
I'm closing stale issue.
