### ISSUE TITLE
Show a spinner in the meantime the client is waiting for the results.

### ISSUE THREAD

**Issue by loalf** [twitter/typeahead.js#166]
First off, thanks for this library, it's just great.

I wonder whether it's possible to catch an event to show a spinner or something or the screen in the meantime the browser is waiting for the server to reply.

Thanks!

**Comment by mjansing** [comment]
Any updates? I'm also interested in a clean way to implement a loading indicator.

**Comment by austinzuffi** [comment]
hint wasn't a good solution in my situation, i set the background image of my typeahead input
in my css
````
.loading {
    background: transparent url('/img/loading.gif') no-repeat scroll right center content-box;
    background-size: contain;
}
````
and in my js
````
$('.typeahead').addClass('loading');
$('.typeahead').removeClass('loading');
````
at my specifically appropriate locations

**Comment by pottabathini** [comment]
where can I download v0.11 still in github showing 0.10.5 version only, can any one provide link

**Comment by apfelbox** [comment]
@pottabathini v0.11 is not yet released, see #1068

**Comment by kierandelaney** [comment]
@pottabathini v0.11.1 is out now.

**Comment by mrchief** [comment]
None of these (ajax prefilters, new 0.11.0 custom events) work during `prefetch`. Is there anyway to show loading while `prefetch` initializes?

**Comment by rajanrawal** [comment]
For the all dropping here agian:

``` javascript
// Instantiate the Typeahead UI
$('.typeahead').typeahead(null, {
    displayKey: 'value',
    limit: 10,
    source: creditors.ttAdapter()
})
.on('typeahead:asyncrequest', function() {
    $('.Typeahead-spinner').show();
})
.on('typeahead:asynccancel typeahead:asyncreceive', function() {
    $('.Typeahead-spinner').hide();
});
```

**Comment by GorozJS** [comment]
if you wan't add loader for input
$('.typeahead').typeahead(null, {
    displayKey: 'value',
    limit: 10,
    source: creditors.ttAdapter()
})
.on('typeahead:asyncrequest', function() {
// if you add loader from css
  //$(this).addClass('loader');
    $(this).show();
})
.on('typeahead:asynccancel typeahead:asyncreceive', function() {

  //$(this).removeClass('loader');
    $(this).hide();
});

**Comment by ghost** [comment]
Arrived late to the party, but you can combine @rajanrawal solution with some CSS3 animations and glyphicons and come up with a nice little loader:

.glyphicon-refresh-animate {
  -animation: spin .7s infinite linear;
  -webkit-animation: spin2 .7s infinite linear;
}

@-webkit-keyframes spin2 {
  from { -webkit-transform: rotate(0deg); }
  to { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  from { transform: scale(1) rotate(0deg);}
  to { transform: scale(1) rotate(360deg); }
}

**Comment by klibansky** [comment]
I notice that when the search returns nothing, or when you type something that returns nothing/something but then remove the text, the spinner doesn't disappear.

**Comment by trungvose** [comment]
For input with loading icon placed on the right while typing. Can use the code below.

```css
.input-loading {    
    background-color: #ffffff;
    background-image: url("http://loadinggif.com/images/image-selection/3.gif");
    background-size: 25px 25px;
    background-position:right center;
    background-repeat: no-repeat;
}
```

```javascript
$('.typeahead').typeahead(null, {
    displayKey: 'value',
    limit: 10,
    source: creditors.ttAdapter()
}).on('typeahead:asyncrequest', function() {
        $('.typeahead').addClass('input-loading');
    })
    .on('typeahead:asynccancel typeahead:asyncreceive', function() {
        $('.typeahead').removeClass('input-loading');
    });
```

Preview: http://jsfiddle.net/tejsoft/7pzgtevv/4/

**Comment by atefBB** [comment]
@DrBenton Your solution doesn't seem to work for me. Any ideas?

**Comment by dximpress** [comment]
Hi everybody, if anybody nowaday have a same problem, I resolve with this:

Here an example.

```
$('.typeahead').typeahead(
  {
    hint: true,
    highlight: true,
    minLength: 1,
    //maxItem: 5,
  },
  {
    name: 'usuario',
    displayKey: 'nombre',
    source: listadoEstudiantes.ttAdapter(),
    templates: {
      empty: function() {
        var string = '<p class="tt-suggestion-link tt-notfound"> Ninguna coincidencia<p>';
        return string;
      },
      pending: function(data) {
        console.log('cargando listado');
        var string = '<p class="tt-suggestion-link tt-notfound"> Cargando listado... <img src="img/loading_2.gif"> <p>';
        return string;
      },
      suggestion: function(data) {
        var string = '<p class="tt-suggestion-link">' + data + '<p>';
        return string;
      }
    },

  }
);
```

Just change "img/loading_2.gif" for your own directory and loader image.

**Comment by sokollondon** [comment]
https://stackoverflow.com/questions/43674174/adding-clear-and-loading-icons-to-twitter-typeahead-js-input/61357920#61357920
