### ISSUE TITLE
How to read data from bloodhound if we provided a URL?

### ISSUE THREAD

**Issue by maryam-abdullah** [twitter/typeahead.js#1680]
Hello, 
I was wondering how is it possible to read data from bloodhound if I provided a URL.

Here's my code:
`search_country_code = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('country', 'country_code'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
                prefetch: {
            url: JS_RESOURCES.ZonesUrl,
            filter: false
          }
    });
search_country_code.initialize();
    $('.main_search_bar input.form-control').typeahead(null, {
        name: 'country-codes',
        display: 'country',
        source: substringMatcher(search_country_code.prefetch.storage.ls['__/Posts/GetZoneData__data'])["datums"]),
        limit: 7,
`

After caching is gone, the data inside storage is not updated. How do I get the updated values?
Am I obliged to use the local option in bloodhound in order to pass it as a parameter for my substringMatcher function?

Many thanks,

**Comment by Ahtetep** [comment]
JSON.parse(search_country_code.prefetch.storage.ls["__/Posts/GetZoneData__data"]).datums
