### ISSUE TITLE
Dropdown closes and reopens on keypress with remote dataset

### ISSUE THREAD

**Issue by ndreckshage** [twitter/typeahead.js#176]
You can see this with the best pictures example [here](http://twitter.github.com/typeahead.js/examples/)

Start typing 'broadway' (pre 1960 example that is not prefetched). At 'bro' it will be isolated from prefetched data. then each additional letter ('a', 'd', ...) will close + reopen dropdown with same value.

**Comment by joekur** [comment]
The fix for this appears to have been lost in v 0.11. Can anyone confirm one way or the other?

**Comment by iMoses** [comment]
I'm experiencing the same issue and would like an option to fix it very much. It looks bad when the dropdown is flickering between each keystroke.

**Comment by joekur** [comment]
@iMoses check out my fork here if you're in need of a quick fix: https://github.com/reverbdotcom/typeahead.js/commit/79b4f088e713e7d5f5156f5b8054164b87fd89af

I was hoping to get an answer here and get another pull merged in (one of #1224, #1233, or #1212) before opening a pull for this.

**Comment by iMoses** [comment]
@joekur, Thanks! I was just starting to debug it, you saved me quite a lot of time :+1: 

Please update the official code ASAP, it's the only true problematic behavior I came across of an otherwise excellent library which I really want to keep using :)

**Comment by jacksondc** [comment]
I'm having the same problem. Any hope for a fix?

**Comment by yashshah** [comment]
I'm facing the same problem. Anyone found the solution yet?

**Comment by Andy6792** [comment]
Same issue here.

**Comment by gaborbernat** [comment]
https://github.com/gaborbernat/typeahead.js/commit/6e8a91b05d7fa875101af09f26c71e9adf313a79

**Comment by ldaug** [comment]
Any update on this? I tried a few of the unofficial fixes (which did not help), but would like an official fix\response, as this issue makes the control unusable in my opinion.

**Comment by joekur** [comment]
This project has apparently been abandoned. See https://github.com/corejavascript/typeahead.js where I believe many of these issues have already been resolved.

**Comment by ldaug** [comment]
Thanks. I was unaware.
