### ISSUE TITLE
execute typeahead only after x amount of char's typed

### ISSUE THREAD

**Issue by adardesign** [twitter/typeahead.js#179]
Please allow a option to only trigger a typeahead when x amount of char's are typed..

Or at least provide a hook (like `beforeSend`) where we can cancel or modify the `query` before it get into the typeahead engine.

**Comment by rahuldadhich** [comment]
Thanks, `minLength` works perfectly. 
But there is an issue when I use `minLength` with ajax autocomplete. Ajax calls after 3 characters but when I backspace(delete) from textbox ajax called with last 1 character also. Means issue when deleting from a textbox.
