### ISSUE TITLE
Opt-out of autocomplete / _setInputValueToQuery OnBlur

### ISSUE THREAD

**Issue by KrisJordan** [twitter/typeahead.js#182]
We are using typeahead to populate a list of selected items. On selection an item is added to the list and the typeahead input is cleared. OnBlur we'd like to leave the input empty rather than populated with the last item selected.

We tried capturing, stoping propagation, and manually focusing onBlur without luck.

Our current hack solution is modifying typeahead.js to clearSuggestions in the handler for blurred/cursorRemoved:

```
_setInputValueToQuery: function() {
    this.dropdownView.clearSuggestions();
},
```

Is there an obvious way to do this we're missing? If not, this would be really handy in list creation scenarios.

Thanks (and awesome work, the new events are great!).

**Comment by gmolinart** [comment]
> 

OH stranger from the past, thank you for your wisdom !! 

 $(el).typeahead('val', '');
