### ISSUE TITLE
new remote request sent when clicking on a suggesting

### ISSUE THREAD

**Issue by asafatzmon** [twitter/typeahead.js#188]
(0.9.1) When clicking on a suggestion that was returned from a remote query, another query is sent to the server with the suggestion text as the query string.
Looking into the code, it looks as the TypeaheadView._handleSelection method is resetting the input field value to that of the selected suggestion without passing a reset=true param to  setInputValue() , which causes a re-invocation of typeahead request.

I had to change the code to pass true for reset to surpress this behavior.

**Comment by asmaazoghbi** [comment]
I have problem when opening of the form,(edit mode) ,the input that is filled is re sending ajax call.
I have 5 input filled.so once i open the form 5 ajax calls are being sent.
The function is initialized in document.ready, how can I prevent sending ajax calls on open of the form with input that already has a value.

Any suggestions please?
