### ISSUE TITLE
Callback on Dataset

### ISSUE THREAD

**Issue by dannyc** [twitter/typeahead.js#196]
In addition to the custom events, it would helpful if one could designate a callback on a selection for a specific Dataset. The use case would be like your NBA & NHL example.  It the user chose a hockey team you might want to take them to their respective NHL site as opposed to a basketball team where you might want to display some information on your own page.
Alternatively, a similar result could be achieved if the category/dataset name was somehow included in the data that get triggered with the standard custom callback events.  Since right now the data is a datum, and we have no way of programmaticly knowing from which dataset it came.
Thoughts? Thanks.

**Comment by lteu** [comment]
2 years have been passed and we still cannot have .on('typeahead:selected', function($e, data, data_set) {} as a solution. That's really absurd!

**Comment by larsalbrecht** [comment]
Three years? Currently it does not work :(
Used the "workaround" with the additional data from the comment in this thread.

**Comment by maxchene** [comment]
Can we reopen this issue as it is not solved yet ?

**Comment by waheedkk** [comment]
any update on this issue ?
