### ISSUE TITLE
Dropdown below *each word*?

### ISSUE THREAD

**Issue by turian** [twitter/typeahead.js#208]
It would be useful to have an option where the dropdown appears below the last word, and selecting the typeahead overwrites only that last word.

![Example](http://i.stack.imgur.com/VgZH4.png)

I saw this discussed on StackOverflow:
http://stackoverflow.com/questions/14672433/jquery-ui-autocomplete-dropdown-below-each-word
and there is some jQuery code. I don't know how to integrate this with typeahead.js

Here is some standalone working Javascript code: http://jsfiddle.net/jc92619/3yTPJ/3/

**Comment by Loremaster** [comment]
+1 To this issue. I have `To:` field in the email form where user can be put several emails. I want to have autocomplete after space or comma but that doesn't work. That is really sad.

**Comment by monprin** [comment]
+1 I would also like to use this to input multiple gene names as part of a query set.
