### ISSUE TITLE
Manually add a suggestion

### ISSUE THREAD

**Issue by psaikali** [twitter/typeahead.js#210]
Hi,

I'm trying to add a global "Search for ****" suggestion at the end of my autocomplete dropdown with a link to /keyword/%keyword%, %keyword% being the word the user entered in the typeahead field.

I added a keydown event on the typeahead field and I successfully insert my custom link at the end of the autocomplete dropdown, but the result isn't perfect as arrow-keys navigation doesn't work on that newly added suggestion. What would be the best way to add/render a "custom" suggestion simply (with custom link) based on the field value (so I guess I could not called that a suggestion as this is the exact word the user typed ;)).

Thanks!

**Comment by canfiax** [comment]
Yeah, I am actually looking for something like this!

**Comment by canfiax** [comment]
Above currently doesn't work in current version.

**Comment by bramchi** [comment]
I've been riding the typeahead:render event to append a custom suggestion in version 0.11.1. It seems to work great, keyboard controls and all.

``` javascript
$('.typeahead').bind('typeahead:render', function(event, suggestions, async, dataset) {
    if( suggestions != undefined && $('.tt-all-results').length <= 0){ // only add if suggestions are available and custom element not already present
        $('.tt-dataset').append( '<div class="tt-suggestion tt-selectable tt-all-results">Show all results</div>');
    }
});
```
