### ISSUE TITLE
Attaching typeahead behavior to dynamically added elements

### ISSUE THREAD

**Issue by thelubin** [twitter/typeahead.js#224]
I am trying to figure out how to add the typeahead behavior to a dynamically added element. I now catch the onInsert event for the new typeahead elements and add the properties (below). However, I don't get the typeahead behavior.

``` javascript
prefetch: '/words.json',
valueKey: 'name',
limit: 30,
template: [
'<p class="repo-name">{{name}}</p>',
'<p class="repo-description">{{description}}</p>'
].join(''),
engine: Hogan
```

Can anyone help me on how to add the typeahead behavior to a dynamically added element?

**Comment by ParthBarot-BoTreeConsulting** [comment]
@jharding Thanks, Your comment worked for me. I was trying to bind it inside `keyup` for the new dynamically added element, but instead we can use this.
