### ISSUE TITLE
Add "on demand" initialization 

### ISSUE THREAD

**Issue by ghost** [twitter/typeahead.js#227]
I wonder if it makes sense to add an "on demand" plugin initialization option, in order to  speed up a little the page load and perform the DOM manipulations as late as possible. I think it may be beneficial for many js-heavy websites. 

I've used this simple trick

``` javascript
var $field = $('#text-search-input');

$field.one('keyup', function () {
    $field.typeahead(
        [
            //datasets
        ]
    );

    $field.on('typeahead:initialized', function () {
        $field.focus();
    });
});
```

but this can be integrated inside the plugin, and toggled by some bool argument.

**Comment by Echecivuole** [comment]
I agree with @chetzof . Currently the initialization load ALL records from the datasource and print in inspector network tab. this means that I have the search bar in the header, it loads ALL records at any page loading. 

Is the above solution the best one to load suggestions only when user starts searching?
