### ISSUE TITLE
How do you clear the input/hint ?

### ISSUE THREAD

**Issue by othmoz** [twitter/typeahead.js#233]
I need a way to clear the hint programatically any help ?
I tried setting the input val to '' $('#typeahead-input').val(''); and the next span holding the hint with no luck.

**Comment by ggndpsingh-old** [comment]
In case someone wanders in here having the same issue and having tried all the given solutions and failed, try adding a timeout to clearing of the typeahead field after selection. I spent an hour on this and adding a timeout of just 10 milliseconds did the trick.

**Comment by BenSummerhayes** [comment]
ggndpsingh.....Good Man, your suggestion saved me a headache! Ridiculous that we would have to do this but there you go. 

example:

setTimeout($.proxy(function(){$('.typeahead').typeahead('val', ''); }, this), 500);

OR without proxy

setTimeout(function(){$('.typeahead').typeahead('val', ''); }, 500);

**Comment by xrnm** [comment]
@jharding Thanks!

**Comment by appsparkler** [comment]
@ggndpsingh thank you!

For anyone facing an issue on **AngularJS**

```
$timeout(function () {
                    $('.typeahead')
                         .typeahead('val', '');
               }, 0);
```
