### ISSUE TITLE
When Tokens Include Spaces Using a Space in the Search Term Stops the Suggestions

### ISSUE THREAD

**Issue by xfreshy** [twitter/typeahead.js#238]
I have spaces in my datums.  For instance:

{ value:"apple",tokens:["apple"] }, { value:"great ape",tokens:["great ape"] }

When typing "great" the suggestion returns "great ape".  But when typing "great " (with a space), no suggestions are returned.

The main issue here is that I WANT the token to HAVE a space.  I don't want this behavior of typing a search like "ap" and getting "great ape" in the results.

**Comment by bitcity** [comment]
This seems like a basic issue with matching algorithm's ability to handle words with spaces. Could you please tag this for improvement.
