### ISSUE TITLE
Using jQuery .val() to set query won't trigger typeahead

### ISSUE THREAD

**Issue by bryantachen** [twitter/typeahead.js#247]
I was hoping to use .val() to set query and was expecting it'd behave the same as when someone pasted in the input field and further kickoff the typeahead mechanism but it seems like using .val() to set query doesn't do anything. 

In addition, it looks like when using .val() to set query, it initially will set the value in the input field but as soon as you blur away the input field the value gets cleared out. I am suspecting .val() did not set query correctly.

Am I overlooking something? Any insights will be greatly appreciated.

Thanks!

**Comment by BonBonSlick** [comment]
```
 jQuery#typeahead('setQuery', $oldSearchValue);

  28 |         let $oldSearchValue = typeaheadInputSelector.val();
  29 |         console.log(1);
> 30 |         jQuery#typeahead('setQuery', $oldSearchValue);
     |               ^
  31 |         // typeaheadInputSelector.typeahead('val', $oldSearchValue);
  32 |         // setTimeout(() => typeaheadInputSelector.typeahead.val($oldSearchValue), 1000);
  33 |         // typea
```
