### ISSUE TITLE
Submit form without typeahead:autocompleted

### ISSUE THREAD

**Issue by kristianthrane** [twitter/typeahead.js#255]
I don't know if this is somewhat the same question as #191, but I'm looking for a way to submit my form without the user input to always match suggestions.

On a .net page with the usual global form-element I'm trying to make typeahead.js work on a search-box without a submit-button. 

So if a user triggers a <code>typeahead:selected</code> I submit the form. And I want to do the same, if the user is using enter-key in the input text field:

``` javascript
jQuery(document).ready(function () {
  jQuery(".search-global")
    .typeahead(
    {
      remote: "/SearchType?Search=%QUERY",
      minLength: 2
    }
  )
  .bind("typeahead:selected", function () {
    jQuery("form").submit();
  });
});
```

But as far as I can see there's no public method or events for this?

**Comment by onetwopunch** [comment]
@jharding is there anything in Typeahead that would prevent a the enclosing form from submitting twice on the same page without refresh?

Everything is working fine using this method:

    $('#my-form').submit( function(e) {
      e.preventDefault();
      search();
    });

_Assuming `search` is an AJAX function that gets ALL results from the server and displays them on the page_

**Except** when I close hide the search results and try to search again, the `submit` is never called.

Any idea why this behavior might be happening?
