### ISSUE TITLE
Autocomplete when pressing Tab in same way it works when pressing Return

### ISSUE THREAD

**Issue by steswinbank** [twitter/typeahead.js#258]
Hi

Would it be possible to amend Typeahead so that a user can start typing, use the down-arrow to navigate to an option and then hit Tab to select that item? Currently this only works by pressing Return. Tab takes the focus to the next tabbable element leaving the text input with what the user typed in only. The desired behaviour would be for the selection of autocomplete option to take place if the user navigates to an option and then presses either Tab or Return.

Thanks
Ste

**Comment by Amerr** [comment]
+1

**Comment by imolorhe** [comment]
@jharding I think it should be configurable. I have a use case where I have two textboxes beside each other with the autocomplete. I don't want the first value to be selected when the person means to just go to the next textbox.
