### ISSUE TITLE
event to tell when user typed their own value vs selecting a suggestion

### ISSUE THREAD

**Issue by armhold** [twitter/typeahead.js#267]
Is there a way to get an event when the user "selects" the text that they have typed out, which is separate from the offered suggestions? I.e. user has typed 'apple', with provided suggestion 'applesauce'; however user really wants to submit simply 'apple'.  

Originally I tried using the 'change' event for this:

```
    }).on('typeahead:selected', function($e, datum) {  // suggestion selected
          console.log('selected: ' + datum['url']);
          window.location = datum['url'];
    }).on('change', function(e) {                     // user typed their own value
          value = $('input.search-input').val();
          window.location = '/search_path?search=' + encodeURIComponent(value);
    });
```

but unfortunately 'change' also seems to fire when the user selects from the drop-down, so if the user types 'apple' and then clicks 'applesauce' there's a kind of race condition where sometimes the form submits 'apple' and sometimes 'applesauce', depending on the speed of the remote.

**Comment by bwbecker** [comment]
I'm using v 11.1 (most recent as of this writing) and seeing the same kinds of things previous posters have complained about.  Contrary to what jharding wrote on Aug 15, 2014, I don't think v0.11 has solved this and the issues should be reopened.

**Comment by acrolink** [comment]
Thank you @rprieto .. Your solution works ..

**Comment by invious** [comment]
@rprieto `$input.data('ttView')` is undefined, how do i define datum now?
