### ISSUE TITLE
Accent folding

### ISSUE THREAD

**Issue by jelen07** [twitter/typeahead.js#271]
Hi!
First I want to say thanks for typeahead.js. It's really usefull!
Now about the issue - is here any option how use "accent folding" like jquery's autocomplete? http://jqueryui.com/autocomplete/#folding
If i had a string "süße Donut", it would be great if typeahead found it under "suse donut" too.
Like:

var accentMap = {
      "á": "a",
      "ö": "o",
      "ß": "s",
      "ü": "u"
};

Regards,
V.

**Comment by bquenin** [comment]
Works fine for me.

Here is a slightly less naive version where you don't instantiate a new RegExp each time:
```javascript
 var frMap = {
    'a': /[àáâ]/gi,
    'c': /[ç]/gi,
    'e': /[èéêë]/gi,
    'i': /[ï]/gi,
    'o': /[ô]/gi,
    'oe': /[œ]/gi,
    'u': /[ü]/gi
  };

  var normalize = function (str) {
    $.each(frMap, function (normalized, regex) {
      str = str.replace(regex, normalized);
    });
    return str;
  };

  var queryTokenizer = function (q) {
    var normalized = normalize(q);
    return Bloodhound.tokenizers.whitespace(normalized);
  };
```

**Comment by greenleafmedia** [comment]
This solution is very close to what I need, but I'm having the same troubles as @jelen07.  Let's say I have a list that has "Bühler" and "Butter".  The end result I'd like is that if I type in "Bu" both results would be returned.

When I run accent folding on the query, I wind up changing the query string to either "Bu" or "Bü" but not both.  Similarly, if I accent fold the datum I wind up with either ("Bühler" and "Bütter") or ("Buhler" and "Butter").

I think I'm close to the result I'd like.  In the queryTokenizer, I can accent fold the query and push it onto the token array.  This would give me "Bü" and "Bu" as my tokens.  However, bloodhound treats the token search as a ALL instead of the ANY I need, so with this approach I windup not getting any results returned.

Any suggestions on how to get a query to return all results that contain either "Bü" or "Bu"?  In the same vein, maybe there's a way to make Bloodhound search in more of an "OR" fashion than an "AND"?

**Comment by impulsief** [comment]
@greenleafmedia thank you so much it worked! 
but it shows only five results

**Comment by greenleafmedia** [comment]
@impulsief -  I think you may be setting your limit wrong.  It works for me when I set a limit in Bloodhound.

**Comment by impulsief** [comment]
@greenleafmedia yes, now it works thank you so much again :+1:

**Comment by PsychoJaps** [comment]
@greenleafmedia, thank you for sharing your code. I have slightly adapted your suggestion to the following, where I intended to proceed the search regardless of the special character while showing the keywords in my dropdown menu (and without the json part, in my case):

``` javascript
var charMap = {
        'a': /[àáâã]/gi,
        'c': /[ç]/gi,
        'e': /[èéêë]/gi,
        'i': /[ïí]/gi,
        'o': /[ôó]/gi,
        'oe': /[œ]/gi,
        'u': /[üú]/gi
    };

var normalize = function (str) {
    $.each(charMap, function (normalized, regex) {
        str = str.replace(regex, normalized);
    });
    return str;
};

var queryTokenizer = function (q) {
    var normalized = normalize(q);
    return Bloodhound.tokenizers.whitespace(normalized);
};

var foo_keywords = [
{name: 'foo1', keywords_query: normalize('foo1à, foo1ç, foo1ê'), keywords: 'foo1à, foo1ç, foo1ê', picture: '/img/foo1.png'},
{name: 'foo2', keywords_query: normalize('foo2à, foo2ç, foo2ê'), keywords: 'foo2à, foo2ç, foo2ê', picture: '/img/foo2.png'},
{name: 'foo3', keywords_query: normalize('foo3à, foo3ç, foo3ê'), keywords: 'foo3à, foo3ç, foo3ê', picture: '/img/foo3.png'}
];

var foo = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace(normalize('keywords_query')),
  queryTokenizer: queryTokenizer,
  local: foo_keywords
});

foo.initialize();

$('.typeahead').typeahead(
    {
        hint: true,
        highlight: true,
        minLength: 1,
    },
    {
        name: 'foo',
        displayKey: 'name',
        source: foo.ttAdapter(),
        templates: {
            suggestion: function(el){return '<div style=\"display:table;\"><div style=\"display:table-cell;text-align:left;margin:0;width:100px;\"><img src="'+el.picture+'" style=\'width:100px;height:auto;\'/></div><div style=\"display:table-cell;text-align:left;margin:0;padding:10px;vertical-align:top;">'+el.name+'<br><font style=\"font-size:0.6em;color:#7b7b7b;\">'+el.keywords+'</font></div></div>'}
        }
    }
);
```

I am sharing my post should someone find it useful too.

**Comment by sorenwiz** [comment]
You can do something like this if you use prefetch
```
    var zips = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('short_name'),
        queryTokenizer: queryTokenizer,
        prefetch: {
            url: '/api/get_zips.json',
            cache: !window.is_development,
            transform: function (obj) {
                return obj.map(
                    function (x) {
                        return {short_name: normalize(x.short_name), url_param: x.url_param}
                    }
                )
            }
        }
    });
