### ISSUE TITLE
Input value blank on blur

### ISSUE THREAD

**Issue by flyingeek** [twitter/typeahead.js#28]
Go to the example demo page, 

$('input[placeholder="countries"]').val('France').click().blur(); the input value is now blank.

If you set a value, you would like to keep it no ? (I would)

Same problem if the input contains a value before becoming a typeahead input.

**Comment by bcackerman** [comment]
I'm curious how to implement this as well.  When I autofill a typeahead enabled field, if a user clicks on that field, I don't want the value to disappear.

**Comment by bcackerman** [comment]
Figured it out: http://stackoverflow.com/questions/16974783/typeahead-js-on-blur-event

**Comment by mehrdadmehralian** [comment]
fre

**Comment by huglester** [comment]
I don't really get how it should be working?
so I have something like that:

``` javascript
remote: {
            wildcard: '%QUERY',
            url: '/api/search?q=%QUERY',
}
```

Now, when I see the results. I can navigate threw them using up/down.
And when I press down (and I am leaving input field), I get that input emptied.
Any way to leave the input with a query?

Thank you

**Comment by HamsterofDeath** [comment]
can someone give a simple example of what do to to prevent the field from getting emptied by a blur event?
i found no clear answer. even the stackoverflow question has none

**Comment by huglester** [comment]
@HamsterofDeath not me ;(

**Comment by HamsterofDeath** [comment]
i found a working hack

```
var myTypeAhead = ...
myTypeAhead.unbind("blur") <- this gets rid of the original handler(s)
myTypeAhead.on("blur", function(evt) {$("#elementId").typeahead("close")}) // <- this will make sure the popup is still closed properly
```

**Comment by lorenzosanzari** [comment]
To avoid the blur field reset problem, I changed the plugin code (v. 0.11.1) at row 1487:
          this.setInputValue(this.query);

to: 


var val = (this.query && this.query.length > 0) ? this.query : this.getInputValue();
this.setInputValue(val);`

I hope this will help someone! :-)

**Comment by ryandaugherty7** [comment]
@HamsterofDeath thanks! Your answer was a huge help to me and worked like a charm on my older 0.10.5 version of typeahead (did not want to adjust the CSS to upgrade to the latest). I just did the following after initializing the typeahead: 

```
  $('#search-query').unbind("blur");
  $('#search-query').on("blur", function(evt) {$('#search-query').typeahead("close")});
```

**Comment by HamsterofDeath** [comment]
always happy to help

 
 

Gesendet: Freitag, 30. Juni 2023 um 18:43 Uhr
Von: "ryandaugherty7" ***@***.***>
An: "twitter/typeahead.js" ***@***.***>
Cc: "HamsterofDeath" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [twitter/typeahead.js] Input value blank on blur (#28)


 

@HamsterofDeath thanks! Your answer was a huge help to me and worked like a charm on my older 0.10.5 version of typeahead (did not want to adjust the CSS to upgrade to the latest). I just did the following after initializing the typeahead:

  $('#search-query').unbind("blur");
  $('#search-query').on("blur", function(evt) {$('#search-query').typeahead("close")});
