### ISSUE TITLE
Cloning a typeahead element using JQuery .clone()

### ISSUE THREAD

**Issue by palintropos** [twitter/typeahead.js#287]
I've got an existing HTML form with jQuery enhancements that uses .clone() in a couple of places to insert or remove form inputs. I'm trying to integrate it with typeahead.js 0.9.2 now, and a cloned typeahead doesn't seem to be functional. I haven't figured out what to change to make this work, or pinpointed what causes it to malfunction, and hoped maybe the community can help.

I have put together the following simplified fiddle in order to both show what I'm trying to do, and also to demonstrate the way .clone() affects the typeahead plugin:

http://jsfiddle.net/AzSgy/8/

If there is another way that I could be doing this besides using .clone(), or you have any suggested improvements to my methods, I am more than happy to listen to these types of solutions as well. Thanks in advance.

**Comment by robbprescott** [comment]
Thanks so much @palintropos, this tip still works!
