### ISSUE TITLE
Adds elements with class tt-suggestion twice

### ISSUE THREAD

**Issue by alyraz** [twitter/typeahead.js#298]
When user starts typing, often certain suggestions appear twice. It seems the DOM is creating 2 divs with class="tt-suggestions." It seems this issue was brought up a couple months ago but doesn't seem to be fixed ( http://issues.liferay.com/browse/AUI-846 )

![screen shot 2013-06-20 at 2 25 43 pm](https://f.cloud.github.com/assets/2508259/684115/025a04e6-d9f0-11e2-9de2-c610052e963f.png)

**Comment by deveshkrsingh** [comment]
I am facing similar issue that i have written here(http://stackoverflow.com/questions/35320812/duplicate-records-coming-in-typeahead-search),any help?

**Comment by namtab00** [comment]
@deveshkrsingh 
This repo seems abandoned.. some kind souls continue maintaing it here: https://github.com/corejavascript/typeahead.js
I'd say the useful thing to do is sending pull requests and issues there.
