### ISSUE TITLE
Example of typeahead:selected event

### ISSUE THREAD

**Issue by andy3rdworld** [twitter/typeahead.js#300]
For anyone interested until an example is added to documentation for custom events...

Assuming there's an input on your page called 'search_input':

``` javascript

$('#search_input').bind('typeahead:selected', function(obj, datum, name) {      
        alert(JSON.stringify(obj)); // object
        // outputs, e.g., {"type":"typeahead:selected","timeStamp":1371822938628,"jQuery19105037956037711017":true,"isTrigger":true,"namespace":"","namespace_re":null,"target":{"jQuery19105037956037711017":46},"delegateTarget":{"jQuery19105037956037711017":46},"currentTarget":
        alert(JSON.stringify(datum)); // contains datum value, tokens and custom fields
        // outputs, e.g., {"redirect_url":"http://localhost/test/topic/test_topic","image_url":"http://localhost/test/upload/images/t_FWnYhhqd.jpg","description":"A test description","value":"A test value","tokens":["A","test","value"]}
        // in this case I created custom fields called 'redirect_url', 'image_url', 'description'   

        alert(JSON.stringify(name)); // contains dataset name
        // outputs, e.g., "my_dataset"

});
```

https://github.com/twitter/typeahead.js#custom-events

**Comment by LukasCamera** [comment]
@HiteshDhanwani There's already an issue #798. Here's a working [fiddle](http://jsfiddle.net/5xxYq/52/), but I couldn't get it working using Bloodhound as engine.

**Comment by andrespipe90** [comment]
Excellent, thanks man !! :) :100:

**Comment by jamesrichards** [comment]
Exactly what I was looking for - why is this not in the docs under custom events? There's no example available.

**Comment by allesan** [comment]
Am I wrong or this is not working anymore?

**Comment by aroraumang** [comment]
Thanks man.

**Comment by fertobar** [comment]
+1

**Comment by mtzmedia** [comment]
Since the "overhaul" of typeahead, typeahead:select no longer defines the dataset name. Anyone know how to get the dataset on the select event?

**Comment by ZaneCEO** [comment]
I was banging my head against the wall so... please note that now the event is "typeahead:select" and NO LONGER "select**ed**".. after this, the original example still works and is the correct way to do it, thanks!

**Comment by oshihirii** [comment]
I am getting:  `TypeError: cyclic object value` from:

```
.on('typeahead:selected', function(obj, datum, name) { 
console.log(JSON.stringify(obj));
console.log(JSON.stringify(datum));
console.log(JSON.stringify(name));
```

`typeahead.bundle.min.js` at `v0.10.5`.

**Comment by DMeganoski** [comment]
+1 to @mtzmedia question. I need to determine which dataset the selection belongs to. I can't seem to find this information anywhere. I got my hopes up seeing this example, only to realize this is an old thread and the name is no longer an argument. Anyone know of another way?

**Comment by mlosavio** [comment]
Hi,
I'm trying to use this hint but without success. The typeahead selector works perfectly (it's a multi-dataset typeahead) but no events are fired.

The following is the HTML part:

```
<div id="namelist">
		  <input class="typeahead" id="searchinput" type="text" placeholder=" search a name..." style="padding:3px">
		</div>
```
and this is the javascript part to bind the selected event but it doesn't fire anything.

```
$('#namelist .typeahead').bind('typeahead:selected', function (obj, datum, name) {
			alert(JSON.stringify(obj)); 
			alert(JSON.stringify(datum)); 
			alert(JSON.stringify(name)); 
		});
```
I have also tried to reference directly the input:

```
$('#searchinput').bind('typeahead:selected', function (obj, datum, name) {
			alert(JSON.stringify(obj)); 
			alert(JSON.stringify(datum)); 
			alert(JSON.stringify(name)); 
		});
```
Nothing.

Any help?

thanks.

**Comment by DMeganoski** [comment]
@mlosavio see ZaneCEO's comment above.

**Comment by mlosavio** [comment]
nothing, it doesn't work. 
I'm sure I'm missing something...
Is there anyone who could post a full example please?

thanks.

**Comment by ivanchaer** [comment]
Try:

- focus.bootstrap3Typeahead
- blur.bootstrap3Typeahead
- keypress.bootstrap3Typeahead
- propertychange.bootstrap3Typeahead input.bootstrap3Typeahead
- keyup.bootstrap3Typeahead

Like:

```
$('input.typeahead').typeahead({...}).bind('keyup.bootstrap3Typeahead', function(event, dataset_selected_Item, dataset_name) {
    console.log('keyup');
  });
```

**Comment by joshuapinter** [comment]
NOTE: In the latest version of typeahead, `typeahead:selected` has been changed to `typeahead:select` and now only two params are passed instead of three: `( event, selected_object )`

**Comment by mrimran** [comment]
What worked for me is below:

```
$('#someinput').typeahead({ 
    source: ['test1', 'test2'], 
    afterSelect: function (item) {
        // do what is needed with item
        //and then, for example ,focus on some other control
        $("#someelementID").focus();
    }
});
```

The solution was taken from https://www.py4u.net/discuss/907420
