### ISSUE TITLE
key "Enter" function default action

### ISSUE THREAD

**Issue by klekle** [twitter/typeahead.js#332]
Hello, I read some issues here and on the internet and people say with this plugin when the user hits enter key while the input is focused it should autocomplete it, but according to the demo page this is not the default behavior and hitting enter has no effect.

I tested the page http://twitter.github.io/typeahead.js/examples/ and in the first field i typed "bra" the only option is "Brazil" so I hit enter hoping it would fill it for me and trigger typeahead:selected for example.

Im using chrome lastest.

Is this correct? or it should work with the enter key?

if this is not the default behavior, could you please point me in the right direction on how to make this work? (hitting enter and choosing the current suggested option).

Thx! great plugin

**Comment by acellary** [comment]
You may change line
this.select($selectable) && $e.preventDefault();
to
this.select($selectable);
By doing that you won't disable default Enter key function (might be sending a form)

**Comment by bpartridge** [comment]
The internal API has changed with 0.11.1. The following behavior lets you hit Enter once while the menu is open to select the top match, then (since the menu is now closed since you have an exact match, under standard tokenization assumptions), if you hit Enter again it allows you to submit a form.

5 years is a long time :)

```
$('.thing-you-called-typeahead-on').on('keypress', function(evt) {
      if (evt.which == 13 /* ENTER */) {
        const typeahead = $(this).data().ttTypeahead;
        const hintText = typeahead.input.$hint.val();
        const menu = typeahead.menu;
        const sel = menu.getActiveSelectable() || menu.getTopSelectable();
        if (menu.isOpen()) {
          menu.trigger('selectableClicked', sel);
          evt.preventDefault();
        }
      }
    });
```
