### ISSUE TITLE
Ability to use WebSocket as transport for remote data sources?

### ISSUE THREAD

**Issue by julien-c** [twitter/typeahead.js#338]
That would speed up things quite a bit in the case of remote data sources. 

Has anyone tried swapping Typeahead's current transport layer with a WebSocket based one?

**Comment by vongillern** [comment]
wanted to document for prosterity... this has been driving me nuts. I'm on latest version (v0.11.1), the transport method now DOES NOT take an "o" parameter. just url (which is actually an object, not a string, the actual url is a field on it)

``` javascript
var source = new Bloodhound({
  remote: {
    url: '%QUERY',
    transport: function(url, onSuccess, onError) {
    }
  }
});
```

**Comment by MattNguyen** [comment]
Should this be documented as a configuration option in https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote?
