### ISSUE TITLE
No event triggered on selection via click?

### ISSUE THREAD

**Issue by lwansbrough** [twitter/typeahead.js#341]
Trying to listen for an event with `.on('typeahead:selected typeahead:autocompleted',...)`  but it only gets triggered when I use my arrow keys and hit enter, not via click. What gives, is this intentional? If so, how do I determine the datum whenever the user changes it?

**Comment by sashtur** [comment]
The item selected via the click shows up in the input box, but reverts to the 1st item in the drop down once you tab out of it.
I have this issue only for dynamically added textbox having typeahead class.
For statically added box, it works fine.

**Comment by sashtur** [comment]
I have this issue only for dynamically added textbox having typeahead class.
For statically added box, it works fine.

**Comment by fredhuds** [comment]
@sashtur I have the same problem.
