### ISSUE TITLE
beforeSend modify URL - cache issue

### ISSUE THREAD

**Issue by calexo** [twitter/typeahead.js#365]
Hi,

I'm trying to make a typeahead field in which suggestions depend on a former Select field.
I use beforeSend to modify URL and adding the Select value.
It does work, but when I go back and modify the 1st Select, it seems to be kept in cache, and the query is not runned again. Event with cache: false
ie.
  I set country 1
  I type a in typeahead, I have A1, AB1, AC1 as suggestions.
  I set country 2, expecting A2, AB2 in my typeahead.
  I type a in typeahead. No query is ran, and I still get A1 AB1 and AC1...

remote: {
        url: './json/getregions.json?query=%QUERY',
        cache: false,
        beforeSend: function(jqXhr, settings) {
          settings.url = settings.url + '&country=' + country;
        }
      }

I'm not sure that's very clear, thanks for your help !

**Comment by Chiragbodana** [comment]
var myFunction = function(el){
  var ct = el;
  // console.log($("#city").val());
  var arealist = new Bloodhound({
    datumTokenizer: function(datum){
      return Bloodhound.tokenizers.whitespace(datum.value)
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: 'http://localhost/scpropertyee/public/api/',
      filter: function(data){
        return $.map(data, function(area){
          return { value: area }; });
      }
    },
    replace: function(url, ct){
      return url + 'arealist?city=' + ct ;
    }

    });
    arealist.initialize();
    var dataset = {
          source: arealist.ttAdapter(),
      }
}

$('#area').each(function () {
  var select = $('#city').siblings('select');
  $(this).tagsinput({
    name: 'area_first',
        displayKey: 'area',
        valueKey: 'area'
  }, myFunction(select));
});

plz check this
