### ISSUE TITLE
Bootstrap 3 broken style

### ISSUE THREAD

**Issue by Stajor** [twitter/typeahead.js#378]
Changed css in bootstrap 3
Before: http://d.pr/i/44ma
After: http://d.pr/i/dv1W

**Comment by yogesh333** [comment]
![rooforders myaccount](https://cloud.githubusercontent.com/assets/10370467/6682459/181e9d84-cc9f-11e4-8265-6d6ab0fa3e0c.png)
Hi this is working fine in firefox but not in chrome & IE ...could you please suggest me something?

**Comment by yogesh333** [comment]
even if place holder is "End Date " in second text box. it is showing as above "mm/dd/yyyy" in chrome.

**Comment by monoblaine** [comment]
@yogesh333 This has nothing to do with typeahead.js library. It appears you are trying to use the "placeholder" attribute on an input type="date" field. According [to this link](https://html.spec.whatwg.org/multipage/forms.html#date-state-%28type=date%29:do-not-apply), using placeholder attributes in date fields is not supported.

**Comment by yogesh333** [comment]
could you please tell me about the gap between glyphicon & textbox as given in above picture, which appears only in chrome but for other browser it is working fine.
