### ISSUE TITLE
Set custom header at every typing

### ISSUE THREAD

**Issue by Kirua88** [twitter/typeahead.js#384]
Hi,

How can i set a custom header ?
i want to insert a a number which change on every typing.

name: 'contacts',
remote: {
       url: 'json.aspx?id=%QUERY',
       filter: function (parsedResponse) {
              var dataset = [];
               for (i = 0; i < parsedResponse.length; i++) {
                    dataset.push({
                          name: 'contacts',
                          id: parsedResponse[i].id,
                          value: parsedResponse[i].value,
                          tokens: [parsedResponse[i].id, parsedResponse[i].value]
                      });
               }
               return dataset;
         },
         beforeSend: function(jqXhr, settings){
              PageMethods.CountContacts(document.getElementById("tbox").value,   OnSuccess,OnError);  
               function OnSuccess(response) {
                   // SET HEADERS
                }
        }
},
header: '<h3class="league-name">CONTACTS ' + document.getElementById("HiddenField1").value + ' résultats</h3>',

**Comment by gerryhall** [comment]
This should be possible by using a template for the header and a Handlebars helper function.
