### ISSUE TITLE
scrollbar support

### ISSUE THREAD

**Issue by darrendb** [twitter/typeahead.js#409]
Would love to see something implemented to this latest version of typeahead allowing scrollbar support. Useful for either the use case where the suggestions are numerous or when gui design calls for a maxHeight on the dropdown that limits the number of items visible.

https://github.com/tgirardi/twitter-bootstrap-typeahead/tree/scrollbar-support

**Comment by Chealer** [comment]
For what it's worth, ngx-bootstrap (for Angular) features scrolling options: https://valor-software.com/ngx-bootstrap/#/typeahead#scrollable
