### ISSUE TITLE
how to re-initialize typeahead

### ISSUE THREAD

**Issue by barsh** [twitter/typeahead.js#41]
What is the recommended approach for re-initializing typeahead to change a prefetch, a dataset, or some other property?

**Comment by rushdy20** [comment]
hi is there a i am using * typeahead.js 0.10.5 is there a way i can change the typeahead source and template on runtime?
basically i got a drop down and from that drop to select the options. and the source and the template needs to change according to the option selected

**Comment by JulesMarcus** [comment]
@rushdy20 Did you ever find a way to do this? I have the exact same problem. Right now I initialize the typeahead in a focusOut event from an other input field, but it isn't working that well.

**Comment by vickyveera10** [comment]
im using typehead in item search in text box (get value from the localstorage) after add new data it's stored in to local storage this new data came in localstorage which i use localstorage value alert. but this typehead not coming that localstorasge new data.[Please kindly help me how to get local storage new added data get it in to the typehead prefetch]

**Comment by vickyveera10** [comment]
im using typehead in item search in text box (get value from the localstorage) after add new data it's stored in to local storage this new data came in localstorage which i use localstorage value alert. but this typehead not camining that localstorasge new data.[Please kindly help me how to get local storage new added data get it in to the typehead prefetch]

**Comment by pierodc** [comment]
How can I have 2 or more autofill fields with typehead that calls diferents data arrays for example, one for city and other for county?
