### ISSUE TITLE
Typeahead cuts my JSON result

### ISSUE THREAD

**Issue by Regaddi** [twitter/typeahead.js#416]
Hi folks!

I'm currently migrating a project from Bootstrap 2 to Bootstrap 3.
Since I used the old Bootstrap Typeahead I followed the suggestion and went over to Twitter Typeahead.

I'm just experiencing a strange problem:

I fetch data from a remote URL (the backend) where the typed string is evaluated and the server returns a JSON array containing JSON objects, which have the same properties.

There are 3 important properties: id, name and path.

I use the path inside the template like `{{{path}}}` and the name is the valueKey. The id is set as a data-attribute on `typeahead:selected`.

Now it is possible, that the name can be identical, but the path and id differ. But typeahead only shows me the first item inside the suggestion list.

Example:

Server response:

```
[{
    id: 1,
    name: 'Foo',
    path: 'Problems > Foo'
},{
    id: 23,
    name: 'Foo',
    path: 'Food > Foo'
}]
```

Suggestion list:

```
Problems > Foo
```

Do you have a workaround for me?

**Comment by ShrinivasMese** [comment]
do you have any fix for typeahead.js 0.9.3?
 or can you suggest me any other solution.
