### ISSUE TITLE
input autofocus attribute is not working

### ISSUE THREAD

**Issue by Nerian** [twitter/typeahead.js#444]
Hi,

I have this input field that I use with typeahead. It has an autofocus attribute that instructs the browser to focus on it. That worked before adding typeahead. After adding typeahead, that is no longer working.
 
````html
<input autofocus="autofocus" class="string required span6" 
    data-behavior="typeahead" 
    data-typeahead="products" id="payment_detail" name="payment[detail]" 
    size="50" type="text">
````

**Comment by toddmo** [comment]
This is still an issue. @jharding, Why was it closed?

**Comment by fletchowns** [comment]
@toddmo I don't think this project is maintained anymore, see #1618
