### ISSUE TITLE
remote.beforeSend not sending POST data

### ISSUE THREAD

**Issue by gavinheasley** [twitter/typeahead.js#448]
Our intention is to supplement our typeahead with data from an elasticsearch query.  I've attempted to set the settings.data in the beforeSend function, but when I get the results, as well as inspect the network traffic (both Chrome and FF) the request payload is not being set.

The beforeSend is functioning correctly when I set the type, but somewhere the data is being lost.  Here is example code exercising my issue http://jsfiddle.net/75mCa/2/   Also note that the expected behavior of POSTing to httpbin.org is that they will simply return your request data wrapped in a 'data' object.  I've also attached a screen shot from Chome debugging tools which shows the lack of the request payload.  The filter function is also expected to fail as none of the request data is submitted and thus added to the response.

Thanks
![network-headers](https://f.cloud.github.com/assets/2986132/1158625/aa3e3238-1fb7-11e3-82f6-8fe34a0f8365.png)

**Comment by mansonkibe** [comment]
You need to modify the before beforeSend: function(xhr,settings)

 remote:{
                 url: "<?php echo base_url('hospital/hospitals'); ?>",
                  beforeSend: function(xhr,settings){
                        xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
                        settings.type = 'POST';
                        settings.hasContent = true;
                        settings.data =$.param({search: $('#hospital_code').val(), column: 'code'});
                        $('.Typeahead-spinner').css('display', 'block');
                    },
                  success: function(data) {
                    $('.Typeahead-spinner').hide();
                    result = data;
                  },
                  complete: function(xhr){
                   $('.Typeahead-spinner').css('display', 'none');
                  }
            },
