### ISSUE TITLE
Request on 0.10: Add a class to the first suggestion if autoselect is true

### ISSUE THREAD

**Issue by chibicode** [twitter/typeahead.js#483]
Hi, thank you for this great plugin :) I've tried out the `integration-0.10.0` branch and love the new APIs. I have one request on `autoselect` (related to #332 ): would it be possible to:

* Add a `tt-autoselect` class to the `tt-suggest` element that will be autoselected, just like `.tt-cursor`.
* But ensure that `tt-autoselect` is only applied when the user has not manually selected anything. In other words, if the user mouses over some other `.tt-suggest` element, then `.tt-autoselect` should be removed from the first element until the user selects nothing again.

This way, even if `hint` is `false`, I'll be able to use CSS to signal users which suggestion will be autoselected upon hitting enter.

Since the first element will always be auto-selected, I thought of using `.tt-suggest:first-child` in my CSS, but this doesn't work when there are more than one sections.

**Comment by WillemStaels** [comment]
Change the getDatumForSuggestion function to this one below when using autocomplete to auto-select the first item.

```javascript
getDatumForSuggestion: function getDatumForSuggestion($el) {
                var datum = null;
                if ($el.length) {
	                if(!this._getCursor().length){
		              this._setCursor(this._getSuggestions().first(),true);
		            }
                    datum = {
                        raw: Dataset.extractDatum($el),
                        value: Dataset.extractValue($el),
                        datasetName: Dataset.extractDatasetName($el)
                    };
                }
                return datum;
            },
```

**Comment by PierBover** [comment]
Can someone post an example on how to implement the `getDatumForSuggestion` function?

**Comment by galenwilk** [comment]
@PierBover just make sure you've enabled the `autoselect: true` option when initializing your typeahead. Then in the `typeahead.js` source replace the existing `getDatumForSuggestion` function with the one above.

**Comment by PierBover** [comment]
Ah thanks @galenwilk I thought the function was some callback
