### ISSUE TITLE
AJAX Post Calls

### ISSUE THREAD

**Issue by jasonterando** [twitter/typeahead.js#542]
Hi, after a lot of messing about I was almost able to get post calls working for remote data, but not while still maintaining the caching of previous request, since the search gets embedded into the query string, and a posted call to the server does not include the query string.

I branched the project and made some changes that allow me to do a posted remote call just by doing the following:

```
        $('#Search').typeahead({
            valueKey: 'MyKey',
            limit: 20,
            remote: {
                url: '/DoSearch',
                type: 'post',
                timeout: 15000,
                limit: 100,
                data: {
                    Criteria: '%QUERY'
                }
            },
            template: "{{blah}}",
            engine: TypeaheadEngine
        }).on('typeahead:selected', function (obj, datum, name) {
            DoSomething(datum);
        });
```

I also added a public method called flushCache to the transport class to clear out any cached results.

I've submitted a pull request "remote-post".  As will be obvious, this is my first attempt at a git-hosted submission, so feel free to let me know anything I need to differently.

Thanks

**Comment by shadowdogg** [comment]
@m-ryan can you please provide your full code, i am struggling to understand how yours works
