### ISSUE TITLE
Using Mustache as template engine (now that it does not have a compile method)

### ISSUE THREAD

**Issue by liquidscorpio** [twitter/typeahead.js#597]
The examples given in #331 no longer work because mustache has removed compile method. (Refer: https://github.com/janl/mustache.js/issues/346)

The browser now reports:

``` javascript
Uncaught TypeError: Object ... has no method 'compile' 
```

**Comment by jpdevries** [comment]
:+1: thanks @kzap

**Comment by tchoulihan** [comment]
+1 this worked for me too, thanks @kzap

**Comment by antonioaltamura** [comment]
very thanks @kzap
