### ISSUE TITLE
OnClear

### ISSUE THREAD

**Issue by katlimruiz** [twitter/typeahead.js#607]
Hi
A good enh would be to have a method called onClear or something like this so when the user clears the content, we can listen to this event so we can clear the other fields.

For example, having a productCode and productId, using selected event, I can assign the productId, but there is no way to clear it when productCode is cleared.

**Comment by bryannielsen** [comment]
+1

**Comment by leidegre** [comment]
You can subscribe to the `typeahead:change` event, when `val === ''` the selection was cleared but it does not always fire. If you press enter before blur you don't get the event at all. Which surly must be bug of some kind?

**Comment by leidegre** [comment]
You can do this by simply subscribing to the `typeahead:change` event. It will fire when the value is cleared and you check for this like so

```
ttPlugIn
  .on('typeahead:change', function(e, val) {
    if (!val) {
    // Selection cleared
    callback(e, null)
  }
```
