### ISSUE TITLE
Remote data is not used

### ISSUE THREAD

**Issue by sergeychernyshev** [twitter/typeahead.js#638]
I'm trying to implement remote-only typeahead feature and Bloodhound is just simply dropping my remote data.

I initialize bloodhoud like this:

```
var engine = new Bloodhound({
        datumTokenizer: function(d) {
                console.log('Datum: ' + d);
                return d.title;
        },
        queryTokenizer: function(q) {
                return q;
        },
        local: [{title: 'Ringo Starr'}, {title: 'Paul McCartney'}],
        remote: '/typeahead.php?q=%QUERY'
});
```

Then use it as part of typeahead:

```
engine.initialize().done(function() {
        field.typeahead({
                autoselect: true
        }, {
                source: engine.ttAdapter(),
                displayKey: 'title',
        });
});
```

where field is input field element.

So local suggestions show up all-right, and requests are also made to the server, but data returned from the server is not used at all.

I also don't see any calls to my datumTokenizer callback (not on local nor on remote calls).

Here's the response from typeahead endpoint for /typeahead.php?q=John (hardcoded boilerplate for now).

```
[
    {
        title: 'Ringo Starr'
    },
    {
        title: 'John Lennon'
    },
    {
        title: 'Paul McCartney'
    },
    {
        title: 'George Harrison'
    }
]
```

What am I doing wrong?

Remotes example is also broken (issue #637) which makes it hard to see what is the correct use of Bloodhound.

Would really appreciate any help.

**Comment by jbardu** [comment]
I second the above comment. I know in established systems json is correct. But when you're knocking something quickly to test the plug-in in your site, with your data, and make a tiny json mistake, there is no information even in the console that you screwed up. In the code, in the ajax callback, it is just err ? [] : ....(what you want to get executed but never does)...

Not returning anything at all is very mysterious. So many things to check! So much time wasted.
