### ISSUE TITLE
General callback for when typeahead is fully initialized and ready

### ISSUE THREAD

**Issue by seiz** [twitter/typeahead.js#64]
I'd appreciate a general callback so i can find out when typeahead is initialized and done prefetching etc. 

For example:

``` javascript
$("input").typeahead({
  name: 'description', 
  prefetch: 'search.json',
  limit: 1000,
  callback: function(){
    alert("Typeahead is ready for you!");
  }
});
```

**Comment by hiiwave** [comment]
Excuse me, could I ask what's the event name? I could not find it on the document.
