### ISSUE TITLE
Unwanted behaviour when using $('.typeahead').typeahead('val', myVal);

### ISSUE THREAD

**Issue by 8enSmith** [twitter/typeahead.js#646]
Whilst answering a [StackOverflow question](http://stackoverflow.com/questions/21586443/have-typeahead-js-output-into-multiple-text-boxes/21591540#21591540) I found what I deem to be undesirable behaviour with the "$('.typeahead').typeahead('val', myVal);" function.

When this function is called it causes "myVal" to be correctly inserted, however it causes the suggestion box to also appear. I think users will expect this function to just populate the typeahead control (i.e. just like a call to $('.typeahead').val(myVal);)).

See this [jsFiddle](http://jsfiddle.net/Fresh/kLLCy/) and uncomment the call to typeahead('val', ...) to recreate the issue.

Is this indeed an issue or is it expected behaviour?

**Comment by yanickrochon** [comment]
I am unsure how this behavior was resolved. I just installed this component and used `.typeahead('val', newValue);` to manually set the field's value and the suggestion menu opens.

Right now, I resolve this using 

```
el.typeahead('val', newValue).one('typeahead:open', function () {
  el.typeahead('close');
});
```

**Comment by yanickrochon** [comment]
Also, even if the suggestion list is closed, I find that setting some items cause the autocomplete to show a hint when it's not supposed to.

For example :

``` js
el.typeahead('val', 'foo');
```

Will set the correct value `"foo"` inside my field (where my datasource `display` is set to return `item.name`), but if I have a remote item like `{ name: 'foobar' }` then I'll see `"foobar"` in my field as "suggestion" even though the actual value properly set is `"foo"`.

How do I set a value without triggering a search, suggesitons, and autocomplete?

**Comment by yanickrochon** [comment]
This should be easy to solve if I could pass [`silent`](https://github.com/twitter/typeahead.js/blob/master/src/typeahead/input.js#L143) to the [`setVal`](https://github.com/twitter/typeahead.js/blob/master/src/typeahead/typeahead.js#L338) function

```
el.typeahead('val', 'foo', true);
```

**Comment by yanickrochon** [comment]
Well, instead of using `val`, I'm using this and it works as expected.

```
el.data('ttTypeahead').input.setQuery('foo', true);
```

**Comment by danielsedlacek** [comment]
Also the documentation could be less ambiguous, it is not clear it the typeahead ("val",val) will only set the value or trigger the search too.
