### ISSUE TITLE
Trigger custom events

### ISSUE THREAD

**Issue by jharding** [twitter/typeahead.js#68]
There's a handful of issues asking for something along the lines of a "selection callback". While I agree this is necessary, I don't think adding an option like `onSelection` is the best way to go about it. Instead, I think triggering custom events on the typeahead input is the way to go. It's a more extensible approach and it won't pollute the options hash.

I'm creating this ticket to start brainstorming what events we need to trigger. The only 2 I can think of right now are:
- suggestion selected (#22)
- prefetched data loaded (#64) 

If there's anything else you'd like an event triggered for, leave a comment in this issue.

**Comment by driptamine** [comment]
Hey, @r4vi , @jharding , @ankane
 I'll be grateful, if you can reply! Can you explain:
  I use **searchkick** (backend Ruby On Rails) with **typeahead** and don't know a place where to add things like:

```ruby
<% user.avatar %> 
<% user.followers.count %>
``` 
![image](https://cloud.githubusercontent.com/assets/18751336/22369515/69656958-e4b6-11e6-863a-0523c4a59ff2.jpg)

I want to develop autocomplete searching with displaying user's avatar like above!

**Comment by joshuaedwardcrowe** [comment]
You need to place them in the objects that are passed to typeahead (or Bloodhound if you're using that).
