### ISSUE TITLE
no result function

### ISSUE THREAD

**Issue by reinvanleirsberghe** [twitter/typeahead.js#682]
In desperate need of a noresult-function.
The 'empty'-template is not what I'm looking for.

When there are no results, I would like to go to a function instead of just showing it on the screen that there are no results.

Thanks!

**Comment by unmeshgit** [comment]
Another way to do so is on the server side (assuming you are making an ajax call to get the results), if you find there are no matching results for the term 'abc', add a new row to the results saying e.g. "No matches found for 'abc'. Create new". This will get displayed in the dropdown and when you select it - your onClick callback will get called. Its important to include the orignal query string in the new row you add for it to show in the dropdown.
