### ISSUE TITLE
typeahead destroy does not seem to remove registered event handlers

### ISSUE THREAD

**Issue by jweyrich** [twitter/typeahead.js#691]
Steps to reproduce:
1. Have a single input field for search;
2. Have 2 buttons. The buttons should change the behavior of the input field to perform different searches (typeaheads). This is done with something along these lines:
   
   $('input').typeahead('destroy');
   $('input').typeahead(null, { REDACTED FOR BREVITY })
       .on('typeahead:selected', function(event, suggestion, datasetName) {
           console.log('typeahead:selected for ' + datasetName);
       }).on('typeahead:autocompleted', function(event, suggestion, datasetName) {
           console.log('typeahead:autocompleted for ' + datasetName);
       });
3. Click the 1st button, type in a search query, click on a suggestion;
4. Click the 2nd button, type in a search query, click on a suggestion;
5. Click the 1st button again, type in a search query, click on a suggestion;

This is triggering spurious events (`typeahead:selected` and `typeahead:autocompleted`) on the previously registered targets. They seem to accumulate in each call to `typeahead()`.

It seems to be a bug in the `destroy` handler, which does not seem to remove the registered event handlers from the input element.

I did workaround this by manually calling `$('input').off()` after `destroy`.

**Comment by jweyrich** [comment]
Your assumption is correct. We register these handlers with '.on('typeahead:...')'. Without looking at its source-code I don't know what to expect from 'destroy' since typeahead seems to wrap the target element (or I'm terribly wrong).
So, are users responsible for removing these handlers before/after a 'destroy'? I did expect 'destroy' to remove all event handlers as well. If my expectation sounds weird, I'm okay with manually removing them. Does it deserve a note in the docs, or is it a common assumption?

**Comment by moahammadalt** [comment]
if you are creating the event multiple times then you should destroy it before create it like that
.off('typeahead:selected').on('typeahead:selected', function($e, book){  .....  });
