### ISSUE TITLE
Clicking vertical scrollbar for suggestions in IE closes menu

### ISSUE THREAD

**Issue by henkli** [twitter/typeahead.js#705]
If the suggestions menu has a vertical scrollbar, e.g. has a max-width set, clicking the scrollbar closes the typeahead menu in Internet Explorer. The scroll bar works fine in Firefox and Chrome.

Affects at least IE8, IE11 (probably IE9 and IE10 as well).
IE8: Clicking scroll up/down icons works fine, but dragging the "scroll element" does not.
IE11: Clicking anywhere on the scrollbar closes the menu.
Tested using typeahead.js 0.10.1

Example fiddle: http://jsfiddle.net/r2a2G/

**Comment by DealerCorp** [comment]
still happening

**Comment by chrisbuckmaster** [comment]
I'm not too sure why this is closed as I still experience this issue? Is there a fix for this? It even happens on the main examples page for the Scrollable Dropdown Menu.

**Comment by worthy7** [comment]
Hi guys, just to let you know it looks like a bug in the latest IE11.0.47, which has reintroduced this bug.

**Comment by joezp** [comment]
In case anyone needs a solution, I basically made a version of _hacks() that relies on a focus flag set using mouseenter, mouseleave events on the menu. Seems to do the trick.

**Comment by worthy7** [comment]
That's what I did too: 
https://github.com/corejavascript/typeahead.js/issues/166

**Comment by joezp** [comment]
mouseenter/leave didn't occur to me until I saw this on a similar problem.
https://stackoverflow.com/questions/2284541/form-input-loses-focus-on-scroll-bar-click-in-ie
