### ISSUE TITLE
Typeahead vs Meteor new templating engine

### ISSUE THREAD

**Issue by dbismut** [twitter/typeahead.js#709]
I struggled a bit (I'm new to Meteor so sorry if this is obvious to others) so I thought I'd share how to use your own template with [Meteor New Templating UI](https://github.com/meteor/meteor/wiki/New-Template-Engine-Preview):

You need to use:

``` javascript
$(input).typeahead(null, {
    displayKey: 'value',
    source: yoursource.ttAdapter(),
    templates: {
        suggestion: function(suggestion) {
            return UI.toHTML(Template.autocomplete, suggestion);
        }
    }
});
```

`Template.autocomplete` is obviously defined using `<template name="autocomplete">...</template>` in a `.html` file.

Hope this helps.

**Comment by 2gen** [comment]
For anyone else looking to do this, you need to use UI.toHTMLWithData:

```js
suggestion: function(suggestion) {
  return UI.toHTMLWithData(Template.autocomplete, suggestion);
}
