### ISSUE TITLE
Unable to focus typeahead input programmatically

### ISSUE THREAD

**Issue by tgoetz** [twitter/typeahead.js#712]
I try to set focus on a typeahead input by calling $('#myTypeahead').focus(), but this does not set the focus in the input. Any hint how this can be achieved?

**Comment by tchoulihan** [comment]
This is still broken.

**Comment by hungsu** [comment]
Thanks for your comment @tchoulihan . Just tried that myself and it works for me, that's so bizarre that that works.

**Comment by tarunbatra11** [comment]
$("tt-menu").addClass("tt-open");

Adding this will over write the default behaviour of typeahead.

**Comment by NinjaKC** [comment]
This still happens if your typeahead input is within a modal. I have found that not even using the setTimeout technique (at any length of delay), does not seem to focus the input properly when typeahead is enabled on it.

**Comment by namtab00** [comment]
@NinjaKC 
This repo seems abandoned.. some kind souls continue maintaing it here: https://github.com/corejavascript/typeahead.js
I'd say the useful thing to do is sending pull requests and issues there.

**Comment by adamplabarge** [comment]
Having the same issue, can't focus on type ahead when in a modal.  typeahead 0.10.2 and bootstrap 2 modal - have yet to find a solution

**Comment by jeffz2012** [comment]
Typeahead input field in modal workaround. 

Assumption: modal outer shell has class="modal", if not, use yours.
A general class for all modals can be used, then this code once set, works each time.

<pre>
$('.modal').on('shown.bs.modal', function (e) {
    $(this).find('input').focus();
})
</pre>

Same idea can be used for non-modal typeaheads.
