### ISSUE TITLE
Avoid dropdown closing

### ISSUE THREAD

**Issue by pensiero** [twitter/typeahead.js#731]
How to accomplish it with the new version? Before 0.10 I did:

```
$(element).data("ttView").dropdownView.close = function() { };
$(element).parent().click(function(e) {
    e.stopPropagation();
});
$('body').click(function() {
    $(element).typeahead('val', '');
});
```

But now it doesn't work.

Thanks fot the replies

**Comment by jstejada** [comment]
should there be an option to prevent the dropdown from closing?

**Comment by jharding** [comment]
@jstejada so behavior are you looking to achieve? You want the menu to always be open?

**Comment by jstejada** [comment]
@jharding exactly! I want to be able to select multiple options, so I need to be able to select without closing the dropdown menu.

thanks!

**Comment by worleydl** [comment]
Seconded. I'd like to support clicking an element to show more data about a row but the default behavior is to select the clicked row and close out the dropdown.

**Comment by worleydl** [comment]
Well putting a click handler in and stopping the propagation works too, so I don't know if it's necessary to mod the library.

**Comment by jdrorrer** [comment]
@worleydl What did you hook the click handler up to?  I am trying to do the same thing on the suggestion, the menu, and the dataset, but stopPropogation() is not working for me.  Thank you!

**Comment by worleydl** [comment]
@jdrorrer I'm using an <a> tag for my row template.  Setting up a click handler at that level and stopping propagation prevents the dropdown from being closed.

**Comment by jdrorrer** [comment]
@worleydl For whatever reason, I couldn't get that to work.  However, this did the trick for me:  `.tt-menu {display: block !important;}`  Thanks again!
