### ISSUE TITLE
TAB event doesn't trigger typeahead:selecetd

### ISSUE THREAD

**Issue by a-lucas** [twitter/typeahead.js#735]
How to repeat : 

```
 var myCustomCallback = function(eventObject, suggestionObject, datasetName) {
    alert('hello');
 }

myTypeAhead.on('typeahead:selected', myCustomCallback);
```

Then navigate on your autocomplete field, type few letter so you get a list of items, and then press TAB. It will select the first item, but it won't trigger the :selected event.

**Comment by channainfo** [comment]
@jharding it works great with typeahead:autocompleted  thanks alot.
