### ISSUE TITLE
Empty item selectable

### ISSUE THREAD

**Issue by sandstrom** [twitter/typeahead.js#747]
It would be neat if the empty template could be a selectable choice (optional). Something like:

> "No results for Foo bar, create Foo Bar instead."

I guess we could filter/feed our own custom suggestion into the data as described here #253, but a boolean option emptyIsSelectable would be great.

**Comment by wamarante** [comment]
Hi, I tried your solution but it does not worked for me. 
Below is my bloodhound settings.  Any sugestions?

```
var person= new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('person_data'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
        url: "ac_lista_favorecidos.php?busca=%QUERY",
        filter: function(c) {
            var res = $.map(c, function(registro) {
                return {
                    id_favorecido: registro.ID_PERSON, 
                    nome_favorecido: registro.PERSON};
                });
            return res;
        },
        wildcard: "%QUERY"
    }
});
```
