### ISSUE TITLE
support for comma (or other) delineated fields

### ISSUE THREAD

**Issue by timprepscius** [twitter/typeahead.js#751]
I'm using this hack I came up with, but perhaps typeahead would like to do this correctly.

```
    fixTypeAheadToWorkWithCommas: function (input) {
        var z = $.data(input, 'ttTypeahead');
        z.input.getInputValue = function() {
            var s = z.input.$input.val();
            var c = s.lastIndexOf(',');
            return s.substr(c+1);
        };
        z.input.setInputValue = function(value, silent) {
            var s = z.input.$input.val();
            var c = s.lastIndexOf(',');
            var f = s.substr(0, c+1) + " " + value;
            z.input.$input.val(f);
        };

        z.input.setHintValue = function(val) {
            var s = z.input.$input.val();
            var c = s.lastIndexOf(',');
            var f = s.substr(0, c+1) + val;
            z.input.$hint.val(f);
        };

        z.input.clearHint = function() {
            z.input.setHintValue("");
        };

        z.input.resetInputValue = function () {
            z.input.setInputValue(z.input.query);
        }
```

**Comment by depiction** [comment]
Please add support for setting special characters to accept, like commas. I'm not using bootstrap so the tokenfield project won't work.

**Comment by timprepscius** [comment]
You might try looking at my project:

https://github.com/timprepscius/mv

I believe I made it tokenize without using tokenfield.

Perhaps look in:
https://github.com/timprepscius/mv/tree/master/client/web/Ext/sliptree-bootstrap-tokenfield-9e935ef

https://github.com/timprepscius/mv/blob/master/client/web/WebContent/templates/composeTemplate.html

https://github.com/timprepscius/mv/blob/master/client/web/WebContent/js/view/ComposeView.js

Not sure if this will help.

-tim

**Comment by timprepscius** [comment]
Oh, I see, _not_ bootstrap.  Sorry.  Brain malfunction.

-tim
