### ISSUE TITLE
Make dropdown stay always open and visible and have content

### ISSUE THREAD

**Issue by thany** [twitter/typeahead.js#796]
For debugging purposes. While styling the dropdown, it's extremely helpful to have the dropdown stay open then the input looses focus, so one can easily fiddle in firebug (or what have you) to finetune styling.

Currently the drodown closes when doing anything in firebug, so it's almost impossible to see what's applied and fiddle with it, especially on suggestion items.

**Comment by lddubeau** [comment]
With 0.10.5 I worked around the issue with this code:

    var tt = $.data([DOM node], "ttTypeahead");
    tt.input.off("blurred");
    tt._onBlurred = function () {
        this.isActivated = false;
    };
    tt.input.onSync("blurred", tt._onBlurred, tt);

`[DOM node]` is the DOM element on which the typeahead was created (e.g. `$([DOM node]).typeahead(...)`).

Unfortunately, any significant change to the core of the typeahead code will probably break this workaround. I tend stay away from such workarounds but the default behavior was significantly impacting the productivity of my users.

**Comment by jdrorrer** [comment]
I was able to get this working with a little css:
`.tt-menu { display: block !important; }`

I also set `data-min-length=0` on the data-source.

Not ideal, but it does the trick!

**Comment by heacu** [comment]
With 0.11.1, if I want to keep the menu open most of the time, then I just return false from the "beforeclose" event. For example:

``` javascript
input.bind('typeahead:beforeclose',
                function (e) {
                    // keep menu open if input element is still focused
                    if ($(e.target).is(':focus')) {
                        return false;
                    }
                }
            );
```
