### ISSUE TITLE
Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by majimboo** [twitter/typeahead.js#799]
Was following the examples on this site and kept getting this error:

```
 typeahead.bundle.min.js:7
 Uncaught TypeError: Cannot call method 'split' of undefined 
```

Is this a bug or something deprecated with the examples?

Was following the remote, custom examples.

**Comment by bhawi** [comment]
@jharding  I am also new to typeahead and got stuck, I am not getting the suggestions. Please help me out as I am new to this.

![git](https://cloud.githubusercontent.com/assets/11805689/6996705/afa316ca-dbb4-11e4-96c2-2eaf39a52f2d.PNG)
