### ISSUE TITLE
input-group-btn addon button with typeahead

### ISSUE THREAD

**Issue by alexweissman** [twitter/typeahead.js#847]
Is there an easy way to create an addon button for typeahead as in http://getbootstrap.com/components/#input-groups-buttons ?

I tried just using the `input-group-btn` inside an `input-group` along with the typeahead, but this doesn't seem to work as typeahead transforms the input field into a number of other fields.

**Comment by alsciende** [comment]
This issue is not resolved. Since this module is specifically targetted at Bootstrap, it would be nice if it could detect the presence of a `.input-group` around the input and plan accordingly, so that the altered markup doesn't invalidate Bootstrap's css. Would you accept a PR in that direction?
