### ISSUE TITLE
Single typeahead source with headers defined in json response?

### ISSUE THREAD

**Issue by alanhartless** [twitter/typeahead.js#851]
Is it possible to return template headers with the response or some way to dynamically parse them?  I need to be able to define a single source because the client doesn't know what the groups of suggestions are and thus I can't define each source with specific headers client side.  

It would be presented like the suggestions in the Multiple Datasets example.  
Header 1
    Option 1
    Option 2
    Option 3
Header 2
    Option 1
    Option 2
    Option 3
...

I'm not totally for sure how the response should be formatted.  Each row has something like array("header" => "Header 1", "value" => "Option 1") and then the values are grouped?  Or something like array("Header 1" => array("Option 1", "Option 2", "Option 3")?

Thanks,
Alan

**Comment by NielsInc** [comment]
Hi @alanhartless, did you manage to work around this restriction? 
I'm currently facing the same issue...
Br,
Niels
