### ISSUE TITLE
how to inspect .tt-dropdown-menu

### ISSUE THREAD

**Issue by agborkowski** [twitter/typeahead.js#852]
i had problem with custom styling of drop down, so i tried use inspect + toggle element state in chrome dev tools but of course didn't work, any suggestion to keep drop down for inspect ?

**Comment by sahanDissanayake** [comment]
http://stackoverflow.com/questions/29789767/keep-twitter-typeahead-suggestion-dropdown-open

Is there a easier way guys ? I cannot get the @bikerpower since my library is hosted on a cdn
