### ISSUE TITLE
Calling $(element).typeahead('val') returns Undefined

### ISSUE THREAD

**Issue by thedavidscherer** [twitter/typeahead.js#863]
Currently not possible to get the value of typeahead input as the `.typeahead('val')` reurns `Undefined`.

``` javascript
console.log($(this).typeahead('val', 'val')); // this works, value is set to 'val'
console.log($(this).typeahead('val')); // returns `Undefined`
```

**Comment by Baso1st** [comment]
The issue still exist v 0.11.1

**Comment by jenilInfyom** [comment]
@boldt
 I'm not able to get value of input using 
$('.typahead').typeahead('val');
