### ISSUE TITLE
filter isn't being called in IE9

### ISSUE THREAD

**Issue by slavajacobson** [twitter/typeahead.js#865]
This code doesn't work in IE9

http://jsfiddle.net/UkB7u/

Try adding alert or console.log within the filter and you will see that it never gets called. Works fine in Chrome/Firefox though.

UPDATE: I just discovered that %QUERY in the URL is what actually prevents it from working in IE9. URLs without %QUERY work fine in IE9.

UPDATE2: I am not 100% sure why it doesn't run in IE9. I will keep on investigating.

**Comment by jackblackCH** [comment]
Happens coz IE9- struggles with cross domain requests.

Another easy solution: add an automatic polyfill (after jquery) for lte: ie9-

```
<!--[if lte IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.3/jquery.xdomainrequest.min.js"></script>
<![endif]-->
```

**Comment by jackblackCH** [comment]
You should really add a comment to the docs. the docs say that its IE8+ compatible!
