### ISSUE TITLE
Npm install: isArray error when using Browserify

### ISSUE THREAD

**Issue by joshhornby** [twitter/typeahead.js#872]
I am using Browserify and trying to require the npm package of typeahead.js

``` js
var $ = require('jquery');
var typehead = require('typeahead.js');
```

When I run this in the browser I get the following error:

``` js
Uncaught TypeError: Cannot read property 'isArray' of undefined
```

Any ideas? Guessing it is an issue with jQuery not being loaded correctly?

**Comment by clayzermk1** [comment]
https://github.com/umdjs/umd anyone?

**Comment by davis** [comment]
es6 modules

**Comment by davis** [comment]
so how do we use this with browserify/webpack/jspm or is that still not a thing?

**Comment by rsshilli** [comment]
It's still not a thing, really.  This package is no longer maintained.  But luckily somebody forked it and is maintaining it here:

https://github.com/corejavascript/typeahead.js

And that one can be imported (at least using webpack) and seems to work great.
