### ISSUE TITLE
feature request: Allow developer to declare where results are displayed

### ISSUE THREAD

**Issue by harlanlewis** [twitter/typeahead.js#875]
As a developer, I would love to be able to render the results in an arbitrary `div`. In other words, use all of what makes Typeahead great except for for the dropdown presentation style and placement.

Have I missed an option for setting display location, or is this better suited to a custom implementation on top of Bloodhound?

**Comment by dustinlemos** [comment]
jharding, was this functionality ever added?

**Comment by rpokrovskij** [comment]
why `results` was not included to v0.11 release? https://github.com/twitter/typeahead.js/blob/master/dist/typeahead.jquery.js
