### ISSUE TITLE
Feature Request: Add Delay to typeahead when using an AJAX datasource.

### ISSUE THREAD

**Issue by amyth91** [twitter/typeahead.js#880]
Is it possible to add a delay to the source ajax call when using ajax json data source, currently it makes calls for every letter that is typed causing multiple server requests which takes long time to return data and because the 'requested word' has changed as the user types, the results returned are not correct sometimes. 

(Not sure if this request was made earlier, sorry if this is a duplicate one)

Thanks

**Comment by i44** [comment]
First request returns data in 1 sec, second request 1.4 sec likewise 1.6,1.9,1.1,0.8...so on. How do you make the customer expect the results at a constant time ? if you don't have a delay function in the UI component. JMO.
