### ISSUE TITLE
key/value pairs in JSON

### ISSUE THREAD

**Issue by paperscissors** [twitter/typeahead.js#890]
i'm wondering if it's possible to return a key/value pair in the JSON, so that when you're typing something in typeahead, it shows you the value, but when you select the item you want it actually puts the key as the input value?

so i.e.

"59936":"Silver Mt. Zion"

if you type "Silver" and select Silver Mt. Zion, it puts 59936 as the value of the input?

I'm not seeing of a way off the bat to do this, but i'm assuming it is possible.

**Comment by netbbe** [comment]
Valid question in 2021, too bad there is no reply
