### ISSUE TITLE
Multiple datasets not working when remote data sources used (introduced in latest release)

### ISSUE THREAD

**Issue by nhouse** [twitter/typeahead.js#896]
I am having the same issue as described here: https://github.com/twitter/typeahead.js/issues/104

I'm not sure whether I should be commenting in there, or creating a new issue, but since that was closed over a year ago I've chosen the latter.

The Typeahead example page shows how to use multiple datasets with Typeahead/Bloodhound. It works great when a local or prefetch data source is used, but it does not work with a remote data source. 

I posted my problem on StackOverflow before stumbling across the above issue: http://stackoverflow.com/questions/24727145/multiple-datasets-not-working-with-twitter-typeahead-bloodhound-when-remote-data

I am using the latest version of Typeahead and Bloodhound from here: http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.min.js

**Comment by sachintoshniwal** [comment]
Hello,

i am using bloodhounds js to bind autocomplete textbox. I am using cascading autocomplete just like select county & retrieve corresponding state. 

When i select first country i got data in state autocomplete & again i select another country then same data display in state field.

bloodhounds data source is not returning update data. it returns old data.I am using local Storage option in bloodhounds  js.

kindly suggest.

Thanks,
Sachin
