### ISSUE TITLE
While remote is being fetched, the prefetch items that where open and doesn't match the query anymore are still visible

### ISSUE THREAD

**Issue by escobar5** [twitter/typeahead.js#913]
If I look up for example 'Jhon', I get this results:

Jhon Wade
Jhonattan Peters
Jhon Wood

Then if I keep typing to: 'Jhon W', the result 'Jhonattan Peters' is still visible until the remote datasource is fetched completely.

Is this the way it should work, or is there anyway to get the local items filtered before the remote call?

**Comment by jharding** [comment]
This should be better in v0.11.
