### ISSUE TITLE
Turning off local storage

### ISSUE THREAD

**Issue by careyestes** [twitter/typeahead.js#943]
Is there a setting to turn off local storage? The JSON is larger than the local storage limit, so I get this error:

Uncaught QuotaExceededError:...

It still fetches properly, but I was wondering if I could turn off the attempt to store locally. I can comment this line:

// this.storage = this.cacheKey ? new PersistentStorage(this.cacheKey) : null;

which works, but I would rather leave the vendor file alone if possible.

**Comment by jharding** [comment]
Closing as duplicate of #920.
