### ISSUE TITLE
Duplicate detection when Bloodhound#add(datums) is used

### ISSUE THREAD

**Issue by addremove** [twitter/typeahead.js#946]
The dupDetector is good for detecting duplicates between local & remote match. However if I'm using `Bloodhound#add(datum)` to occasionally append data to the search index, I see duplicates showing up. 

Is that expected behavior? If yes, should it be patched in typeahead.js or should my code inspect the available list of suggestions and avoid duplicate manually?

**Comment by jharding** [comment]
This is now possible in v0.11 with usage of the `identify` option.
