### ISSUE TITLE
Substrings only match at beginning of word

### ISSUE THREAD

**Issue by seiz** [twitter/typeahead.js#96]
I don't know if this is on purpose, but substrings only match at the beginning of a word.
Searching for "ant" will find "antilope" or "ants" but not "giant" or "replicant".

**Comment by sturdynut** [comment]
If anyone finds there way here...I ended up adding more tokens in the datumTokenizer function.  Note that I am using lodash to trim empty space, you'll need to provide whatever trim function you are using here if you aren't using lodash or underscore.

> 'datum.name' is contrived.  If you are providing a data source of objects, you'll want to use whatever field is appropriate here.  If it is just a string, then you should just use 'datum'

```
datumTokenizer: function(datum) {
  var name = datum.name;
  var tokens = [name].concat(Bloodhound.tokenizers.nonword(name));

  for(var i = 1, l = name.length; i < l; i++) {
    var char = name.charAt(i);

    if(_.trim(char) !== ''
      && char === char.toUpperCase()) {
      tokens.push(name.slice(i));
    }
  }

  return tokens;
}
```

**Comment by namtab00** [comment]
@sturdynut 
This repo seems abandoned.. some kind souls continue maintaing it here: https://github.com/corejavascript/typeahead.js
I'd say the useful thing to do is sending pull request there.

**Comment by sturdynut** [comment]
@namtab00 - Thanks!  Good to know...:)
