### ISSUE TITLE
typeahead:closed event triggered when input loses focus

### ISSUE THREAD

**Issue by nhouse** [twitter/typeahead.js#982]
The typeahead:closed event is triggered when the input loses focus, which is contrary to the documentation description. I found [this question][2] on SO when searching for a solution to this issue.

>From documentations:

>> `typeahead:closed` – Triggered when the dropdown menu of a typeahead is
>> closed.

>But when adding `typeahead:closed` to typeahead, it will get triggered also `onblur`. 

>In this [fiddle][1], i have 

>    .on("typeahead:closed",function() {
>         alert("Dropdown Closed!"); 
>    });

>The alert will be triggered when the dropdown is closed and also when losing focus, click in and click out of the textbox you'll see the alert.

>Is this a bug? is there any way it should only be triggered when the dropdown menu is closed and not each time i'm clicking in and out? 

  [1]: http://jsfiddle.net/69b7hhv0/2/
  [2]: http://stackoverflow.com/questions/25271162/typeaheadclosed-will-be-triggered-when-losing-focus

**Comment by mrtom** [comment]
I'm also seeing this issue. Any update on a fix?

**Comment by jharding** [comment]
This stuff has been improved in v0.11. Take a look at the [docs](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events) for more details.
