### ISSUE TITLE
Fetching related data along with suggestions

### ISSUE THREAD

**Issue by addremove** [twitter/typeahead.js#984]
I'm fetching the names of cities from a database using typeahead. As the user types, bloodhound fetches the names of cities from the server. The database also contains additional info like city population, neighboring cities etc.. which doesn't need to be displayed to the user immediately but it's needed if the user selects a city from the suggestions. I can configure the server to send that additional data along with suggestions when bloodhound makes a request. But how do i store it & retrieve it from bloodhound when a result is selected? I'm trying to avoid a subsequent request when a suggestion is selected by the user.

**Comment by bitcity** [comment]
Any comments on this?

**Comment by jharding** [comment]
Apologies for closing without comment – was trying to do some clean up after leaving typeahead.js alone for too long.

If the user selects a suggestion, you can use the `typeahead:select` event to get the suggestion object. If the user types the entire value without selecting a suggestion, it's a little trickier. Is the latter scenario something you need to deal with?
