### ISSUE TITLE
Confused about ranking/ordering

### ISSUE THREAD

**Issue by addremove** [twitter/typeahead.js#985]
This is the `local` data I'm using with Typeahead. 

    var local  = [
        {value: 'Alpha Sheet B'},
        {value: 'Alpha Sheet C'},
        {value: 'Alpha Sheet D'},
        {value: 'Sheet A2'},
        {value: 'Sheet A'},
        {value: 'Sheet A1'}
]

When I type `Sheet A ` in the search box (with a space after `A`), I expect `Sheet A` to show up as the first search result, instead `Alpha Sheet B` etc. are ranked higher. Is this a bug? With a finite limit, it'll hide relevant results.

Here's a demo : http://jsfiddle.net/hc5udw6y/2/

**Comment by jharding** [comment]
Not a bug, there just isn't much logic in place for smart ordering.

**Comment by bitcity** [comment]
Any plans for providing a hook for ordering in this or the next version?
