### ISSUE TITLE
Input is cleared when loses focus, if field value provided with jQuery.val(val)

### ISSUE THREAD

**Issue by traone** [twitter/typeahead.js#991]
I have a dataset of cities and if the user has geolocation enabled, I populate the city field with a city name from Gmaps Geocode results. 

When the city field loses focus, the field value is cleared.

Should I set the field value some other way than $('.selector').val(currentCity); ?

**Comment by itinance** [comment]
thx @sandebert and @traone! I ran into the same 'issue'
