### ISSUE TITLE
requests stop after 6 connections, queued onDeckRequestArgs don't get sent

### ISSUE THREAD

**Issue by eaccka** [twitter/typeahead.js#993]
If more than 6 sources are used, the 7th and on requests do not get sent.

On line 349 of typeahead.bundle.js in the always() function, that.onDeckRequestArgs appears to always be undefined, so the block that fires queued get requests is not being fired, capping us off at the maximum of 6.

**Comment by jharding** [comment]
Unable to reproduce in v0.11. Let me know if you're still experiencing this problem and I'll take a closer look. Steps to reproduce would be helpful :smile:

**Comment by eaccka** [comment]
Issue persists in 0.11.1 with > 6 **remote** sources

**Comment by HeavyMedl** [comment]
I'm also seeing no more than 6 remote calls using 0.11.1

**Comment by mcgoncalves** [comment]
@jharding I'm experiencing the same problem reported in this issue. 
In [bloodhound transport](https://github.com/twitter/typeahead.js/blob/master/src/bloodhound/transport.js#L12) the maxPendingRequests is set to 6 and there's a [function to set this value](https://github.com/twitter/typeahead.js/blob/master/src/bloodhound/transport.js#L33), but I cannot access it. 
If I manually change the value from 6 to higher value it works.

_Repro for my case_ 
Use a typeahead with multiple datasets more than 6 (I'm getting the data using [remote](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote) from Bloodhound).
When you start typing on that typeahead it'll only get the first 6 datasets, while the other ones are ignored.

**Comment by sbsurf** [comment]
Why is this issue closed? This is still a problem.

**Comment by namtab00** [comment]
@sbsurf @mcgoncalves @eaccka  @kurtlocker 

This repo seems abandoned.. some kind souls continue maintaing it here: https://github.com/corejavascript/typeahead.js
I'd say the useful thing to do is sending pull requests and issues there.

**Comment by sbsurf** [comment]
If anyone wants to resolve this issue, you can use my code changes until this PR is merged:

https://github.com/corejavascript/typeahead.js/pull/62#issuecomment-186402183
