### ISSUE TITLE
Make tokenizers optional when not using local or prefetch in a Bloodhound engine

### ISSUE THREAD

**Issue by browles** [twitter/typeahead.js#997]
Currently you have to include both datumTokenizer and queryTokenizer even though neither will be used when we are delegating the autocompletion to a remote server, i.e. when in the options parameter passed to Bloodhound, .remote is specified but both .local and .prefetch are left undefined.

**Comment by X-O** [comment]
I suspect this has to do with these features:

- Uses local storage intelligently to cut down on network requests
- Rate-limits and caches network requests to remote sources to lighten the load

Which is nice if true.
But I am not sure what the correct datumTokenizer and queryTokenizer would be to make this work correctly. Especially in relation to #525.
Maybe the queryTokenizer should return the whole query.

**Comment by jharding** [comment]
I'd prefer to keep them required even when you're just using remote. The less special cases there are, the easier it is to manage the code and write documentation.
